// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: proto/mq/mq_message.proto

// Java 包的命名空间

package mq

import (
	common "github.com/bdsw/bdsw-im-ws/proto/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 事件类型枚举
type MQMessage_EventType int32

const (
	MQMessage_NEW_MESSAGE         MQMessage_EventType = 0  // 新消息
	MQMessage_MESSAGE_RECALL      MQMessage_EventType = 1  // 消息撤回
	MQMessage_MESSAGE_READ        MQMessage_EventType = 2  // 消息已读
	MQMessage_CONVERSATION_UPDATE MQMessage_EventType = 3  // 会话更新
	MQMessage_USER_ONLINE         MQMessage_EventType = 4  // 用户上线
	MQMessage_USER_OFFLINE        MQMessage_EventType = 5  // 用户下线
	MQMessage_GROUP_CREATE        MQMessage_EventType = 6  // 群组创建
	MQMessage_GROUP_UPDATE        MQMessage_EventType = 7  // 群组更新
	MQMessage_GROUP_MEMBER_CHANGE MQMessage_EventType = 8  // 群成员变更
	MQMessage_FRIEND_ADD          MQMessage_EventType = 9  // 好友添加
	MQMessage_FRIEND_DELETE       MQMessage_EventType = 10 // 好友删除
	MQMessage_PUSH_NOTIFICATION   MQMessage_EventType = 11 // 推送通知
	MQMessage_AI_CHAT_REQUEST     MQMessage_EventType = 12 // AI聊天请求
)

// Enum value maps for MQMessage_EventType.
var (
	MQMessage_EventType_name = map[int32]string{
		0:  "NEW_MESSAGE",
		1:  "MESSAGE_RECALL",
		2:  "MESSAGE_READ",
		3:  "CONVERSATION_UPDATE",
		4:  "USER_ONLINE",
		5:  "USER_OFFLINE",
		6:  "GROUP_CREATE",
		7:  "GROUP_UPDATE",
		8:  "GROUP_MEMBER_CHANGE",
		9:  "FRIEND_ADD",
		10: "FRIEND_DELETE",
		11: "PUSH_NOTIFICATION",
		12: "AI_CHAT_REQUEST",
	}
	MQMessage_EventType_value = map[string]int32{
		"NEW_MESSAGE":         0,
		"MESSAGE_RECALL":      1,
		"MESSAGE_READ":        2,
		"CONVERSATION_UPDATE": 3,
		"USER_ONLINE":         4,
		"USER_OFFLINE":        5,
		"GROUP_CREATE":        6,
		"GROUP_UPDATE":        7,
		"GROUP_MEMBER_CHANGE": 8,
		"FRIEND_ADD":          9,
		"FRIEND_DELETE":       10,
		"PUSH_NOTIFICATION":   11,
		"AI_CHAT_REQUEST":     12,
	}
)

func (x MQMessage_EventType) Enum() *MQMessage_EventType {
	p := new(MQMessage_EventType)
	*p = x
	return p
}

func (x MQMessage_EventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MQMessage_EventType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_mq_mq_message_proto_enumTypes[0].Descriptor()
}

func (MQMessage_EventType) Type() protoreflect.EnumType {
	return &file_proto_mq_mq_message_proto_enumTypes[0]
}

func (x MQMessage_EventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MQMessage_EventType.Descriptor instead.
func (MQMessage_EventType) EnumDescriptor() ([]byte, []int) {
	return file_proto_mq_mq_message_proto_rawDescGZIP(), []int{0, 0}
}

// MQ消息格式
type MQMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 消息头
	MsgId       string `protobuf:"bytes,1,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
	EventType   int32  `protobuf:"varint,2,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"` // 事件类型
	Producer    string `protobuf:"bytes,3,opt,name=producer,proto3" json:"producer,omitempty"`                     // 生产者
	ProduceTime int64  `protobuf:"varint,4,opt,name=produce_time,json=produceTime,proto3" json:"produce_time,omitempty"`
	// 消息体
	//
	// Types that are valid to be assigned to Body:
	//
	//	*MQMessage_MessageEvent
	//	*MQMessage_UserEvent
	//	*MQMessage_GroupEvent
	//	*MQMessage_FriendEvent
	//	*MQMessage_PushEvent
	//	*MQMessage_AiEvent
	Body          isMQMessage_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MQMessage) Reset() {
	*x = MQMessage{}
	mi := &file_proto_mq_mq_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MQMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MQMessage) ProtoMessage() {}

func (x *MQMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mq_mq_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MQMessage.ProtoReflect.Descriptor instead.
func (*MQMessage) Descriptor() ([]byte, []int) {
	return file_proto_mq_mq_message_proto_rawDescGZIP(), []int{0}
}

func (x *MQMessage) GetMsgId() string {
	if x != nil {
		return x.MsgId
	}
	return ""
}

func (x *MQMessage) GetEventType() int32 {
	if x != nil {
		return x.EventType
	}
	return 0
}

func (x *MQMessage) GetProducer() string {
	if x != nil {
		return x.Producer
	}
	return ""
}

func (x *MQMessage) GetProduceTime() int64 {
	if x != nil {
		return x.ProduceTime
	}
	return 0
}

func (x *MQMessage) GetBody() isMQMessage_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *MQMessage) GetMessageEvent() *MessageEvent {
	if x != nil {
		if x, ok := x.Body.(*MQMessage_MessageEvent); ok {
			return x.MessageEvent
		}
	}
	return nil
}

func (x *MQMessage) GetUserEvent() *UserEvent {
	if x != nil {
		if x, ok := x.Body.(*MQMessage_UserEvent); ok {
			return x.UserEvent
		}
	}
	return nil
}

func (x *MQMessage) GetGroupEvent() *GroupEvent {
	if x != nil {
		if x, ok := x.Body.(*MQMessage_GroupEvent); ok {
			return x.GroupEvent
		}
	}
	return nil
}

func (x *MQMessage) GetFriendEvent() *FriendEvent {
	if x != nil {
		if x, ok := x.Body.(*MQMessage_FriendEvent); ok {
			return x.FriendEvent
		}
	}
	return nil
}

func (x *MQMessage) GetPushEvent() *PushEvent {
	if x != nil {
		if x, ok := x.Body.(*MQMessage_PushEvent); ok {
			return x.PushEvent
		}
	}
	return nil
}

func (x *MQMessage) GetAiEvent() *AIEvent {
	if x != nil {
		if x, ok := x.Body.(*MQMessage_AiEvent); ok {
			return x.AiEvent
		}
	}
	return nil
}

type isMQMessage_Body interface {
	isMQMessage_Body()
}

type MQMessage_MessageEvent struct {
	MessageEvent *MessageEvent `protobuf:"bytes,5,opt,name=message_event,json=messageEvent,proto3,oneof"`
}

type MQMessage_UserEvent struct {
	UserEvent *UserEvent `protobuf:"bytes,6,opt,name=user_event,json=userEvent,proto3,oneof"`
}

type MQMessage_GroupEvent struct {
	GroupEvent *GroupEvent `protobuf:"bytes,7,opt,name=group_event,json=groupEvent,proto3,oneof"`
}

type MQMessage_FriendEvent struct {
	FriendEvent *FriendEvent `protobuf:"bytes,8,opt,name=friend_event,json=friendEvent,proto3,oneof"`
}

type MQMessage_PushEvent struct {
	PushEvent *PushEvent `protobuf:"bytes,9,opt,name=push_event,json=pushEvent,proto3,oneof"`
}

type MQMessage_AiEvent struct {
	AiEvent *AIEvent `protobuf:"bytes,10,opt,name=ai_event,json=aiEvent,proto3,oneof"`
}

func (*MQMessage_MessageEvent) isMQMessage_Body() {}

func (*MQMessage_UserEvent) isMQMessage_Body() {}

func (*MQMessage_GroupEvent) isMQMessage_Body() {}

func (*MQMessage_FriendEvent) isMQMessage_Body() {}

func (*MQMessage_PushEvent) isMQMessage_Body() {}

func (*MQMessage_AiEvent) isMQMessage_Body() {}

// 消息事件
type MessageEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       *common.Message        `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	TargetUserIds []string               `protobuf:"bytes,2,rep,name=target_user_ids,json=targetUserIds,proto3" json:"target_user_ids,omitempty"` // 目标用户ID列表
	NeedPush      bool                   `protobuf:"varint,3,opt,name=need_push,json=needPush,proto3" json:"need_push,omitempty"`                 // 是否需要推送
	NeedStore     bool                   `protobuf:"varint,4,opt,name=need_store,json=needStore,proto3" json:"need_store,omitempty"`              // 是否需要存储
	PushStrategy  int32                  `protobuf:"varint,5,opt,name=push_strategy,json=pushStrategy,proto3" json:"push_strategy,omitempty"`     // 推送策略
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageEvent) Reset() {
	*x = MessageEvent{}
	mi := &file_proto_mq_mq_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageEvent) ProtoMessage() {}

func (x *MessageEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mq_mq_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageEvent.ProtoReflect.Descriptor instead.
func (*MessageEvent) Descriptor() ([]byte, []int) {
	return file_proto_mq_mq_message_proto_rawDescGZIP(), []int{1}
}

func (x *MessageEvent) GetMessage() *common.Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *MessageEvent) GetTargetUserIds() []string {
	if x != nil {
		return x.TargetUserIds
	}
	return nil
}

func (x *MessageEvent) GetNeedPush() bool {
	if x != nil {
		return x.NeedPush
	}
	return false
}

func (x *MessageEvent) GetNeedStore() bool {
	if x != nil {
		return x.NeedStore
	}
	return false
}

func (x *MessageEvent) GetPushStrategy() int32 {
	if x != nil {
		return x.PushStrategy
	}
	return 0
}

// 用户事件
type UserEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DeviceId      string                 `protobuf:"bytes,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Event         int32                  `protobuf:"varint,3,opt,name=event,proto3" json:"event,omitempty"` // 1:上线 2:下线 3:状态变更
	Data          map[string]string      `protobuf:"bytes,4,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserEvent) Reset() {
	*x = UserEvent{}
	mi := &file_proto_mq_mq_message_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserEvent) ProtoMessage() {}

func (x *UserEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mq_mq_message_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserEvent.ProtoReflect.Descriptor instead.
func (*UserEvent) Descriptor() ([]byte, []int) {
	return file_proto_mq_mq_message_proto_rawDescGZIP(), []int{2}
}

func (x *UserEvent) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserEvent) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *UserEvent) GetEvent() int32 {
	if x != nil {
		return x.Event
	}
	return 0
}

func (x *UserEvent) GetData() map[string]string {
	if x != nil {
		return x.Data
	}
	return nil
}

// 群组事件
type GroupEvent struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	GroupId         string                 `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	OperatorId      string                 `protobuf:"bytes,2,opt,name=operator_id,json=operatorId,proto3" json:"operator_id,omitempty"`
	Event           int32                  `protobuf:"varint,3,opt,name=event,proto3" json:"event,omitempty"`                                             // 1:创建 2:更新 3:解散 4:成员变更
	AffectedUserIds []string               `protobuf:"bytes,4,rep,name=affected_user_ids,json=affectedUserIds,proto3" json:"affected_user_ids,omitempty"` // 受影响用户ID列表
	Data            map[string]string      `protobuf:"bytes,5,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GroupEvent) Reset() {
	*x = GroupEvent{}
	mi := &file_proto_mq_mq_message_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupEvent) ProtoMessage() {}

func (x *GroupEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mq_mq_message_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupEvent.ProtoReflect.Descriptor instead.
func (*GroupEvent) Descriptor() ([]byte, []int) {
	return file_proto_mq_mq_message_proto_rawDescGZIP(), []int{3}
}

func (x *GroupEvent) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *GroupEvent) GetOperatorId() string {
	if x != nil {
		return x.OperatorId
	}
	return ""
}

func (x *GroupEvent) GetEvent() int32 {
	if x != nil {
		return x.Event
	}
	return 0
}

func (x *GroupEvent) GetAffectedUserIds() []string {
	if x != nil {
		return x.AffectedUserIds
	}
	return nil
}

func (x *GroupEvent) GetData() map[string]string {
	if x != nil {
		return x.Data
	}
	return nil
}

// 好友事件
type FriendEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromUserId    string                 `protobuf:"bytes,1,opt,name=from_user_id,json=fromUserId,proto3" json:"from_user_id,omitempty"`
	ToUserId      string                 `protobuf:"bytes,2,opt,name=to_user_id,json=toUserId,proto3" json:"to_user_id,omitempty"`
	Event         int32                  `protobuf:"varint,3,opt,name=event,proto3" json:"event,omitempty"` // 1:添加 2:删除 3:申请 4:同意 5:拒绝
	Data          map[string]string      `protobuf:"bytes,4,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FriendEvent) Reset() {
	*x = FriendEvent{}
	mi := &file_proto_mq_mq_message_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FriendEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendEvent) ProtoMessage() {}

func (x *FriendEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mq_mq_message_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendEvent.ProtoReflect.Descriptor instead.
func (*FriendEvent) Descriptor() ([]byte, []int) {
	return file_proto_mq_mq_message_proto_rawDescGZIP(), []int{4}
}

func (x *FriendEvent) GetFromUserId() string {
	if x != nil {
		return x.FromUserId
	}
	return ""
}

func (x *FriendEvent) GetToUserId() string {
	if x != nil {
		return x.ToUserId
	}
	return ""
}

func (x *FriendEvent) GetEvent() int32 {
	if x != nil {
		return x.Event
	}
	return 0
}

func (x *FriendEvent) GetData() map[string]string {
	if x != nil {
		return x.Data
	}
	return nil
}

// 推送事件
type PushEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserIds       []string               `protobuf:"bytes,1,rep,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Payload       map[string]string      `protobuf:"bytes,4,rep,name=payload,proto3" json:"payload,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	PushType      int32                  `protobuf:"varint,5,opt,name=push_type,json=pushType,proto3" json:"push_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushEvent) Reset() {
	*x = PushEvent{}
	mi := &file_proto_mq_mq_message_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushEvent) ProtoMessage() {}

func (x *PushEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mq_mq_message_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushEvent.ProtoReflect.Descriptor instead.
func (*PushEvent) Descriptor() ([]byte, []int) {
	return file_proto_mq_mq_message_proto_rawDescGZIP(), []int{5}
}

func (x *PushEvent) GetUserIds() []string {
	if x != nil {
		return x.UserIds
	}
	return nil
}

func (x *PushEvent) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *PushEvent) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *PushEvent) GetPayload() map[string]string {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *PushEvent) GetPushType() int32 {
	if x != nil {
		return x.PushType
	}
	return 0
}

// AI事件（用于Hula的AI聊天功能）
type AIEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Query         string                 `protobuf:"bytes,3,opt,name=query,proto3" json:"query,omitempty"`
	AiModel       string                 `protobuf:"bytes,4,opt,name=ai_model,json=aiModel,proto3" json:"ai_model,omitempty"` // 使用的AI模型
	Parameters    map[string]string      `protobuf:"bytes,5,rep,name=parameters,proto3" json:"parameters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AIEvent) Reset() {
	*x = AIEvent{}
	mi := &file_proto_mq_mq_message_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AIEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AIEvent) ProtoMessage() {}

func (x *AIEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mq_mq_message_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AIEvent.ProtoReflect.Descriptor instead.
func (*AIEvent) Descriptor() ([]byte, []int) {
	return file_proto_mq_mq_message_proto_rawDescGZIP(), []int{6}
}

func (x *AIEvent) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *AIEvent) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AIEvent) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *AIEvent) GetAiModel() string {
	if x != nil {
		return x.AiModel
	}
	return ""
}

func (x *AIEvent) GetParameters() map[string]string {
	if x != nil {
		return x.Parameters
	}
	return nil
}

var File_proto_mq_mq_message_proto protoreflect.FileDescriptor

const file_proto_mq_mq_message_proto_rawDesc = "" +
	"\n" +
	"\x19proto/mq/mq_message.proto\x12\x11com.bdsw.proto.mq\x1a\x1aproto/common/message.proto\"\x9b\x06\n" +
	"\tMQMessage\x12\x15\n" +
	"\x06msg_id\x18\x01 \x01(\tR\x05msgId\x12\x1d\n" +
	"\n" +
	"event_type\x18\x02 \x01(\x05R\teventType\x12\x1a\n" +
	"\bproducer\x18\x03 \x01(\tR\bproducer\x12!\n" +
	"\fproduce_time\x18\x04 \x01(\x03R\vproduceTime\x12F\n" +
	"\rmessage_event\x18\x05 \x01(\v2\x1f.com.bdsw.proto.mq.MessageEventH\x00R\fmessageEvent\x12=\n" +
	"\n" +
	"user_event\x18\x06 \x01(\v2\x1c.com.bdsw.proto.mq.UserEventH\x00R\tuserEvent\x12@\n" +
	"\vgroup_event\x18\a \x01(\v2\x1d.com.bdsw.proto.mq.GroupEventH\x00R\n" +
	"groupEvent\x12C\n" +
	"\ffriend_event\x18\b \x01(\v2\x1e.com.bdsw.proto.mq.FriendEventH\x00R\vfriendEvent\x12=\n" +
	"\n" +
	"push_event\x18\t \x01(\v2\x1c.com.bdsw.proto.mq.PushEventH\x00R\tpushEvent\x127\n" +
	"\bai_event\x18\n" +
	" \x01(\v2\x1a.com.bdsw.proto.mq.AIEventH\x00R\aaiEvent\"\x8a\x02\n" +
	"\tEventType\x12\x0f\n" +
	"\vNEW_MESSAGE\x10\x00\x12\x12\n" +
	"\x0eMESSAGE_RECALL\x10\x01\x12\x10\n" +
	"\fMESSAGE_READ\x10\x02\x12\x17\n" +
	"\x13CONVERSATION_UPDATE\x10\x03\x12\x0f\n" +
	"\vUSER_ONLINE\x10\x04\x12\x10\n" +
	"\fUSER_OFFLINE\x10\x05\x12\x10\n" +
	"\fGROUP_CREATE\x10\x06\x12\x10\n" +
	"\fGROUP_UPDATE\x10\a\x12\x17\n" +
	"\x13GROUP_MEMBER_CHANGE\x10\b\x12\x0e\n" +
	"\n" +
	"FRIEND_ADD\x10\t\x12\x11\n" +
	"\rFRIEND_DELETE\x10\n" +
	"\x12\x15\n" +
	"\x11PUSH_NOTIFICATION\x10\v\x12\x13\n" +
	"\x0fAI_CHAT_REQUEST\x10\fB\x06\n" +
	"\x04body\"\xd1\x01\n" +
	"\fMessageEvent\x128\n" +
	"\amessage\x18\x01 \x01(\v2\x1e.com.bdsw.proto.common.MessageR\amessage\x12&\n" +
	"\x0ftarget_user_ids\x18\x02 \x03(\tR\rtargetUserIds\x12\x1b\n" +
	"\tneed_push\x18\x03 \x01(\bR\bneedPush\x12\x1d\n" +
	"\n" +
	"need_store\x18\x04 \x01(\bR\tneedStore\x12#\n" +
	"\rpush_strategy\x18\x05 \x01(\x05R\fpushStrategy\"\xcc\x01\n" +
	"\tUserEvent\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tdevice_id\x18\x02 \x01(\tR\bdeviceId\x12\x14\n" +
	"\x05event\x18\x03 \x01(\x05R\x05event\x12:\n" +
	"\x04data\x18\x04 \x03(\v2&.com.bdsw.proto.mq.UserEvent.DataEntryR\x04data\x1a7\n" +
	"\tDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x80\x02\n" +
	"\n" +
	"GroupEvent\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\tR\agroupId\x12\x1f\n" +
	"\voperator_id\x18\x02 \x01(\tR\n" +
	"operatorId\x12\x14\n" +
	"\x05event\x18\x03 \x01(\x05R\x05event\x12*\n" +
	"\x11affected_user_ids\x18\x04 \x03(\tR\x0faffectedUserIds\x12;\n" +
	"\x04data\x18\x05 \x03(\v2'.com.bdsw.proto.mq.GroupEvent.DataEntryR\x04data\x1a7\n" +
	"\tDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xda\x01\n" +
	"\vFriendEvent\x12 \n" +
	"\ffrom_user_id\x18\x01 \x01(\tR\n" +
	"fromUserId\x12\x1c\n" +
	"\n" +
	"to_user_id\x18\x02 \x01(\tR\btoUserId\x12\x14\n" +
	"\x05event\x18\x03 \x01(\x05R\x05event\x12<\n" +
	"\x04data\x18\x04 \x03(\v2(.com.bdsw.proto.mq.FriendEvent.DataEntryR\x04data\x1a7\n" +
	"\tDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xf4\x01\n" +
	"\tPushEvent\x12\x19\n" +
	"\buser_ids\x18\x01 \x03(\tR\auserIds\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12C\n" +
	"\apayload\x18\x04 \x03(\v2).com.bdsw.proto.mq.PushEvent.PayloadEntryR\apayload\x12\x1b\n" +
	"\tpush_type\x18\x05 \x01(\x05R\bpushType\x1a:\n" +
	"\fPayloadEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xfd\x01\n" +
	"\aAIEvent\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x14\n" +
	"\x05query\x18\x03 \x01(\tR\x05query\x12\x19\n" +
	"\bai_model\x18\x04 \x01(\tR\aaiModel\x12J\n" +
	"\n" +
	"parameters\x18\x05 \x03(\v2*.com.bdsw.proto.mq.AIEvent.ParametersEntryR\n" +
	"parameters\x1a=\n" +
	"\x0fParametersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01BM\n" +
	"\x11com.bdsw.proto.mqB\x0eMqMessageProtoP\x01Z&github.com/bdsw/bdsw-im-ws/proto/mq;mqb\x06proto3"

var (
	file_proto_mq_mq_message_proto_rawDescOnce sync.Once
	file_proto_mq_mq_message_proto_rawDescData []byte
)

func file_proto_mq_mq_message_proto_rawDescGZIP() []byte {
	file_proto_mq_mq_message_proto_rawDescOnce.Do(func() {
		file_proto_mq_mq_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_mq_mq_message_proto_rawDesc), len(file_proto_mq_mq_message_proto_rawDesc)))
	})
	return file_proto_mq_mq_message_proto_rawDescData
}

var file_proto_mq_mq_message_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_mq_mq_message_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_proto_mq_mq_message_proto_goTypes = []any{
	(MQMessage_EventType)(0), // 0: com.bdsw.proto.mq.MQMessage.EventType
	(*MQMessage)(nil),        // 1: com.bdsw.proto.mq.MQMessage
	(*MessageEvent)(nil),     // 2: com.bdsw.proto.mq.MessageEvent
	(*UserEvent)(nil),        // 3: com.bdsw.proto.mq.UserEvent
	(*GroupEvent)(nil),       // 4: com.bdsw.proto.mq.GroupEvent
	(*FriendEvent)(nil),      // 5: com.bdsw.proto.mq.FriendEvent
	(*PushEvent)(nil),        // 6: com.bdsw.proto.mq.PushEvent
	(*AIEvent)(nil),          // 7: com.bdsw.proto.mq.AIEvent
	nil,                      // 8: com.bdsw.proto.mq.UserEvent.DataEntry
	nil,                      // 9: com.bdsw.proto.mq.GroupEvent.DataEntry
	nil,                      // 10: com.bdsw.proto.mq.FriendEvent.DataEntry
	nil,                      // 11: com.bdsw.proto.mq.PushEvent.PayloadEntry
	nil,                      // 12: com.bdsw.proto.mq.AIEvent.ParametersEntry
	(*common.Message)(nil),   // 13: com.bdsw.proto.common.Message
}
var file_proto_mq_mq_message_proto_depIdxs = []int32{
	2,  // 0: com.bdsw.proto.mq.MQMessage.message_event:type_name -> com.bdsw.proto.mq.MessageEvent
	3,  // 1: com.bdsw.proto.mq.MQMessage.user_event:type_name -> com.bdsw.proto.mq.UserEvent
	4,  // 2: com.bdsw.proto.mq.MQMessage.group_event:type_name -> com.bdsw.proto.mq.GroupEvent
	5,  // 3: com.bdsw.proto.mq.MQMessage.friend_event:type_name -> com.bdsw.proto.mq.FriendEvent
	6,  // 4: com.bdsw.proto.mq.MQMessage.push_event:type_name -> com.bdsw.proto.mq.PushEvent
	7,  // 5: com.bdsw.proto.mq.MQMessage.ai_event:type_name -> com.bdsw.proto.mq.AIEvent
	13, // 6: com.bdsw.proto.mq.MessageEvent.message:type_name -> com.bdsw.proto.common.Message
	8,  // 7: com.bdsw.proto.mq.UserEvent.data:type_name -> com.bdsw.proto.mq.UserEvent.DataEntry
	9,  // 8: com.bdsw.proto.mq.GroupEvent.data:type_name -> com.bdsw.proto.mq.GroupEvent.DataEntry
	10, // 9: com.bdsw.proto.mq.FriendEvent.data:type_name -> com.bdsw.proto.mq.FriendEvent.DataEntry
	11, // 10: com.bdsw.proto.mq.PushEvent.payload:type_name -> com.bdsw.proto.mq.PushEvent.PayloadEntry
	12, // 11: com.bdsw.proto.mq.AIEvent.parameters:type_name -> com.bdsw.proto.mq.AIEvent.ParametersEntry
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_proto_mq_mq_message_proto_init() }
func file_proto_mq_mq_message_proto_init() {
	if File_proto_mq_mq_message_proto != nil {
		return
	}
	file_proto_mq_mq_message_proto_msgTypes[0].OneofWrappers = []any{
		(*MQMessage_MessageEvent)(nil),
		(*MQMessage_UserEvent)(nil),
		(*MQMessage_GroupEvent)(nil),
		(*MQMessage_FriendEvent)(nil),
		(*MQMessage_PushEvent)(nil),
		(*MQMessage_AiEvent)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_mq_mq_message_proto_rawDesc), len(file_proto_mq_mq_message_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_mq_mq_message_proto_goTypes,
		DependencyIndexes: file_proto_mq_mq_message_proto_depIdxs,
		EnumInfos:         file_proto_mq_mq_message_proto_enumTypes,
		MessageInfos:      file_proto_mq_mq_message_proto_msgTypes,
	}.Build()
	File_proto_mq_mq_message_proto = out.File
	file_proto_mq_mq_message_proto_goTypes = nil
	file_proto_mq_mq_message_proto_depIdxs = nil
}
