// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: proto/service/apns_service.proto

// Java 包的命名空间

package service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ApnsPushRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceToken   string                 `protobuf:"bytes,1,opt,name=device_token,json=deviceToken,proto3" json:"device_token,omitempty"`
	Payload       *ApnsPayload           `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	Headers       *ApnsHeaders           `protobuf:"bytes,3,opt,name=headers,proto3" json:"headers,omitempty"`
	Priority      int32                  `protobuf:"varint,4,opt,name=priority,proto3" json:"priority,omitempty"`                      // 10:即时 5:可延迟
	Expiration    int64                  `protobuf:"varint,5,opt,name=expiration,proto3" json:"expiration,omitempty"`                  // 过期时间戳
	CollapseId    string                 `protobuf:"bytes,6,opt,name=collapse_id,json=collapseId,proto3" json:"collapse_id,omitempty"` // 分组ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApnsPushRequest) Reset() {
	*x = ApnsPushRequest{}
	mi := &file_proto_service_apns_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApnsPushRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApnsPushRequest) ProtoMessage() {}

func (x *ApnsPushRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_apns_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApnsPushRequest.ProtoReflect.Descriptor instead.
func (*ApnsPushRequest) Descriptor() ([]byte, []int) {
	return file_proto_service_apns_service_proto_rawDescGZIP(), []int{0}
}

func (x *ApnsPushRequest) GetDeviceToken() string {
	if x != nil {
		return x.DeviceToken
	}
	return ""
}

func (x *ApnsPushRequest) GetPayload() *ApnsPayload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ApnsPushRequest) GetHeaders() *ApnsHeaders {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *ApnsPushRequest) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *ApnsPushRequest) GetExpiration() int64 {
	if x != nil {
		return x.Expiration
	}
	return 0
}

func (x *ApnsPushRequest) GetCollapseId() string {
	if x != nil {
		return x.CollapseId
	}
	return ""
}

type ApnsPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Aps           *Aps                   `protobuf:"bytes,1,opt,name=aps,proto3" json:"aps,omitempty"`
	CustomData    map[string]string      `protobuf:"bytes,2,rep,name=custom_data,json=customData,proto3" json:"custom_data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApnsPayload) Reset() {
	*x = ApnsPayload{}
	mi := &file_proto_service_apns_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApnsPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApnsPayload) ProtoMessage() {}

func (x *ApnsPayload) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_apns_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApnsPayload.ProtoReflect.Descriptor instead.
func (*ApnsPayload) Descriptor() ([]byte, []int) {
	return file_proto_service_apns_service_proto_rawDescGZIP(), []int{1}
}

func (x *ApnsPayload) GetAps() *Aps {
	if x != nil {
		return x.Aps
	}
	return nil
}

func (x *ApnsPayload) GetCustomData() map[string]string {
	if x != nil {
		return x.CustomData
	}
	return nil
}

type Aps struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Alert            *Alert                 `protobuf:"bytes,1,opt,name=alert,proto3" json:"alert,omitempty"`
	Badge            int32                  `protobuf:"varint,2,opt,name=badge,proto3" json:"badge,omitempty"`
	Sound            string                 `protobuf:"bytes,3,opt,name=sound,proto3" json:"sound,omitempty"`
	ContentAvailable int32                  `protobuf:"varint,4,opt,name=content_available,json=contentAvailable,proto3" json:"content_available,omitempty"` // 1:后台更新
	MutableContent   int32                  `protobuf:"varint,5,opt,name=mutable_content,json=mutableContent,proto3" json:"mutable_content,omitempty"`       // 1:可修改内容
	Category         string                 `protobuf:"bytes,6,opt,name=category,proto3" json:"category,omitempty"`
	ThreadId         string                 `protobuf:"bytes,7,opt,name=thread_id,json=threadId,proto3" json:"thread_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Aps) Reset() {
	*x = Aps{}
	mi := &file_proto_service_apns_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Aps) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Aps) ProtoMessage() {}

func (x *Aps) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_apns_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Aps.ProtoReflect.Descriptor instead.
func (*Aps) Descriptor() ([]byte, []int) {
	return file_proto_service_apns_service_proto_rawDescGZIP(), []int{2}
}

func (x *Aps) GetAlert() *Alert {
	if x != nil {
		return x.Alert
	}
	return nil
}

func (x *Aps) GetBadge() int32 {
	if x != nil {
		return x.Badge
	}
	return 0
}

func (x *Aps) GetSound() string {
	if x != nil {
		return x.Sound
	}
	return ""
}

func (x *Aps) GetContentAvailable() int32 {
	if x != nil {
		return x.ContentAvailable
	}
	return 0
}

func (x *Aps) GetMutableContent() int32 {
	if x != nil {
		return x.MutableContent
	}
	return 0
}

func (x *Aps) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *Aps) GetThreadId() string {
	if x != nil {
		return x.ThreadId
	}
	return ""
}

type Alert struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Subtitle      string                 `protobuf:"bytes,2,opt,name=subtitle,proto3" json:"subtitle,omitempty"`
	Body          string                 `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	TitleLocKey   string                 `protobuf:"bytes,4,opt,name=title_loc_key,json=titleLocKey,proto3" json:"title_loc_key,omitempty"`
	TitleLocArgs  []string               `protobuf:"bytes,5,rep,name=title_loc_args,json=titleLocArgs,proto3" json:"title_loc_args,omitempty"`
	LocKey        string                 `protobuf:"bytes,6,opt,name=loc_key,json=locKey,proto3" json:"loc_key,omitempty"`
	LocArgs       []string               `protobuf:"bytes,7,rep,name=loc_args,json=locArgs,proto3" json:"loc_args,omitempty"`
	ActionLocKey  string                 `protobuf:"bytes,8,opt,name=action_loc_key,json=actionLocKey,proto3" json:"action_loc_key,omitempty"`
	LaunchImage   string                 `protobuf:"bytes,9,opt,name=launch_image,json=launchImage,proto3" json:"launch_image,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Alert) Reset() {
	*x = Alert{}
	mi := &file_proto_service_apns_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Alert) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Alert) ProtoMessage() {}

func (x *Alert) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_apns_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Alert.ProtoReflect.Descriptor instead.
func (*Alert) Descriptor() ([]byte, []int) {
	return file_proto_service_apns_service_proto_rawDescGZIP(), []int{3}
}

func (x *Alert) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Alert) GetSubtitle() string {
	if x != nil {
		return x.Subtitle
	}
	return ""
}

func (x *Alert) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *Alert) GetTitleLocKey() string {
	if x != nil {
		return x.TitleLocKey
	}
	return ""
}

func (x *Alert) GetTitleLocArgs() []string {
	if x != nil {
		return x.TitleLocArgs
	}
	return nil
}

func (x *Alert) GetLocKey() string {
	if x != nil {
		return x.LocKey
	}
	return ""
}

func (x *Alert) GetLocArgs() []string {
	if x != nil {
		return x.LocArgs
	}
	return nil
}

func (x *Alert) GetActionLocKey() string {
	if x != nil {
		return x.ActionLocKey
	}
	return ""
}

func (x *Alert) GetLaunchImage() string {
	if x != nil {
		return x.LaunchImage
	}
	return ""
}

type ApnsHeaders struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ApnsId         string                 `protobuf:"bytes,1,opt,name=apns_id,json=apnsId,proto3" json:"apns_id,omitempty"`
	ApnsExpiration string                 `protobuf:"bytes,2,opt,name=apns_expiration,json=apnsExpiration,proto3" json:"apns_expiration,omitempty"`
	ApnsPriority   string                 `protobuf:"bytes,3,opt,name=apns_priority,json=apnsPriority,proto3" json:"apns_priority,omitempty"`
	ApnsTopic      string                 `protobuf:"bytes,4,opt,name=apns_topic,json=apnsTopic,proto3" json:"apns_topic,omitempty"`
	ApnsCollapseId string                 `protobuf:"bytes,5,opt,name=apns_collapse_id,json=apnsCollapseId,proto3" json:"apns_collapse_id,omitempty"`
	ApnsPushType   string                 `protobuf:"bytes,6,opt,name=apns_push_type,json=apnsPushType,proto3" json:"apns_push_type,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ApnsHeaders) Reset() {
	*x = ApnsHeaders{}
	mi := &file_proto_service_apns_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApnsHeaders) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApnsHeaders) ProtoMessage() {}

func (x *ApnsHeaders) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_apns_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApnsHeaders.ProtoReflect.Descriptor instead.
func (*ApnsHeaders) Descriptor() ([]byte, []int) {
	return file_proto_service_apns_service_proto_rawDescGZIP(), []int{4}
}

func (x *ApnsHeaders) GetApnsId() string {
	if x != nil {
		return x.ApnsId
	}
	return ""
}

func (x *ApnsHeaders) GetApnsExpiration() string {
	if x != nil {
		return x.ApnsExpiration
	}
	return ""
}

func (x *ApnsHeaders) GetApnsPriority() string {
	if x != nil {
		return x.ApnsPriority
	}
	return ""
}

func (x *ApnsHeaders) GetApnsTopic() string {
	if x != nil {
		return x.ApnsTopic
	}
	return ""
}

func (x *ApnsHeaders) GetApnsCollapseId() string {
	if x != nil {
		return x.ApnsCollapseId
	}
	return ""
}

func (x *ApnsHeaders) GetApnsPushType() string {
	if x != nil {
		return x.ApnsPushType
	}
	return ""
}

type ApnsPushResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ApnsId           string                 `protobuf:"bytes,1,opt,name=apns_id,json=apnsId,proto3" json:"apns_id,omitempty"`
	Success          bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Error            string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	ErrorDescription string                 `protobuf:"bytes,4,opt,name=error_description,json=errorDescription,proto3" json:"error_description,omitempty"`
	Timestamp        int64                  `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ApnsPushResponse) Reset() {
	*x = ApnsPushResponse{}
	mi := &file_proto_service_apns_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApnsPushResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApnsPushResponse) ProtoMessage() {}

func (x *ApnsPushResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_apns_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApnsPushResponse.ProtoReflect.Descriptor instead.
func (*ApnsPushResponse) Descriptor() ([]byte, []int) {
	return file_proto_service_apns_service_proto_rawDescGZIP(), []int{5}
}

func (x *ApnsPushResponse) GetApnsId() string {
	if x != nil {
		return x.ApnsId
	}
	return ""
}

func (x *ApnsPushResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ApnsPushResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ApnsPushResponse) GetErrorDescription() string {
	if x != nil {
		return x.ErrorDescription
	}
	return ""
}

func (x *ApnsPushResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type ValidateTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceTokens  []string               `protobuf:"bytes,1,rep,name=device_tokens,json=deviceTokens,proto3" json:"device_tokens,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateTokenRequest) Reset() {
	*x = ValidateTokenRequest{}
	mi := &file_proto_service_apns_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateTokenRequest) ProtoMessage() {}

func (x *ValidateTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_apns_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateTokenRequest.ProtoReflect.Descriptor instead.
func (*ValidateTokenRequest) Descriptor() ([]byte, []int) {
	return file_proto_service_apns_service_proto_rawDescGZIP(), []int{6}
}

func (x *ValidateTokenRequest) GetDeviceTokens() []string {
	if x != nil {
		return x.DeviceTokens
	}
	return nil
}

type ValidateTokenResponse struct {
	state         protoimpl.MessageState               `protogen:"open.v1"`
	Statuses      []*ValidateTokenResponse_TokenStatus `protobuf:"bytes,1,rep,name=statuses,proto3" json:"statuses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateTokenResponse) Reset() {
	*x = ValidateTokenResponse{}
	mi := &file_proto_service_apns_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateTokenResponse) ProtoMessage() {}

func (x *ValidateTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_apns_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateTokenResponse.ProtoReflect.Descriptor instead.
func (*ValidateTokenResponse) Descriptor() ([]byte, []int) {
	return file_proto_service_apns_service_proto_rawDescGZIP(), []int{7}
}

func (x *ValidateTokenResponse) GetStatuses() []*ValidateTokenResponse_TokenStatus {
	if x != nil {
		return x.Statuses
	}
	return nil
}

type StatisticsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartTime     int64                  `protobuf:"varint,1,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       int64                  `protobuf:"varint,2,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	Topic         string                 `protobuf:"bytes,3,opt,name=topic,proto3" json:"topic,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatisticsRequest) Reset() {
	*x = StatisticsRequest{}
	mi := &file_proto_service_apns_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatisticsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatisticsRequest) ProtoMessage() {}

func (x *StatisticsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_apns_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatisticsRequest.ProtoReflect.Descriptor instead.
func (*StatisticsRequest) Descriptor() ([]byte, []int) {
	return file_proto_service_apns_service_proto_rawDescGZIP(), []int{8}
}

func (x *StatisticsRequest) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *StatisticsRequest) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *StatisticsRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

type StatisticsResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TotalSent      int64                  `protobuf:"varint,1,opt,name=total_sent,json=totalSent,proto3" json:"total_sent,omitempty"`
	TotalDelivered int64                  `protobuf:"varint,2,opt,name=total_delivered,json=totalDelivered,proto3" json:"total_delivered,omitempty"`
	TotalFailed    int64                  `protobuf:"varint,3,opt,name=total_failed,json=totalFailed,proto3" json:"total_failed,omitempty"`
	FailureReasons map[string]int64       `protobuf:"bytes,4,rep,name=failure_reasons,json=failureReasons,proto3" json:"failure_reasons,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"` // 失败原因统计
	PeriodStart    int64                  `protobuf:"varint,5,opt,name=period_start,json=periodStart,proto3" json:"period_start,omitempty"`
	PeriodEnd      int64                  `protobuf:"varint,6,opt,name=period_end,json=periodEnd,proto3" json:"period_end,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StatisticsResponse) Reset() {
	*x = StatisticsResponse{}
	mi := &file_proto_service_apns_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatisticsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatisticsResponse) ProtoMessage() {}

func (x *StatisticsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_apns_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatisticsResponse.ProtoReflect.Descriptor instead.
func (*StatisticsResponse) Descriptor() ([]byte, []int) {
	return file_proto_service_apns_service_proto_rawDescGZIP(), []int{9}
}

func (x *StatisticsResponse) GetTotalSent() int64 {
	if x != nil {
		return x.TotalSent
	}
	return 0
}

func (x *StatisticsResponse) GetTotalDelivered() int64 {
	if x != nil {
		return x.TotalDelivered
	}
	return 0
}

func (x *StatisticsResponse) GetTotalFailed() int64 {
	if x != nil {
		return x.TotalFailed
	}
	return 0
}

func (x *StatisticsResponse) GetFailureReasons() map[string]int64 {
	if x != nil {
		return x.FailureReasons
	}
	return nil
}

func (x *StatisticsResponse) GetPeriodStart() int64 {
	if x != nil {
		return x.PeriodStart
	}
	return 0
}

func (x *StatisticsResponse) GetPeriodEnd() int64 {
	if x != nil {
		return x.PeriodEnd
	}
	return 0
}

type ValidateTokenResponse_TokenStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceToken   string                 `protobuf:"bytes,1,opt,name=device_token,json=deviceToken,proto3" json:"device_token,omitempty"`
	Valid         bool                   `protobuf:"varint,2,opt,name=valid,proto3" json:"valid,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	LastSeen      int64                  `protobuf:"varint,4,opt,name=last_seen,json=lastSeen,proto3" json:"last_seen,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateTokenResponse_TokenStatus) Reset() {
	*x = ValidateTokenResponse_TokenStatus{}
	mi := &file_proto_service_apns_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateTokenResponse_TokenStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateTokenResponse_TokenStatus) ProtoMessage() {}

func (x *ValidateTokenResponse_TokenStatus) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_apns_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateTokenResponse_TokenStatus.ProtoReflect.Descriptor instead.
func (*ValidateTokenResponse_TokenStatus) Descriptor() ([]byte, []int) {
	return file_proto_service_apns_service_proto_rawDescGZIP(), []int{7, 0}
}

func (x *ValidateTokenResponse_TokenStatus) GetDeviceToken() string {
	if x != nil {
		return x.DeviceToken
	}
	return ""
}

func (x *ValidateTokenResponse_TokenStatus) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *ValidateTokenResponse_TokenStatus) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *ValidateTokenResponse_TokenStatus) GetLastSeen() int64 {
	if x != nil {
		return x.LastSeen
	}
	return 0
}

var File_proto_service_apns_service_proto protoreflect.FileDescriptor

const file_proto_service_apns_service_proto_rawDesc = "" +
	"\n" +
	" proto/service/apns_service.proto\x12\x16com.bdsw.proto.service\"\x8f\x02\n" +
	"\x0fApnsPushRequest\x12!\n" +
	"\fdevice_token\x18\x01 \x01(\tR\vdeviceToken\x12=\n" +
	"\apayload\x18\x02 \x01(\v2#.com.bdsw.proto.service.ApnsPayloadR\apayload\x12=\n" +
	"\aheaders\x18\x03 \x01(\v2#.com.bdsw.proto.service.ApnsHeadersR\aheaders\x12\x1a\n" +
	"\bpriority\x18\x04 \x01(\x05R\bpriority\x12\x1e\n" +
	"\n" +
	"expiration\x18\x05 \x01(\x03R\n" +
	"expiration\x12\x1f\n" +
	"\vcollapse_id\x18\x06 \x01(\tR\n" +
	"collapseId\"\xd1\x01\n" +
	"\vApnsPayload\x12-\n" +
	"\x03aps\x18\x01 \x01(\v2\x1b.com.bdsw.proto.service.ApsR\x03aps\x12T\n" +
	"\vcustom_data\x18\x02 \x03(\v23.com.bdsw.proto.service.ApnsPayload.CustomDataEntryR\n" +
	"customData\x1a=\n" +
	"\x0fCustomDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xf5\x01\n" +
	"\x03Aps\x123\n" +
	"\x05alert\x18\x01 \x01(\v2\x1d.com.bdsw.proto.service.AlertR\x05alert\x12\x14\n" +
	"\x05badge\x18\x02 \x01(\x05R\x05badge\x12\x14\n" +
	"\x05sound\x18\x03 \x01(\tR\x05sound\x12+\n" +
	"\x11content_available\x18\x04 \x01(\x05R\x10contentAvailable\x12'\n" +
	"\x0fmutable_content\x18\x05 \x01(\x05R\x0emutableContent\x12\x1a\n" +
	"\bcategory\x18\x06 \x01(\tR\bcategory\x12\x1b\n" +
	"\tthread_id\x18\a \x01(\tR\bthreadId\"\x94\x02\n" +
	"\x05Alert\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x1a\n" +
	"\bsubtitle\x18\x02 \x01(\tR\bsubtitle\x12\x12\n" +
	"\x04body\x18\x03 \x01(\tR\x04body\x12\"\n" +
	"\rtitle_loc_key\x18\x04 \x01(\tR\vtitleLocKey\x12$\n" +
	"\x0etitle_loc_args\x18\x05 \x03(\tR\ftitleLocArgs\x12\x17\n" +
	"\aloc_key\x18\x06 \x01(\tR\x06locKey\x12\x19\n" +
	"\bloc_args\x18\a \x03(\tR\alocArgs\x12$\n" +
	"\x0eaction_loc_key\x18\b \x01(\tR\factionLocKey\x12!\n" +
	"\flaunch_image\x18\t \x01(\tR\vlaunchImage\"\xe3\x01\n" +
	"\vApnsHeaders\x12\x17\n" +
	"\aapns_id\x18\x01 \x01(\tR\x06apnsId\x12'\n" +
	"\x0fapns_expiration\x18\x02 \x01(\tR\x0eapnsExpiration\x12#\n" +
	"\rapns_priority\x18\x03 \x01(\tR\fapnsPriority\x12\x1d\n" +
	"\n" +
	"apns_topic\x18\x04 \x01(\tR\tapnsTopic\x12(\n" +
	"\x10apns_collapse_id\x18\x05 \x01(\tR\x0eapnsCollapseId\x12$\n" +
	"\x0eapns_push_type\x18\x06 \x01(\tR\fapnsPushType\"\xa6\x01\n" +
	"\x10ApnsPushResponse\x12\x17\n" +
	"\aapns_id\x18\x01 \x01(\tR\x06apnsId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\x12+\n" +
	"\x11error_description\x18\x04 \x01(\tR\x10errorDescription\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x03R\ttimestamp\";\n" +
	"\x14ValidateTokenRequest\x12#\n" +
	"\rdevice_tokens\x18\x01 \x03(\tR\fdeviceTokens\"\xeb\x01\n" +
	"\x15ValidateTokenResponse\x12U\n" +
	"\bstatuses\x18\x01 \x03(\v29.com.bdsw.proto.service.ValidateTokenResponse.TokenStatusR\bstatuses\x1a{\n" +
	"\vTokenStatus\x12!\n" +
	"\fdevice_token\x18\x01 \x01(\tR\vdeviceToken\x12\x14\n" +
	"\x05valid\x18\x02 \x01(\bR\x05valid\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\x12\x1b\n" +
	"\tlast_seen\x18\x04 \x01(\x03R\blastSeen\"c\n" +
	"\x11StatisticsRequest\x12\x1d\n" +
	"\n" +
	"start_time\x18\x01 \x01(\x03R\tstartTime\x12\x19\n" +
	"\bend_time\x18\x02 \x01(\x03R\aendTime\x12\x14\n" +
	"\x05topic\x18\x03 \x01(\tR\x05topic\"\xed\x02\n" +
	"\x12StatisticsResponse\x12\x1d\n" +
	"\n" +
	"total_sent\x18\x01 \x01(\x03R\ttotalSent\x12'\n" +
	"\x0ftotal_delivered\x18\x02 \x01(\x03R\x0etotalDelivered\x12!\n" +
	"\ftotal_failed\x18\x03 \x01(\x03R\vtotalFailed\x12g\n" +
	"\x0ffailure_reasons\x18\x04 \x03(\v2>.com.bdsw.proto.service.StatisticsResponse.FailureReasonsEntryR\x0efailureReasons\x12!\n" +
	"\fperiod_start\x18\x05 \x01(\x03R\vperiodStart\x12\x1d\n" +
	"\n" +
	"period_end\x18\x06 \x01(\x03R\tperiodEnd\x1aA\n" +
	"\x13FailureReasonsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x012\xd0\x02\n" +
	"\vApnsService\x12a\n" +
	"\fsendApnsPush\x12'.com.bdsw.proto.service.ApnsPushRequest\x1a(.com.bdsw.proto.service.ApnsPushResponse\x12r\n" +
	"\x13validateDeviceToken\x12,.com.bdsw.proto.service.ValidateTokenRequest\x1a-.com.bdsw.proto.service.ValidateTokenResponse\x12j\n" +
	"\x11getPushStatistics\x12).com.bdsw.proto.service.StatisticsRequest\x1a*.com.bdsw.proto.service.StatisticsResponseB^\n" +
	"\x16com.bdsw.proto.serviceB\x10ApnsServiceProtoP\x01Z0github.com/bdsw/bdsw-im-ws/proto/service;serviceb\x06proto3"

var (
	file_proto_service_apns_service_proto_rawDescOnce sync.Once
	file_proto_service_apns_service_proto_rawDescData []byte
)

func file_proto_service_apns_service_proto_rawDescGZIP() []byte {
	file_proto_service_apns_service_proto_rawDescOnce.Do(func() {
		file_proto_service_apns_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_service_apns_service_proto_rawDesc), len(file_proto_service_apns_service_proto_rawDesc)))
	})
	return file_proto_service_apns_service_proto_rawDescData
}

var file_proto_service_apns_service_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_proto_service_apns_service_proto_goTypes = []any{
	(*ApnsPushRequest)(nil),                   // 0: com.bdsw.proto.service.ApnsPushRequest
	(*ApnsPayload)(nil),                       // 1: com.bdsw.proto.service.ApnsPayload
	(*Aps)(nil),                               // 2: com.bdsw.proto.service.Aps
	(*Alert)(nil),                             // 3: com.bdsw.proto.service.Alert
	(*ApnsHeaders)(nil),                       // 4: com.bdsw.proto.service.ApnsHeaders
	(*ApnsPushResponse)(nil),                  // 5: com.bdsw.proto.service.ApnsPushResponse
	(*ValidateTokenRequest)(nil),              // 6: com.bdsw.proto.service.ValidateTokenRequest
	(*ValidateTokenResponse)(nil),             // 7: com.bdsw.proto.service.ValidateTokenResponse
	(*StatisticsRequest)(nil),                 // 8: com.bdsw.proto.service.StatisticsRequest
	(*StatisticsResponse)(nil),                // 9: com.bdsw.proto.service.StatisticsResponse
	nil,                                       // 10: com.bdsw.proto.service.ApnsPayload.CustomDataEntry
	(*ValidateTokenResponse_TokenStatus)(nil), // 11: com.bdsw.proto.service.ValidateTokenResponse.TokenStatus
	nil, // 12: com.bdsw.proto.service.StatisticsResponse.FailureReasonsEntry
}
var file_proto_service_apns_service_proto_depIdxs = []int32{
	1,  // 0: com.bdsw.proto.service.ApnsPushRequest.payload:type_name -> com.bdsw.proto.service.ApnsPayload
	4,  // 1: com.bdsw.proto.service.ApnsPushRequest.headers:type_name -> com.bdsw.proto.service.ApnsHeaders
	2,  // 2: com.bdsw.proto.service.ApnsPayload.aps:type_name -> com.bdsw.proto.service.Aps
	10, // 3: com.bdsw.proto.service.ApnsPayload.custom_data:type_name -> com.bdsw.proto.service.ApnsPayload.CustomDataEntry
	3,  // 4: com.bdsw.proto.service.Aps.alert:type_name -> com.bdsw.proto.service.Alert
	11, // 5: com.bdsw.proto.service.ValidateTokenResponse.statuses:type_name -> com.bdsw.proto.service.ValidateTokenResponse.TokenStatus
	12, // 6: com.bdsw.proto.service.StatisticsResponse.failure_reasons:type_name -> com.bdsw.proto.service.StatisticsResponse.FailureReasonsEntry
	0,  // 7: com.bdsw.proto.service.ApnsService.sendApnsPush:input_type -> com.bdsw.proto.service.ApnsPushRequest
	6,  // 8: com.bdsw.proto.service.ApnsService.validateDeviceToken:input_type -> com.bdsw.proto.service.ValidateTokenRequest
	8,  // 9: com.bdsw.proto.service.ApnsService.getPushStatistics:input_type -> com.bdsw.proto.service.StatisticsRequest
	5,  // 10: com.bdsw.proto.service.ApnsService.sendApnsPush:output_type -> com.bdsw.proto.service.ApnsPushResponse
	7,  // 11: com.bdsw.proto.service.ApnsService.validateDeviceToken:output_type -> com.bdsw.proto.service.ValidateTokenResponse
	9,  // 12: com.bdsw.proto.service.ApnsService.getPushStatistics:output_type -> com.bdsw.proto.service.StatisticsResponse
	10, // [10:13] is the sub-list for method output_type
	7,  // [7:10] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_proto_service_apns_service_proto_init() }
func file_proto_service_apns_service_proto_init() {
	if File_proto_service_apns_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_service_apns_service_proto_rawDesc), len(file_proto_service_apns_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_service_apns_service_proto_goTypes,
		DependencyIndexes: file_proto_service_apns_service_proto_depIdxs,
		MessageInfos:      file_proto_service_apns_service_proto_msgTypes,
	}.Build()
	File_proto_service_apns_service_proto = out.File
	file_proto_service_apns_service_proto_goTypes = nil
	file_proto_service_apns_service_proto_depIdxs = nil
}
