// Code generated by protoc-gen-go-triple. DO NOT EDIT.
// versions:
// - protoc-gen-go-triple v1.0.8
// - protoc             v6.32.1
// source: proto/service/apns_service.proto

package service

import (
	context "context"
	protocol "dubbo.apache.org/dubbo-go/v3/protocol"
	dubbo3 "dubbo.apache.org/dubbo-go/v3/protocol/dubbo3"
	invocation "dubbo.apache.org/dubbo-go/v3/protocol/invocation"
	grpc_go "github.com/dubbogo/grpc-go"
	codes "github.com/dubbogo/grpc-go/codes"
	metadata "github.com/dubbogo/grpc-go/metadata"
	status "github.com/dubbogo/grpc-go/status"
	common "github.com/dubbogo/triple/pkg/common"
	constant "github.com/dubbogo/triple/pkg/common/constant"
	triple "github.com/dubbogo/triple/pkg/triple"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc_go.SupportPackageIsVersion7

// ApnsServiceClient is the client API for ApnsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ApnsServiceClient interface {
	// 发送APNS推送
	SendApnsPush(ctx context.Context, in *ApnsPushRequest, opts ...grpc_go.CallOption) (*ApnsPushResponse, common.ErrorWithAttachment)
	// 验证设备令牌
	ValidateDeviceToken(ctx context.Context, in *ValidateTokenRequest, opts ...grpc_go.CallOption) (*ValidateTokenResponse, common.ErrorWithAttachment)
	// 获取推送统计
	GetPushStatistics(ctx context.Context, in *StatisticsRequest, opts ...grpc_go.CallOption) (*StatisticsResponse, common.ErrorWithAttachment)
}

type apnsServiceClient struct {
	cc *triple.TripleConn
}

type ApnsServiceClientImpl struct {
	SendApnsPush        func(ctx context.Context, in *ApnsPushRequest) (*ApnsPushResponse, error)
	ValidateDeviceToken func(ctx context.Context, in *ValidateTokenRequest) (*ValidateTokenResponse, error)
	GetPushStatistics   func(ctx context.Context, in *StatisticsRequest) (*StatisticsResponse, error)
}

func (c *ApnsServiceClientImpl) GetDubboStub(cc *triple.TripleConn) ApnsServiceClient {
	return NewApnsServiceClient(cc)
}

func (c *ApnsServiceClientImpl) XXX_InterfaceName() string {
	return "com.bdsw.proto.service.ApnsService"
}

func NewApnsServiceClient(cc *triple.TripleConn) ApnsServiceClient {
	return &apnsServiceClient{cc}
}

func (c *apnsServiceClient) SendApnsPush(ctx context.Context, in *ApnsPushRequest, opts ...grpc_go.CallOption) (*ApnsPushResponse, common.ErrorWithAttachment) {
	out := new(ApnsPushResponse)
	interfaceKey := ctx.Value(constant.InterfaceKey).(string)
	return out, c.cc.Invoke(ctx, "/"+interfaceKey+"/SendApnsPush", in, out)
}

func (c *apnsServiceClient) ValidateDeviceToken(ctx context.Context, in *ValidateTokenRequest, opts ...grpc_go.CallOption) (*ValidateTokenResponse, common.ErrorWithAttachment) {
	out := new(ValidateTokenResponse)
	interfaceKey := ctx.Value(constant.InterfaceKey).(string)
	return out, c.cc.Invoke(ctx, "/"+interfaceKey+"/ValidateDeviceToken", in, out)
}

func (c *apnsServiceClient) GetPushStatistics(ctx context.Context, in *StatisticsRequest, opts ...grpc_go.CallOption) (*StatisticsResponse, common.ErrorWithAttachment) {
	out := new(StatisticsResponse)
	interfaceKey := ctx.Value(constant.InterfaceKey).(string)
	return out, c.cc.Invoke(ctx, "/"+interfaceKey+"/GetPushStatistics", in, out)
}

// ApnsServiceServer is the server API for ApnsService service.
// All implementations must embed UnimplementedApnsServiceServer
// for forward compatibility
type ApnsServiceServer interface {
	// 发送APNS推送
	SendApnsPush(context.Context, *ApnsPushRequest) (*ApnsPushResponse, error)
	// 验证设备令牌
	ValidateDeviceToken(context.Context, *ValidateTokenRequest) (*ValidateTokenResponse, error)
	// 获取推送统计
	GetPushStatistics(context.Context, *StatisticsRequest) (*StatisticsResponse, error)
	mustEmbedUnimplementedApnsServiceServer()
}

// UnimplementedApnsServiceServer must be embedded to have forward compatible implementations.
type UnimplementedApnsServiceServer struct {
	proxyImpl protocol.Invoker
}

func (UnimplementedApnsServiceServer) SendApnsPush(context.Context, *ApnsPushRequest) (*ApnsPushResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendApnsPush not implemented")
}
func (UnimplementedApnsServiceServer) ValidateDeviceToken(context.Context, *ValidateTokenRequest) (*ValidateTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ValidateDeviceToken not implemented")
}
func (UnimplementedApnsServiceServer) GetPushStatistics(context.Context, *StatisticsRequest) (*StatisticsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPushStatistics not implemented")
}
func (s *UnimplementedApnsServiceServer) XXX_SetProxyImpl(impl protocol.Invoker) {
	s.proxyImpl = impl
}

func (s *UnimplementedApnsServiceServer) XXX_GetProxyImpl() protocol.Invoker {
	return s.proxyImpl
}

func (s *UnimplementedApnsServiceServer) XXX_ServiceDesc() *grpc_go.ServiceDesc {
	return &ApnsService_ServiceDesc
}
func (s *UnimplementedApnsServiceServer) XXX_InterfaceName() string {
	return "com.bdsw.proto.service.ApnsService"
}

func (UnimplementedApnsServiceServer) mustEmbedUnimplementedApnsServiceServer() {}

// UnsafeApnsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ApnsServiceServer will
// result in compilation errors.
type UnsafeApnsServiceServer interface {
	mustEmbedUnimplementedApnsServiceServer()
}

func RegisterApnsServiceServer(s grpc_go.ServiceRegistrar, srv ApnsServiceServer) {
	s.RegisterService(&ApnsService_ServiceDesc, srv)
}

func _ApnsService_SendApnsPush_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc_go.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApnsPushRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	base := srv.(dubbo3.Dubbo3GrpcService)
	args := []interface{}{}
	args = append(args, in)
	md, _ := metadata.FromIncomingContext(ctx)
	invAttachment := make(map[string]interface{}, len(md))
	for k, v := range md {
		invAttachment[k] = v
	}
	invo := invocation.NewRPCInvocation("SendApnsPush", args, invAttachment)
	if interceptor == nil {
		result := base.XXX_GetProxyImpl().Invoke(ctx, invo)
		return result, result.Error()
	}
	info := &grpc_go.UnaryServerInfo{
		Server:     srv,
		FullMethod: ctx.Value("XXX_TRIPLE_GO_INTERFACE_NAME").(string),
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		result := base.XXX_GetProxyImpl().Invoke(ctx, invo)
		return result, result.Error()
	}
	return interceptor(ctx, in, info, handler)
}

func _ApnsService_ValidateDeviceToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc_go.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	base := srv.(dubbo3.Dubbo3GrpcService)
	args := []interface{}{}
	args = append(args, in)
	md, _ := metadata.FromIncomingContext(ctx)
	invAttachment := make(map[string]interface{}, len(md))
	for k, v := range md {
		invAttachment[k] = v
	}
	invo := invocation.NewRPCInvocation("ValidateDeviceToken", args, invAttachment)
	if interceptor == nil {
		result := base.XXX_GetProxyImpl().Invoke(ctx, invo)
		return result, result.Error()
	}
	info := &grpc_go.UnaryServerInfo{
		Server:     srv,
		FullMethod: ctx.Value("XXX_TRIPLE_GO_INTERFACE_NAME").(string),
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		result := base.XXX_GetProxyImpl().Invoke(ctx, invo)
		return result, result.Error()
	}
	return interceptor(ctx, in, info, handler)
}

func _ApnsService_GetPushStatistics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc_go.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatisticsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	base := srv.(dubbo3.Dubbo3GrpcService)
	args := []interface{}{}
	args = append(args, in)
	md, _ := metadata.FromIncomingContext(ctx)
	invAttachment := make(map[string]interface{}, len(md))
	for k, v := range md {
		invAttachment[k] = v
	}
	invo := invocation.NewRPCInvocation("GetPushStatistics", args, invAttachment)
	if interceptor == nil {
		result := base.XXX_GetProxyImpl().Invoke(ctx, invo)
		return result, result.Error()
	}
	info := &grpc_go.UnaryServerInfo{
		Server:     srv,
		FullMethod: ctx.Value("XXX_TRIPLE_GO_INTERFACE_NAME").(string),
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		result := base.XXX_GetProxyImpl().Invoke(ctx, invo)
		return result, result.Error()
	}
	return interceptor(ctx, in, info, handler)
}

// ApnsService_ServiceDesc is the grpc_go.ServiceDesc for ApnsService service.
// It's only intended for direct use with grpc_go.RegisterService,
// and not to be introspected or modified (even as a copy)
var ApnsService_ServiceDesc = grpc_go.ServiceDesc{
	ServiceName: "com.bdsw.proto.service.ApnsService",
	HandlerType: (*ApnsServiceServer)(nil),
	Methods: []grpc_go.MethodDesc{
		{
			MethodName: "sendApnsPush",
			Handler:    _ApnsService_SendApnsPush_Handler,
		},
		{
			MethodName: "validateDeviceToken",
			Handler:    _ApnsService_ValidateDeviceToken_Handler,
		},
		{
			MethodName: "getPushStatistics",
			Handler:    _ApnsService_GetPushStatistics_Handler,
		},
	},
	Streams:  []grpc_go.StreamDesc{},
	Metadata: "proto/service/apns_service.proto",
}
