// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: proto/service/auth_service.proto

// Java 包的命名空间

package service

import (
	common "github.com/bdsw/bdsw-im-ws/proto/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 请求/响应消息定义
type PasswordLoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	DeviceInfo    *common.DeviceInfo     `protobuf:"bytes,3,opt,name=device_info,json=deviceInfo,proto3" json:"device_info,omitempty"`
	Captcha       string                 `protobuf:"bytes,4,opt,name=captcha,proto3" json:"captcha,omitempty"` // 验证码
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PasswordLoginRequest) Reset() {
	*x = PasswordLoginRequest{}
	mi := &file_proto_service_auth_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PasswordLoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PasswordLoginRequest) ProtoMessage() {}

func (x *PasswordLoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_auth_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PasswordLoginRequest.ProtoReflect.Descriptor instead.
func (*PasswordLoginRequest) Descriptor() ([]byte, []int) {
	return file_proto_service_auth_service_proto_rawDescGZIP(), []int{0}
}

func (x *PasswordLoginRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *PasswordLoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *PasswordLoginRequest) GetDeviceInfo() *common.DeviceInfo {
	if x != nil {
		return x.DeviceInfo
	}
	return nil
}

func (x *PasswordLoginRequest) GetCaptcha() string {
	if x != nil {
		return x.Captcha
	}
	return ""
}

type TokenLoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	DeviceInfo    *common.DeviceInfo     `protobuf:"bytes,2,opt,name=device_info,json=deviceInfo,proto3" json:"device_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenLoginRequest) Reset() {
	*x = TokenLoginRequest{}
	mi := &file_proto_service_auth_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenLoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenLoginRequest) ProtoMessage() {}

func (x *TokenLoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_auth_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenLoginRequest.ProtoReflect.Descriptor instead.
func (*TokenLoginRequest) Descriptor() ([]byte, []int) {
	return file_proto_service_auth_service_proto_rawDescGZIP(), []int{1}
}

func (x *TokenLoginRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *TokenLoginRequest) GetDeviceInfo() *common.DeviceInfo {
	if x != nil {
		return x.DeviceInfo
	}
	return nil
}

type GenerateQRCodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	ExpireSeconds int32                  `protobuf:"varint,2,opt,name=expire_seconds,json=expireSeconds,proto3" json:"expire_seconds,omitempty"` // 二维码过期时间（秒）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateQRCodeRequest) Reset() {
	*x = GenerateQRCodeRequest{}
	mi := &file_proto_service_auth_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateQRCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateQRCodeRequest) ProtoMessage() {}

func (x *GenerateQRCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_auth_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateQRCodeRequest.ProtoReflect.Descriptor instead.
func (*GenerateQRCodeRequest) Descriptor() ([]byte, []int) {
	return file_proto_service_auth_service_proto_rawDescGZIP(), []int{2}
}

func (x *GenerateQRCodeRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *GenerateQRCodeRequest) GetExpireSeconds() int32 {
	if x != nil {
		return x.ExpireSeconds
	}
	return 0
}

type QRCodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QrcodeId      string                 `protobuf:"bytes,1,opt,name=qrcode_id,json=qrcodeId,proto3" json:"qrcode_id,omitempty"`
	QrcodeUrl     string                 `protobuf:"bytes,2,opt,name=qrcode_url,json=qrcodeUrl,proto3" json:"qrcode_url,omitempty"`
	QrcodeData    string                 `protobuf:"bytes,3,opt,name=qrcode_data,json=qrcodeData,proto3" json:"qrcode_data,omitempty"` // base64编码的二维码图片
	ExpireAt      int64                  `protobuf:"varint,4,opt,name=expire_at,json=expireAt,proto3" json:"expire_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QRCodeResponse) Reset() {
	*x = QRCodeResponse{}
	mi := &file_proto_service_auth_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QRCodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QRCodeResponse) ProtoMessage() {}

func (x *QRCodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_auth_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QRCodeResponse.ProtoReflect.Descriptor instead.
func (*QRCodeResponse) Descriptor() ([]byte, []int) {
	return file_proto_service_auth_service_proto_rawDescGZIP(), []int{3}
}

func (x *QRCodeResponse) GetQrcodeId() string {
	if x != nil {
		return x.QrcodeId
	}
	return ""
}

func (x *QRCodeResponse) GetQrcodeUrl() string {
	if x != nil {
		return x.QrcodeUrl
	}
	return ""
}

func (x *QRCodeResponse) GetQrcodeData() string {
	if x != nil {
		return x.QrcodeData
	}
	return ""
}

func (x *QRCodeResponse) GetExpireAt() int64 {
	if x != nil {
		return x.ExpireAt
	}
	return 0
}

type ConfirmQRCodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QrcodeId      string                 `protobuf:"bytes,1,opt,name=qrcode_id,json=qrcodeId,proto3" json:"qrcode_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Confirm       bool                   `protobuf:"varint,3,opt,name=confirm,proto3" json:"confirm,omitempty"` // true:确认登录 false:取消登录
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmQRCodeRequest) Reset() {
	*x = ConfirmQRCodeRequest{}
	mi := &file_proto_service_auth_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmQRCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmQRCodeRequest) ProtoMessage() {}

func (x *ConfirmQRCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_auth_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmQRCodeRequest.ProtoReflect.Descriptor instead.
func (*ConfirmQRCodeRequest) Descriptor() ([]byte, []int) {
	return file_proto_service_auth_service_proto_rawDescGZIP(), []int{4}
}

func (x *ConfirmQRCodeRequest) GetQrcodeId() string {
	if x != nil {
		return x.QrcodeId
	}
	return ""
}

func (x *ConfirmQRCodeRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ConfirmQRCodeRequest) GetConfirm() bool {
	if x != nil {
		return x.Confirm
	}
	return false
}

type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *common.User           `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	AuthToken     *AuthToken             `protobuf:"bytes,2,opt,name=auth_token,json=authToken,proto3" json:"auth_token,omitempty"`
	DeviceInfo    *common.DeviceInfo     `protobuf:"bytes,3,opt,name=device_info,json=deviceInfo,proto3" json:"device_info,omitempty"`
	OtherDevices  []*common.DeviceInfo   `protobuf:"bytes,4,rep,name=other_devices,json=otherDevices,proto3" json:"other_devices,omitempty"` // 其他在线设备
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_proto_service_auth_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_auth_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_proto_service_auth_service_proto_rawDescGZIP(), []int{5}
}

func (x *LoginResponse) GetUser() *common.User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *LoginResponse) GetAuthToken() *AuthToken {
	if x != nil {
		return x.AuthToken
	}
	return nil
}

func (x *LoginResponse) GetDeviceInfo() *common.DeviceInfo {
	if x != nil {
		return x.DeviceInfo
	}
	return nil
}

func (x *LoginResponse) GetOtherDevices() []*common.DeviceInfo {
	if x != nil {
		return x.OtherDevices
	}
	return nil
}

type LogoutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DeviceId      string                 `protobuf:"bytes,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	LogoutAll     bool                   `protobuf:"varint,3,opt,name=logout_all,json=logoutAll,proto3" json:"logout_all,omitempty"` // 是否登出所有设备
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutRequest) Reset() {
	*x = LogoutRequest{}
	mi := &file_proto_service_auth_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutRequest) ProtoMessage() {}

func (x *LogoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_auth_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutRequest.ProtoReflect.Descriptor instead.
func (*LogoutRequest) Descriptor() ([]byte, []int) {
	return file_proto_service_auth_service_proto_rawDescGZIP(), []int{6}
}

func (x *LogoutRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *LogoutRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *LogoutRequest) GetLogoutAll() bool {
	if x != nil {
		return x.LogoutAll
	}
	return false
}

type RefreshTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefreshToken  string                 `protobuf:"bytes,1,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshTokenRequest) Reset() {
	*x = RefreshTokenRequest{}
	mi := &file_proto_service_auth_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokenRequest) ProtoMessage() {}

func (x *RefreshTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_auth_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTokenRequest.ProtoReflect.Descriptor instead.
func (*RefreshTokenRequest) Descriptor() ([]byte, []int) {
	return file_proto_service_auth_service_proto_rawDescGZIP(), []int{7}
}

func (x *RefreshTokenRequest) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type TokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuthToken     *AuthToken             `protobuf:"bytes,1,opt,name=auth_token,json=authToken,proto3" json:"auth_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenResponse) Reset() {
	*x = TokenResponse{}
	mi := &file_proto_service_auth_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenResponse) ProtoMessage() {}

func (x *TokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_auth_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenResponse.ProtoReflect.Descriptor instead.
func (*TokenResponse) Descriptor() ([]byte, []int) {
	return file_proto_service_auth_service_proto_rawDescGZIP(), []int{8}
}

func (x *TokenResponse) GetAuthToken() *AuthToken {
	if x != nil {
		return x.AuthToken
	}
	return nil
}

type VerifyTokenRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Token              string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	RequiredPermission string                 `protobuf:"bytes,2,opt,name=required_permission,json=requiredPermission,proto3" json:"required_permission,omitempty"` // 需要的权限
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *VerifyTokenRequest) Reset() {
	*x = VerifyTokenRequest{}
	mi := &file_proto_service_auth_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyTokenRequest) ProtoMessage() {}

func (x *VerifyTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_auth_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyTokenRequest.ProtoReflect.Descriptor instead.
func (*VerifyTokenRequest) Descriptor() ([]byte, []int) {
	return file_proto_service_auth_service_proto_rawDescGZIP(), []int{9}
}

func (x *VerifyTokenRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *VerifyTokenRequest) GetRequiredPermission() string {
	if x != nil {
		return x.RequiredPermission
	}
	return ""
}

type VerifyTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valid         bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Permissions   []string               `protobuf:"bytes,3,rep,name=permissions,proto3" json:"permissions,omitempty"` // 用户拥有的权限
	ExpireAt      int64                  `protobuf:"varint,4,opt,name=expire_at,json=expireAt,proto3" json:"expire_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyTokenResponse) Reset() {
	*x = VerifyTokenResponse{}
	mi := &file_proto_service_auth_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyTokenResponse) ProtoMessage() {}

func (x *VerifyTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_auth_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyTokenResponse.ProtoReflect.Descriptor instead.
func (*VerifyTokenResponse) Descriptor() ([]byte, []int) {
	return file_proto_service_auth_service_proto_rawDescGZIP(), []int{10}
}

func (x *VerifyTokenResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *VerifyTokenResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *VerifyTokenResponse) GetPermissions() []string {
	if x != nil {
		return x.Permissions
	}
	return nil
}

func (x *VerifyTokenResponse) GetExpireAt() int64 {
	if x != nil {
		return x.ExpireAt
	}
	return 0
}

type ForceLogoutRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OperatorId     string                 `protobuf:"bytes,1,opt,name=operator_id,json=operatorId,proto3" json:"operator_id,omitempty"` // 操作人ID
	TargetUserId   string                 `protobuf:"bytes,2,opt,name=target_user_id,json=targetUserId,proto3" json:"target_user_id,omitempty"`
	TargetDeviceId string                 `protobuf:"bytes,3,opt,name=target_device_id,json=targetDeviceId,proto3" json:"target_device_id,omitempty"` // 为空则踢出所有设备
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ForceLogoutRequest) Reset() {
	*x = ForceLogoutRequest{}
	mi := &file_proto_service_auth_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForceLogoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForceLogoutRequest) ProtoMessage() {}

func (x *ForceLogoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_auth_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForceLogoutRequest.ProtoReflect.Descriptor instead.
func (*ForceLogoutRequest) Descriptor() ([]byte, []int) {
	return file_proto_service_auth_service_proto_rawDescGZIP(), []int{11}
}

func (x *ForceLogoutRequest) GetOperatorId() string {
	if x != nil {
		return x.OperatorId
	}
	return ""
}

func (x *ForceLogoutRequest) GetTargetUserId() string {
	if x != nil {
		return x.TargetUserId
	}
	return ""
}

func (x *ForceLogoutRequest) GetTargetDeviceId() string {
	if x != nil {
		return x.TargetDeviceId
	}
	return ""
}

type UserDevicesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserDevicesRequest) Reset() {
	*x = UserDevicesRequest{}
	mi := &file_proto_service_auth_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserDevicesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserDevicesRequest) ProtoMessage() {}

func (x *UserDevicesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_auth_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserDevicesRequest.ProtoReflect.Descriptor instead.
func (*UserDevicesRequest) Descriptor() ([]byte, []int) {
	return file_proto_service_auth_service_proto_rawDescGZIP(), []int{12}
}

func (x *UserDevicesRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type UserDevicesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Devices       []*common.DeviceInfo   `protobuf:"bytes,1,rep,name=devices,proto3" json:"devices,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserDevicesResponse) Reset() {
	*x = UserDevicesResponse{}
	mi := &file_proto_service_auth_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserDevicesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserDevicesResponse) ProtoMessage() {}

func (x *UserDevicesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_auth_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserDevicesResponse.ProtoReflect.Descriptor instead.
func (*UserDevicesResponse) Descriptor() ([]byte, []int) {
	return file_proto_service_auth_service_proto_rawDescGZIP(), []int{13}
}

func (x *UserDevicesResponse) GetDevices() []*common.DeviceInfo {
	if x != nil {
		return x.Devices
	}
	return nil
}

// 认证令牌
type AuthToken struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AccessToken     string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken    string                 `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	AccessExpireAt  int64                  `protobuf:"varint,3,opt,name=access_expire_at,json=accessExpireAt,proto3" json:"access_expire_at,omitempty"`
	RefreshExpireAt int64                  `protobuf:"varint,4,opt,name=refresh_expire_at,json=refreshExpireAt,proto3" json:"refresh_expire_at,omitempty"`
	TokenType       string                 `protobuf:"bytes,5,opt,name=token_type,json=tokenType,proto3" json:"token_type,omitempty"` // Bearer
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AuthToken) Reset() {
	*x = AuthToken{}
	mi := &file_proto_service_auth_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthToken) ProtoMessage() {}

func (x *AuthToken) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_auth_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthToken.ProtoReflect.Descriptor instead.
func (*AuthToken) Descriptor() ([]byte, []int) {
	return file_proto_service_auth_service_proto_rawDescGZIP(), []int{14}
}

func (x *AuthToken) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *AuthToken) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *AuthToken) GetAccessExpireAt() int64 {
	if x != nil {
		return x.AccessExpireAt
	}
	return 0
}

func (x *AuthToken) GetRefreshExpireAt() int64 {
	if x != nil {
		return x.RefreshExpireAt
	}
	return 0
}

func (x *AuthToken) GetTokenType() string {
	if x != nil {
		return x.TokenType
	}
	return ""
}

var File_proto_service_auth_service_proto protoreflect.FileDescriptor

const file_proto_service_auth_service_proto_rawDesc = "" +
	"\n" +
	" proto/service/auth_service.proto\x12\x16com.bdsw.proto.service\x1a\x19proto/common/common.proto\x1a\x17proto/common/user.proto\"\xac\x01\n" +
	"\x14PasswordLoginRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12B\n" +
	"\vdevice_info\x18\x03 \x01(\v2!.com.bdsw.proto.common.DeviceInfoR\n" +
	"deviceInfo\x12\x18\n" +
	"\acaptcha\x18\x04 \x01(\tR\acaptcha\"m\n" +
	"\x11TokenLoginRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12B\n" +
	"\vdevice_info\x18\x02 \x01(\v2!.com.bdsw.proto.common.DeviceInfoR\n" +
	"deviceInfo\"[\n" +
	"\x15GenerateQRCodeRequest\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12%\n" +
	"\x0eexpire_seconds\x18\x02 \x01(\x05R\rexpireSeconds\"\x8a\x01\n" +
	"\x0eQRCodeResponse\x12\x1b\n" +
	"\tqrcode_id\x18\x01 \x01(\tR\bqrcodeId\x12\x1d\n" +
	"\n" +
	"qrcode_url\x18\x02 \x01(\tR\tqrcodeUrl\x12\x1f\n" +
	"\vqrcode_data\x18\x03 \x01(\tR\n" +
	"qrcodeData\x12\x1b\n" +
	"\texpire_at\x18\x04 \x01(\x03R\bexpireAt\"f\n" +
	"\x14ConfirmQRCodeRequest\x12\x1b\n" +
	"\tqrcode_id\x18\x01 \x01(\tR\bqrcodeId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x18\n" +
	"\aconfirm\x18\x03 \x01(\bR\aconfirm\"\x8e\x02\n" +
	"\rLoginResponse\x12/\n" +
	"\x04user\x18\x01 \x01(\v2\x1b.com.bdsw.proto.common.UserR\x04user\x12@\n" +
	"\n" +
	"auth_token\x18\x02 \x01(\v2!.com.bdsw.proto.service.AuthTokenR\tauthToken\x12B\n" +
	"\vdevice_info\x18\x03 \x01(\v2!.com.bdsw.proto.common.DeviceInfoR\n" +
	"deviceInfo\x12F\n" +
	"\rother_devices\x18\x04 \x03(\v2!.com.bdsw.proto.common.DeviceInfoR\fotherDevices\"d\n" +
	"\rLogoutRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tdevice_id\x18\x02 \x01(\tR\bdeviceId\x12\x1d\n" +
	"\n" +
	"logout_all\x18\x03 \x01(\bR\tlogoutAll\":\n" +
	"\x13RefreshTokenRequest\x12#\n" +
	"\rrefresh_token\x18\x01 \x01(\tR\frefreshToken\"Q\n" +
	"\rTokenResponse\x12@\n" +
	"\n" +
	"auth_token\x18\x01 \x01(\v2!.com.bdsw.proto.service.AuthTokenR\tauthToken\"[\n" +
	"\x12VerifyTokenRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12/\n" +
	"\x13required_permission\x18\x02 \x01(\tR\x12requiredPermission\"\x83\x01\n" +
	"\x13VerifyTokenResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12 \n" +
	"\vpermissions\x18\x03 \x03(\tR\vpermissions\x12\x1b\n" +
	"\texpire_at\x18\x04 \x01(\x03R\bexpireAt\"\x85\x01\n" +
	"\x12ForceLogoutRequest\x12\x1f\n" +
	"\voperator_id\x18\x01 \x01(\tR\n" +
	"operatorId\x12$\n" +
	"\x0etarget_user_id\x18\x02 \x01(\tR\ftargetUserId\x12(\n" +
	"\x10target_device_id\x18\x03 \x01(\tR\x0etargetDeviceId\"-\n" +
	"\x12UserDevicesRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"R\n" +
	"\x13UserDevicesResponse\x12;\n" +
	"\adevices\x18\x01 \x03(\v2!.com.bdsw.proto.common.DeviceInfoR\adevices\"\xc8\x01\n" +
	"\tAuthToken\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x02 \x01(\tR\frefreshToken\x12(\n" +
	"\x10access_expire_at\x18\x03 \x01(\x03R\x0eaccessExpireAt\x12*\n" +
	"\x11refresh_expire_at\x18\x04 \x01(\x03R\x0frefreshExpireAt\x12\x1d\n" +
	"\n" +
	"token_type\x18\x05 \x01(\tR\ttokenType2\x95\a\n" +
	"\vAuthService\x12f\n" +
	"\x0floginByPassword\x12,.com.bdsw.proto.service.PasswordLoginRequest\x1a%.com.bdsw.proto.service.LoginResponse\x12`\n" +
	"\floginByToken\x12).com.bdsw.proto.service.TokenLoginRequest\x1a%.com.bdsw.proto.service.LoginResponse\x12l\n" +
	"\x13generateLoginQRCode\x12-.com.bdsw.proto.service.GenerateQRCodeRequest\x1a&.com.bdsw.proto.service.QRCodeResponse\x12i\n" +
	"\x12confirmQRCodeLogin\x12,.com.bdsw.proto.service.ConfirmQRCodeRequest\x1a%.com.bdsw.proto.service.LoginResponse\x12P\n" +
	"\x06logout\x12%.com.bdsw.proto.service.LogoutRequest\x1a\x1f.com.bdsw.proto.common.Response\x12b\n" +
	"\frefreshToken\x12+.com.bdsw.proto.service.RefreshTokenRequest\x1a%.com.bdsw.proto.service.TokenResponse\x12f\n" +
	"\vverifyToken\x12*.com.bdsw.proto.service.VerifyTokenRequest\x1a+.com.bdsw.proto.service.VerifyTokenResponse\x12Z\n" +
	"\vforceLogout\x12*.com.bdsw.proto.service.ForceLogoutRequest\x1a\x1f.com.bdsw.proto.common.Response\x12i\n" +
	"\x0egetUserDevices\x12*.com.bdsw.proto.service.UserDevicesRequest\x1a+.com.bdsw.proto.service.UserDevicesResponseB^\n" +
	"\x16com.bdsw.proto.serviceB\x10AuthServiceProtoP\x01Z0github.com/bdsw/bdsw-im-ws/proto/service;serviceb\x06proto3"

var (
	file_proto_service_auth_service_proto_rawDescOnce sync.Once
	file_proto_service_auth_service_proto_rawDescData []byte
)

func file_proto_service_auth_service_proto_rawDescGZIP() []byte {
	file_proto_service_auth_service_proto_rawDescOnce.Do(func() {
		file_proto_service_auth_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_service_auth_service_proto_rawDesc), len(file_proto_service_auth_service_proto_rawDesc)))
	})
	return file_proto_service_auth_service_proto_rawDescData
}

var file_proto_service_auth_service_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_proto_service_auth_service_proto_goTypes = []any{
	(*PasswordLoginRequest)(nil),  // 0: com.bdsw.proto.service.PasswordLoginRequest
	(*TokenLoginRequest)(nil),     // 1: com.bdsw.proto.service.TokenLoginRequest
	(*GenerateQRCodeRequest)(nil), // 2: com.bdsw.proto.service.GenerateQRCodeRequest
	(*QRCodeResponse)(nil),        // 3: com.bdsw.proto.service.QRCodeResponse
	(*ConfirmQRCodeRequest)(nil),  // 4: com.bdsw.proto.service.ConfirmQRCodeRequest
	(*LoginResponse)(nil),         // 5: com.bdsw.proto.service.LoginResponse
	(*LogoutRequest)(nil),         // 6: com.bdsw.proto.service.LogoutRequest
	(*RefreshTokenRequest)(nil),   // 7: com.bdsw.proto.service.RefreshTokenRequest
	(*TokenResponse)(nil),         // 8: com.bdsw.proto.service.TokenResponse
	(*VerifyTokenRequest)(nil),    // 9: com.bdsw.proto.service.VerifyTokenRequest
	(*VerifyTokenResponse)(nil),   // 10: com.bdsw.proto.service.VerifyTokenResponse
	(*ForceLogoutRequest)(nil),    // 11: com.bdsw.proto.service.ForceLogoutRequest
	(*UserDevicesRequest)(nil),    // 12: com.bdsw.proto.service.UserDevicesRequest
	(*UserDevicesResponse)(nil),   // 13: com.bdsw.proto.service.UserDevicesResponse
	(*AuthToken)(nil),             // 14: com.bdsw.proto.service.AuthToken
	(*common.DeviceInfo)(nil),     // 15: com.bdsw.proto.common.DeviceInfo
	(*common.User)(nil),           // 16: com.bdsw.proto.common.User
	(*common.Response)(nil),       // 17: com.bdsw.proto.common.Response
}
var file_proto_service_auth_service_proto_depIdxs = []int32{
	15, // 0: com.bdsw.proto.service.PasswordLoginRequest.device_info:type_name -> com.bdsw.proto.common.DeviceInfo
	15, // 1: com.bdsw.proto.service.TokenLoginRequest.device_info:type_name -> com.bdsw.proto.common.DeviceInfo
	16, // 2: com.bdsw.proto.service.LoginResponse.user:type_name -> com.bdsw.proto.common.User
	14, // 3: com.bdsw.proto.service.LoginResponse.auth_token:type_name -> com.bdsw.proto.service.AuthToken
	15, // 4: com.bdsw.proto.service.LoginResponse.device_info:type_name -> com.bdsw.proto.common.DeviceInfo
	15, // 5: com.bdsw.proto.service.LoginResponse.other_devices:type_name -> com.bdsw.proto.common.DeviceInfo
	14, // 6: com.bdsw.proto.service.TokenResponse.auth_token:type_name -> com.bdsw.proto.service.AuthToken
	15, // 7: com.bdsw.proto.service.UserDevicesResponse.devices:type_name -> com.bdsw.proto.common.DeviceInfo
	0,  // 8: com.bdsw.proto.service.AuthService.loginByPassword:input_type -> com.bdsw.proto.service.PasswordLoginRequest
	1,  // 9: com.bdsw.proto.service.AuthService.loginByToken:input_type -> com.bdsw.proto.service.TokenLoginRequest
	2,  // 10: com.bdsw.proto.service.AuthService.generateLoginQRCode:input_type -> com.bdsw.proto.service.GenerateQRCodeRequest
	4,  // 11: com.bdsw.proto.service.AuthService.confirmQRCodeLogin:input_type -> com.bdsw.proto.service.ConfirmQRCodeRequest
	6,  // 12: com.bdsw.proto.service.AuthService.logout:input_type -> com.bdsw.proto.service.LogoutRequest
	7,  // 13: com.bdsw.proto.service.AuthService.refreshToken:input_type -> com.bdsw.proto.service.RefreshTokenRequest
	9,  // 14: com.bdsw.proto.service.AuthService.verifyToken:input_type -> com.bdsw.proto.service.VerifyTokenRequest
	11, // 15: com.bdsw.proto.service.AuthService.forceLogout:input_type -> com.bdsw.proto.service.ForceLogoutRequest
	12, // 16: com.bdsw.proto.service.AuthService.getUserDevices:input_type -> com.bdsw.proto.service.UserDevicesRequest
	5,  // 17: com.bdsw.proto.service.AuthService.loginByPassword:output_type -> com.bdsw.proto.service.LoginResponse
	5,  // 18: com.bdsw.proto.service.AuthService.loginByToken:output_type -> com.bdsw.proto.service.LoginResponse
	3,  // 19: com.bdsw.proto.service.AuthService.generateLoginQRCode:output_type -> com.bdsw.proto.service.QRCodeResponse
	5,  // 20: com.bdsw.proto.service.AuthService.confirmQRCodeLogin:output_type -> com.bdsw.proto.service.LoginResponse
	17, // 21: com.bdsw.proto.service.AuthService.logout:output_type -> com.bdsw.proto.common.Response
	8,  // 22: com.bdsw.proto.service.AuthService.refreshToken:output_type -> com.bdsw.proto.service.TokenResponse
	10, // 23: com.bdsw.proto.service.AuthService.verifyToken:output_type -> com.bdsw.proto.service.VerifyTokenResponse
	17, // 24: com.bdsw.proto.service.AuthService.forceLogout:output_type -> com.bdsw.proto.common.Response
	13, // 25: com.bdsw.proto.service.AuthService.getUserDevices:output_type -> com.bdsw.proto.service.UserDevicesResponse
	17, // [17:26] is the sub-list for method output_type
	8,  // [8:17] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_proto_service_auth_service_proto_init() }
func file_proto_service_auth_service_proto_init() {
	if File_proto_service_auth_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_service_auth_service_proto_rawDesc), len(file_proto_service_auth_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_service_auth_service_proto_goTypes,
		DependencyIndexes: file_proto_service_auth_service_proto_depIdxs,
		MessageInfos:      file_proto_service_auth_service_proto_msgTypes,
	}.Build()
	File_proto_service_auth_service_proto = out.File
	file_proto_service_auth_service_proto_goTypes = nil
	file_proto_service_auth_service_proto_depIdxs = nil
}
