// Code generated by protoc-gen-go-triple. DO NOT EDIT.
// versions:
// - protoc-gen-go-triple v1.0.8
// - protoc             v6.32.1
// source: proto/service/auth_service.proto

package service

import (
	context "context"
	protocol "dubbo.apache.org/dubbo-go/v3/protocol"
	dubbo3 "dubbo.apache.org/dubbo-go/v3/protocol/dubbo3"
	invocation "dubbo.apache.org/dubbo-go/v3/protocol/invocation"
	common1 "github.com/bdsw/bdsw-im-ws/proto/common"
	grpc_go "github.com/dubbogo/grpc-go"
	codes "github.com/dubbogo/grpc-go/codes"
	metadata "github.com/dubbogo/grpc-go/metadata"
	status "github.com/dubbogo/grpc-go/status"
	common "github.com/dubbogo/triple/pkg/common"
	constant "github.com/dubbogo/triple/pkg/common/constant"
	triple "github.com/dubbogo/triple/pkg/triple"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc_go.SupportPackageIsVersion7

// AuthServiceClient is the client API for AuthService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AuthServiceClient interface {
	// 密码登录
	LoginByPassword(ctx context.Context, in *PasswordLoginRequest, opts ...grpc_go.CallOption) (*LoginResponse, common.ErrorWithAttachment)
	// Token登录/验证
	LoginByToken(ctx context.Context, in *TokenLoginRequest, opts ...grpc_go.CallOption) (*LoginResponse, common.ErrorWithAttachment)
	// 二维码登录（生成二维码）
	GenerateLoginQRCode(ctx context.Context, in *GenerateQRCodeRequest, opts ...grpc_go.CallOption) (*QRCodeResponse, common.ErrorWithAttachment)
	// 二维码登录（扫码确认）
	ConfirmQRCodeLogin(ctx context.Context, in *ConfirmQRCodeRequest, opts ...grpc_go.CallOption) (*LoginResponse, common.ErrorWithAttachment)
	// 登出
	Logout(ctx context.Context, in *LogoutRequest, opts ...grpc_go.CallOption) (*common1.Response, common.ErrorWithAttachment)
	// 刷新Token
	RefreshToken(ctx context.Context, in *RefreshTokenRequest, opts ...grpc_go.CallOption) (*TokenResponse, common.ErrorWithAttachment)
	// 验证Token
	VerifyToken(ctx context.Context, in *VerifyTokenRequest, opts ...grpc_go.CallOption) (*VerifyTokenResponse, common.ErrorWithAttachment)
	// 强制下线（多设备管理）
	ForceLogout(ctx context.Context, in *ForceLogoutRequest, opts ...grpc_go.CallOption) (*common1.Response, common.ErrorWithAttachment)
	// 获取用户设备列表
	GetUserDevices(ctx context.Context, in *UserDevicesRequest, opts ...grpc_go.CallOption) (*UserDevicesResponse, common.ErrorWithAttachment)
}

type authServiceClient struct {
	cc *triple.TripleConn
}

type AuthServiceClientImpl struct {
	LoginByPassword     func(ctx context.Context, in *PasswordLoginRequest) (*LoginResponse, error)
	LoginByToken        func(ctx context.Context, in *TokenLoginRequest) (*LoginResponse, error)
	GenerateLoginQRCode func(ctx context.Context, in *GenerateQRCodeRequest) (*QRCodeResponse, error)
	ConfirmQRCodeLogin  func(ctx context.Context, in *ConfirmQRCodeRequest) (*LoginResponse, error)
	Logout              func(ctx context.Context, in *LogoutRequest) (*common1.Response, error)
	RefreshToken        func(ctx context.Context, in *RefreshTokenRequest) (*TokenResponse, error)
	VerifyToken         func(ctx context.Context, in *VerifyTokenRequest) (*VerifyTokenResponse, error)
	ForceLogout         func(ctx context.Context, in *ForceLogoutRequest) (*common1.Response, error)
	GetUserDevices      func(ctx context.Context, in *UserDevicesRequest) (*UserDevicesResponse, error)
}

func (c *AuthServiceClientImpl) GetDubboStub(cc *triple.TripleConn) AuthServiceClient {
	return NewAuthServiceClient(cc)
}

func (c *AuthServiceClientImpl) XXX_InterfaceName() string {
	return "com.bdsw.proto.service.AuthService"
}

func NewAuthServiceClient(cc *triple.TripleConn) AuthServiceClient {
	return &authServiceClient{cc}
}

func (c *authServiceClient) LoginByPassword(ctx context.Context, in *PasswordLoginRequest, opts ...grpc_go.CallOption) (*LoginResponse, common.ErrorWithAttachment) {
	out := new(LoginResponse)
	interfaceKey := ctx.Value(constant.InterfaceKey).(string)
	return out, c.cc.Invoke(ctx, "/"+interfaceKey+"/LoginByPassword", in, out)
}

func (c *authServiceClient) LoginByToken(ctx context.Context, in *TokenLoginRequest, opts ...grpc_go.CallOption) (*LoginResponse, common.ErrorWithAttachment) {
	out := new(LoginResponse)
	interfaceKey := ctx.Value(constant.InterfaceKey).(string)
	return out, c.cc.Invoke(ctx, "/"+interfaceKey+"/LoginByToken", in, out)
}

func (c *authServiceClient) GenerateLoginQRCode(ctx context.Context, in *GenerateQRCodeRequest, opts ...grpc_go.CallOption) (*QRCodeResponse, common.ErrorWithAttachment) {
	out := new(QRCodeResponse)
	interfaceKey := ctx.Value(constant.InterfaceKey).(string)
	return out, c.cc.Invoke(ctx, "/"+interfaceKey+"/GenerateLoginQRCode", in, out)
}

func (c *authServiceClient) ConfirmQRCodeLogin(ctx context.Context, in *ConfirmQRCodeRequest, opts ...grpc_go.CallOption) (*LoginResponse, common.ErrorWithAttachment) {
	out := new(LoginResponse)
	interfaceKey := ctx.Value(constant.InterfaceKey).(string)
	return out, c.cc.Invoke(ctx, "/"+interfaceKey+"/ConfirmQRCodeLogin", in, out)
}

func (c *authServiceClient) Logout(ctx context.Context, in *LogoutRequest, opts ...grpc_go.CallOption) (*common1.Response, common.ErrorWithAttachment) {
	out := new(common1.Response)
	interfaceKey := ctx.Value(constant.InterfaceKey).(string)
	return out, c.cc.Invoke(ctx, "/"+interfaceKey+"/Logout", in, out)
}

func (c *authServiceClient) RefreshToken(ctx context.Context, in *RefreshTokenRequest, opts ...grpc_go.CallOption) (*TokenResponse, common.ErrorWithAttachment) {
	out := new(TokenResponse)
	interfaceKey := ctx.Value(constant.InterfaceKey).(string)
	return out, c.cc.Invoke(ctx, "/"+interfaceKey+"/RefreshToken", in, out)
}

func (c *authServiceClient) VerifyToken(ctx context.Context, in *VerifyTokenRequest, opts ...grpc_go.CallOption) (*VerifyTokenResponse, common.ErrorWithAttachment) {
	out := new(VerifyTokenResponse)
	interfaceKey := ctx.Value(constant.InterfaceKey).(string)
	return out, c.cc.Invoke(ctx, "/"+interfaceKey+"/VerifyToken", in, out)
}

func (c *authServiceClient) ForceLogout(ctx context.Context, in *ForceLogoutRequest, opts ...grpc_go.CallOption) (*common1.Response, common.ErrorWithAttachment) {
	out := new(common1.Response)
	interfaceKey := ctx.Value(constant.InterfaceKey).(string)
	return out, c.cc.Invoke(ctx, "/"+interfaceKey+"/ForceLogout", in, out)
}

func (c *authServiceClient) GetUserDevices(ctx context.Context, in *UserDevicesRequest, opts ...grpc_go.CallOption) (*UserDevicesResponse, common.ErrorWithAttachment) {
	out := new(UserDevicesResponse)
	interfaceKey := ctx.Value(constant.InterfaceKey).(string)
	return out, c.cc.Invoke(ctx, "/"+interfaceKey+"/GetUserDevices", in, out)
}

// AuthServiceServer is the server API for AuthService service.
// All implementations must embed UnimplementedAuthServiceServer
// for forward compatibility
type AuthServiceServer interface {
	// 密码登录
	LoginByPassword(context.Context, *PasswordLoginRequest) (*LoginResponse, error)
	// Token登录/验证
	LoginByToken(context.Context, *TokenLoginRequest) (*LoginResponse, error)
	// 二维码登录（生成二维码）
	GenerateLoginQRCode(context.Context, *GenerateQRCodeRequest) (*QRCodeResponse, error)
	// 二维码登录（扫码确认）
	ConfirmQRCodeLogin(context.Context, *ConfirmQRCodeRequest) (*LoginResponse, error)
	// 登出
	Logout(context.Context, *LogoutRequest) (*common1.Response, error)
	// 刷新Token
	RefreshToken(context.Context, *RefreshTokenRequest) (*TokenResponse, error)
	// 验证Token
	VerifyToken(context.Context, *VerifyTokenRequest) (*VerifyTokenResponse, error)
	// 强制下线（多设备管理）
	ForceLogout(context.Context, *ForceLogoutRequest) (*common1.Response, error)
	// 获取用户设备列表
	GetUserDevices(context.Context, *UserDevicesRequest) (*UserDevicesResponse, error)
	mustEmbedUnimplementedAuthServiceServer()
}

// UnimplementedAuthServiceServer must be embedded to have forward compatible implementations.
type UnimplementedAuthServiceServer struct {
	proxyImpl protocol.Invoker
}

func (UnimplementedAuthServiceServer) LoginByPassword(context.Context, *PasswordLoginRequest) (*LoginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoginByPassword not implemented")
}
func (UnimplementedAuthServiceServer) LoginByToken(context.Context, *TokenLoginRequest) (*LoginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoginByToken not implemented")
}
func (UnimplementedAuthServiceServer) GenerateLoginQRCode(context.Context, *GenerateQRCodeRequest) (*QRCodeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateLoginQRCode not implemented")
}
func (UnimplementedAuthServiceServer) ConfirmQRCodeLogin(context.Context, *ConfirmQRCodeRequest) (*LoginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ConfirmQRCodeLogin not implemented")
}
func (UnimplementedAuthServiceServer) Logout(context.Context, *LogoutRequest) (*common1.Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Logout not implemented")
}
func (UnimplementedAuthServiceServer) RefreshToken(context.Context, *RefreshTokenRequest) (*TokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RefreshToken not implemented")
}
func (UnimplementedAuthServiceServer) VerifyToken(context.Context, *VerifyTokenRequest) (*VerifyTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VerifyToken not implemented")
}
func (UnimplementedAuthServiceServer) ForceLogout(context.Context, *ForceLogoutRequest) (*common1.Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ForceLogout not implemented")
}
func (UnimplementedAuthServiceServer) GetUserDevices(context.Context, *UserDevicesRequest) (*UserDevicesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserDevices not implemented")
}
func (s *UnimplementedAuthServiceServer) XXX_SetProxyImpl(impl protocol.Invoker) {
	s.proxyImpl = impl
}

func (s *UnimplementedAuthServiceServer) XXX_GetProxyImpl() protocol.Invoker {
	return s.proxyImpl
}

func (s *UnimplementedAuthServiceServer) XXX_ServiceDesc() *grpc_go.ServiceDesc {
	return &AuthService_ServiceDesc
}
func (s *UnimplementedAuthServiceServer) XXX_InterfaceName() string {
	return "com.bdsw.proto.service.AuthService"
}

func (UnimplementedAuthServiceServer) mustEmbedUnimplementedAuthServiceServer() {}

// UnsafeAuthServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuthServiceServer will
// result in compilation errors.
type UnsafeAuthServiceServer interface {
	mustEmbedUnimplementedAuthServiceServer()
}

func RegisterAuthServiceServer(s grpc_go.ServiceRegistrar, srv AuthServiceServer) {
	s.RegisterService(&AuthService_ServiceDesc, srv)
}

func _AuthService_LoginByPassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc_go.UnaryServerInterceptor) (interface{}, error) {
	in := new(PasswordLoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	base := srv.(dubbo3.Dubbo3GrpcService)
	args := []interface{}{}
	args = append(args, in)
	md, _ := metadata.FromIncomingContext(ctx)
	invAttachment := make(map[string]interface{}, len(md))
	for k, v := range md {
		invAttachment[k] = v
	}
	invo := invocation.NewRPCInvocation("LoginByPassword", args, invAttachment)
	if interceptor == nil {
		result := base.XXX_GetProxyImpl().Invoke(ctx, invo)
		return result, result.Error()
	}
	info := &grpc_go.UnaryServerInfo{
		Server:     srv,
		FullMethod: ctx.Value("XXX_TRIPLE_GO_INTERFACE_NAME").(string),
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		result := base.XXX_GetProxyImpl().Invoke(ctx, invo)
		return result, result.Error()
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_LoginByToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc_go.UnaryServerInterceptor) (interface{}, error) {
	in := new(TokenLoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	base := srv.(dubbo3.Dubbo3GrpcService)
	args := []interface{}{}
	args = append(args, in)
	md, _ := metadata.FromIncomingContext(ctx)
	invAttachment := make(map[string]interface{}, len(md))
	for k, v := range md {
		invAttachment[k] = v
	}
	invo := invocation.NewRPCInvocation("LoginByToken", args, invAttachment)
	if interceptor == nil {
		result := base.XXX_GetProxyImpl().Invoke(ctx, invo)
		return result, result.Error()
	}
	info := &grpc_go.UnaryServerInfo{
		Server:     srv,
		FullMethod: ctx.Value("XXX_TRIPLE_GO_INTERFACE_NAME").(string),
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		result := base.XXX_GetProxyImpl().Invoke(ctx, invo)
		return result, result.Error()
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_GenerateLoginQRCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc_go.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateQRCodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	base := srv.(dubbo3.Dubbo3GrpcService)
	args := []interface{}{}
	args = append(args, in)
	md, _ := metadata.FromIncomingContext(ctx)
	invAttachment := make(map[string]interface{}, len(md))
	for k, v := range md {
		invAttachment[k] = v
	}
	invo := invocation.NewRPCInvocation("GenerateLoginQRCode", args, invAttachment)
	if interceptor == nil {
		result := base.XXX_GetProxyImpl().Invoke(ctx, invo)
		return result, result.Error()
	}
	info := &grpc_go.UnaryServerInfo{
		Server:     srv,
		FullMethod: ctx.Value("XXX_TRIPLE_GO_INTERFACE_NAME").(string),
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		result := base.XXX_GetProxyImpl().Invoke(ctx, invo)
		return result, result.Error()
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_ConfirmQRCodeLogin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc_go.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfirmQRCodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	base := srv.(dubbo3.Dubbo3GrpcService)
	args := []interface{}{}
	args = append(args, in)
	md, _ := metadata.FromIncomingContext(ctx)
	invAttachment := make(map[string]interface{}, len(md))
	for k, v := range md {
		invAttachment[k] = v
	}
	invo := invocation.NewRPCInvocation("ConfirmQRCodeLogin", args, invAttachment)
	if interceptor == nil {
		result := base.XXX_GetProxyImpl().Invoke(ctx, invo)
		return result, result.Error()
	}
	info := &grpc_go.UnaryServerInfo{
		Server:     srv,
		FullMethod: ctx.Value("XXX_TRIPLE_GO_INTERFACE_NAME").(string),
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		result := base.XXX_GetProxyImpl().Invoke(ctx, invo)
		return result, result.Error()
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_Logout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc_go.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogoutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	base := srv.(dubbo3.Dubbo3GrpcService)
	args := []interface{}{}
	args = append(args, in)
	md, _ := metadata.FromIncomingContext(ctx)
	invAttachment := make(map[string]interface{}, len(md))
	for k, v := range md {
		invAttachment[k] = v
	}
	invo := invocation.NewRPCInvocation("Logout", args, invAttachment)
	if interceptor == nil {
		result := base.XXX_GetProxyImpl().Invoke(ctx, invo)
		return result, result.Error()
	}
	info := &grpc_go.UnaryServerInfo{
		Server:     srv,
		FullMethod: ctx.Value("XXX_TRIPLE_GO_INTERFACE_NAME").(string),
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		result := base.XXX_GetProxyImpl().Invoke(ctx, invo)
		return result, result.Error()
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_RefreshToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc_go.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefreshTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	base := srv.(dubbo3.Dubbo3GrpcService)
	args := []interface{}{}
	args = append(args, in)
	md, _ := metadata.FromIncomingContext(ctx)
	invAttachment := make(map[string]interface{}, len(md))
	for k, v := range md {
		invAttachment[k] = v
	}
	invo := invocation.NewRPCInvocation("RefreshToken", args, invAttachment)
	if interceptor == nil {
		result := base.XXX_GetProxyImpl().Invoke(ctx, invo)
		return result, result.Error()
	}
	info := &grpc_go.UnaryServerInfo{
		Server:     srv,
		FullMethod: ctx.Value("XXX_TRIPLE_GO_INTERFACE_NAME").(string),
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		result := base.XXX_GetProxyImpl().Invoke(ctx, invo)
		return result, result.Error()
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_VerifyToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc_go.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	base := srv.(dubbo3.Dubbo3GrpcService)
	args := []interface{}{}
	args = append(args, in)
	md, _ := metadata.FromIncomingContext(ctx)
	invAttachment := make(map[string]interface{}, len(md))
	for k, v := range md {
		invAttachment[k] = v
	}
	invo := invocation.NewRPCInvocation("VerifyToken", args, invAttachment)
	if interceptor == nil {
		result := base.XXX_GetProxyImpl().Invoke(ctx, invo)
		return result, result.Error()
	}
	info := &grpc_go.UnaryServerInfo{
		Server:     srv,
		FullMethod: ctx.Value("XXX_TRIPLE_GO_INTERFACE_NAME").(string),
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		result := base.XXX_GetProxyImpl().Invoke(ctx, invo)
		return result, result.Error()
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_ForceLogout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc_go.UnaryServerInterceptor) (interface{}, error) {
	in := new(ForceLogoutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	base := srv.(dubbo3.Dubbo3GrpcService)
	args := []interface{}{}
	args = append(args, in)
	md, _ := metadata.FromIncomingContext(ctx)
	invAttachment := make(map[string]interface{}, len(md))
	for k, v := range md {
		invAttachment[k] = v
	}
	invo := invocation.NewRPCInvocation("ForceLogout", args, invAttachment)
	if interceptor == nil {
		result := base.XXX_GetProxyImpl().Invoke(ctx, invo)
		return result, result.Error()
	}
	info := &grpc_go.UnaryServerInfo{
		Server:     srv,
		FullMethod: ctx.Value("XXX_TRIPLE_GO_INTERFACE_NAME").(string),
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		result := base.XXX_GetProxyImpl().Invoke(ctx, invo)
		return result, result.Error()
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_GetUserDevices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc_go.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserDevicesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	base := srv.(dubbo3.Dubbo3GrpcService)
	args := []interface{}{}
	args = append(args, in)
	md, _ := metadata.FromIncomingContext(ctx)
	invAttachment := make(map[string]interface{}, len(md))
	for k, v := range md {
		invAttachment[k] = v
	}
	invo := invocation.NewRPCInvocation("GetUserDevices", args, invAttachment)
	if interceptor == nil {
		result := base.XXX_GetProxyImpl().Invoke(ctx, invo)
		return result, result.Error()
	}
	info := &grpc_go.UnaryServerInfo{
		Server:     srv,
		FullMethod: ctx.Value("XXX_TRIPLE_GO_INTERFACE_NAME").(string),
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		result := base.XXX_GetProxyImpl().Invoke(ctx, invo)
		return result, result.Error()
	}
	return interceptor(ctx, in, info, handler)
}

// AuthService_ServiceDesc is the grpc_go.ServiceDesc for AuthService service.
// It's only intended for direct use with grpc_go.RegisterService,
// and not to be introspected or modified (even as a copy)
var AuthService_ServiceDesc = grpc_go.ServiceDesc{
	ServiceName: "com.bdsw.proto.service.AuthService",
	HandlerType: (*AuthServiceServer)(nil),
	Methods: []grpc_go.MethodDesc{
		{
			MethodName: "loginByPassword",
			Handler:    _AuthService_LoginByPassword_Handler,
		},
		{
			MethodName: "loginByToken",
			Handler:    _AuthService_LoginByToken_Handler,
		},
		{
			MethodName: "generateLoginQRCode",
			Handler:    _AuthService_GenerateLoginQRCode_Handler,
		},
		{
			MethodName: "confirmQRCodeLogin",
			Handler:    _AuthService_ConfirmQRCodeLogin_Handler,
		},
		{
			MethodName: "logout",
			Handler:    _AuthService_Logout_Handler,
		},
		{
			MethodName: "refreshToken",
			Handler:    _AuthService_RefreshToken_Handler,
		},
		{
			MethodName: "verifyToken",
			Handler:    _AuthService_VerifyToken_Handler,
		},
		{
			MethodName: "forceLogout",
			Handler:    _AuthService_ForceLogout_Handler,
		},
		{
			MethodName: "getUserDevices",
			Handler:    _AuthService_GetUserDevices_Handler,
		},
	},
	Streams:  []grpc_go.StreamDesc{},
	Metadata: "proto/service/auth_service.proto",
}
