// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: proto/service/gateway_service.proto

// Java 包的命名空间

package service

import (
	common "github.com/bdsw/bdsw-im-ws/proto/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ClientMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       []byte                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientMessageRequest) Reset() {
	*x = ClientMessageRequest{}
	mi := &file_proto_service_gateway_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientMessageRequest) ProtoMessage() {}

func (x *ClientMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_gateway_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientMessageRequest.ProtoReflect.Descriptor instead.
func (*ClientMessageRequest) Descriptor() ([]byte, []int) {
	return file_proto_service_gateway_service_proto_rawDescGZIP(), []int{0}
}

func (x *ClientMessageRequest) GetMessage() []byte {
	if x != nil {
		return x.Message
	}
	return nil
}

type ClientMessageResponse struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	MsgId         string                       `protobuf:"bytes,1,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
	ServerTime    int64                        `protobuf:"varint,2,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"`
	Status        common.Message_MessageStatus `protobuf:"varint,3,opt,name=status,proto3,enum=com.bdsw.proto.common.Message_MessageStatus" json:"status,omitempty"`
	ErrorMsg      string                       `protobuf:"bytes,4,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"` // 错误信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientMessageResponse) Reset() {
	*x = ClientMessageResponse{}
	mi := &file_proto_service_gateway_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientMessageResponse) ProtoMessage() {}

func (x *ClientMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_gateway_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientMessageResponse.ProtoReflect.Descriptor instead.
func (*ClientMessageResponse) Descriptor() ([]byte, []int) {
	return file_proto_service_gateway_service_proto_rawDescGZIP(), []int{1}
}

func (x *ClientMessageResponse) GetMsgId() string {
	if x != nil {
		return x.MsgId
	}
	return ""
}

func (x *ClientMessageResponse) GetServerTime() int64 {
	if x != nil {
		return x.ServerTime
	}
	return 0
}

func (x *ClientMessageResponse) GetStatus() common.Message_MessageStatus {
	if x != nil {
		return x.Status
	}
	return common.Message_MessageStatus(0)
}

func (x *ClientMessageResponse) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

type FetchMessagesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DeviceId      string                 `protobuf:"bytes,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	LastSeq       int64                  `protobuf:"varint,3,opt,name=last_seq,json=lastSeq,proto3" json:"last_seq,omitempty"`       // 客户端已处理的最大消息序列号
	BatchSize     int32                  `protobuf:"varint,4,opt,name=batch_size,json=batchSize,proto3" json:"batch_size,omitempty"` // 批量大小
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchMessagesRequest) Reset() {
	*x = FetchMessagesRequest{}
	mi := &file_proto_service_gateway_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchMessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchMessagesRequest) ProtoMessage() {}

func (x *FetchMessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_gateway_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchMessagesRequest.ProtoReflect.Descriptor instead.
func (*FetchMessagesRequest) Descriptor() ([]byte, []int) {
	return file_proto_service_gateway_service_proto_rawDescGZIP(), []int{2}
}

func (x *FetchMessagesRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *FetchMessagesRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *FetchMessagesRequest) GetLastSeq() int64 {
	if x != nil {
		return x.LastSeq
	}
	return 0
}

func (x *FetchMessagesRequest) GetBatchSize() int32 {
	if x != nil {
		return x.BatchSize
	}
	return 0
}

type DeliveredNotification struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DeviceId      string                 `protobuf:"bytes,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	MsgIds        []string               `protobuf:"bytes,3,rep,name=msg_ids,json=msgIds,proto3" json:"msg_ids,omitempty"` // 已送达的消息ID列表
	DeliverTime   int64                  `protobuf:"varint,4,opt,name=deliver_time,json=deliverTime,proto3" json:"deliver_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeliveredNotification) Reset() {
	*x = DeliveredNotification{}
	mi := &file_proto_service_gateway_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeliveredNotification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliveredNotification) ProtoMessage() {}

func (x *DeliveredNotification) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_gateway_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliveredNotification.ProtoReflect.Descriptor instead.
func (*DeliveredNotification) Descriptor() ([]byte, []int) {
	return file_proto_service_gateway_service_proto_rawDescGZIP(), []int{3}
}

func (x *DeliveredNotification) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *DeliveredNotification) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *DeliveredNotification) GetMsgIds() []string {
	if x != nil {
		return x.MsgIds
	}
	return nil
}

func (x *DeliveredNotification) GetDeliverTime() int64 {
	if x != nil {
		return x.DeliverTime
	}
	return 0
}

type ReadNotification struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DeviceId       string                 `protobuf:"bytes,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	ConversationId string                 `protobuf:"bytes,3,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	ReadSeq        int64                  `protobuf:"varint,4,opt,name=read_seq,json=readSeq,proto3" json:"read_seq,omitempty"` // 已读到的消息序列号
	ReadTime       int64                  `protobuf:"varint,5,opt,name=read_time,json=readTime,proto3" json:"read_time,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ReadNotification) Reset() {
	*x = ReadNotification{}
	mi := &file_proto_service_gateway_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadNotification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadNotification) ProtoMessage() {}

func (x *ReadNotification) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_gateway_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadNotification.ProtoReflect.Descriptor instead.
func (*ReadNotification) Descriptor() ([]byte, []int) {
	return file_proto_service_gateway_service_proto_rawDescGZIP(), []int{4}
}

func (x *ReadNotification) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ReadNotification) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *ReadNotification) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *ReadNotification) GetReadSeq() int64 {
	if x != nil {
		return x.ReadSeq
	}
	return 0
}

func (x *ReadNotification) GetReadTime() int64 {
	if x != nil {
		return x.ReadTime
	}
	return 0
}

type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DeviceId      string                 `protobuf:"bytes,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	ClientTime    int64                  `protobuf:"varint,3,opt,name=client_time,json=clientTime,proto3" json:"client_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_proto_service_gateway_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_gateway_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_proto_service_gateway_service_proto_rawDescGZIP(), []int{5}
}

func (x *HeartbeatRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *HeartbeatRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *HeartbeatRequest) GetClientTime() int64 {
	if x != nil {
		return x.ClientTime
	}
	return 0
}

type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerTime    int64                  `protobuf:"varint,1,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"`
	NeedSync      bool                   `protobuf:"varint,2,opt,name=need_sync,json=needSync,proto3" json:"need_sync,omitempty"` // 是否需要同步消息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_proto_service_gateway_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_gateway_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_proto_service_gateway_service_proto_rawDescGZIP(), []int{6}
}

func (x *HeartbeatResponse) GetServerTime() int64 {
	if x != nil {
		return x.ServerTime
	}
	return 0
}

func (x *HeartbeatResponse) GetNeedSync() bool {
	if x != nil {
		return x.NeedSync
	}
	return false
}

type DisconnectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DeviceId      string                 `protobuf:"bytes,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Reason        int32                  `protobuf:"varint,3,opt,name=reason,proto3" json:"reason,omitempty"` // 断开原因: 0:正常退出 1:网络异常 2:被踢下线
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisconnectRequest) Reset() {
	*x = DisconnectRequest{}
	mi := &file_proto_service_gateway_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisconnectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisconnectRequest) ProtoMessage() {}

func (x *DisconnectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_gateway_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisconnectRequest.ProtoReflect.Descriptor instead.
func (*DisconnectRequest) Descriptor() ([]byte, []int) {
	return file_proto_service_gateway_service_proto_rawDescGZIP(), []int{7}
}

func (x *DisconnectRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *DisconnectRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *DisconnectRequest) GetReason() int32 {
	if x != nil {
		return x.Reason
	}
	return 0
}

var File_proto_service_gateway_service_proto protoreflect.FileDescriptor

const file_proto_service_gateway_service_proto_rawDesc = "" +
	"\n" +
	"#proto/service/gateway_service.proto\x12\x16com.bdsw.proto.service\x1a\x19proto/common/common.proto\x1a\x1aproto/common/message.proto\"0\n" +
	"\x14ClientMessageRequest\x12\x18\n" +
	"\amessage\x18\x01 \x01(\fR\amessage\"\xb2\x01\n" +
	"\x15ClientMessageResponse\x12\x15\n" +
	"\x06msg_id\x18\x01 \x01(\tR\x05msgId\x12\x1f\n" +
	"\vserver_time\x18\x02 \x01(\x03R\n" +
	"serverTime\x12D\n" +
	"\x06status\x18\x03 \x01(\x0e2,.com.bdsw.proto.common.Message.MessageStatusR\x06status\x12\x1b\n" +
	"\terror_msg\x18\x04 \x01(\tR\berrorMsg\"\x86\x01\n" +
	"\x14FetchMessagesRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tdevice_id\x18\x02 \x01(\tR\bdeviceId\x12\x19\n" +
	"\blast_seq\x18\x03 \x01(\x03R\alastSeq\x12\x1d\n" +
	"\n" +
	"batch_size\x18\x04 \x01(\x05R\tbatchSize\"\x89\x01\n" +
	"\x15DeliveredNotification\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tdevice_id\x18\x02 \x01(\tR\bdeviceId\x12\x17\n" +
	"\amsg_ids\x18\x03 \x03(\tR\x06msgIds\x12!\n" +
	"\fdeliver_time\x18\x04 \x01(\x03R\vdeliverTime\"\xa9\x01\n" +
	"\x10ReadNotification\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tdevice_id\x18\x02 \x01(\tR\bdeviceId\x12'\n" +
	"\x0fconversation_id\x18\x03 \x01(\tR\x0econversationId\x12\x19\n" +
	"\bread_seq\x18\x04 \x01(\x03R\areadSeq\x12\x1b\n" +
	"\tread_time\x18\x05 \x01(\x03R\breadTime\"i\n" +
	"\x10HeartbeatRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tdevice_id\x18\x02 \x01(\tR\bdeviceId\x12\x1f\n" +
	"\vclient_time\x18\x03 \x01(\x03R\n" +
	"clientTime\"Q\n" +
	"\x11HeartbeatResponse\x12\x1f\n" +
	"\vserver_time\x18\x01 \x01(\x03R\n" +
	"serverTime\x12\x1b\n" +
	"\tneed_sync\x18\x02 \x01(\bR\bneedSync\"a\n" +
	"\x11DisconnectRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tdevice_id\x18\x02 \x01(\tR\bdeviceId\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\x05R\x06reason2\xf8\x04\n" +
	"\x0eGatewayService\x12r\n" +
	"\x13handleClientMessage\x12,.com.bdsw.proto.service.ClientMessageRequest\x1a-.com.bdsw.proto.service.ClientMessageResponse\x12f\n" +
	"\x14fetchPendingMessages\x12,.com.bdsw.proto.service.FetchMessagesRequest\x1a\x1e.com.bdsw.proto.common.Message0\x01\x12h\n" +
	"\x16notifyMessageDelivered\x12-.com.bdsw.proto.service.DeliveredNotification\x1a\x1f.com.bdsw.proto.common.Response\x12^\n" +
	"\x11notifyMessageRead\x12(.com.bdsw.proto.service.ReadNotification\x1a\x1f.com.bdsw.proto.common.Response\x12`\n" +
	"\theartbeat\x12(.com.bdsw.proto.service.HeartbeatRequest\x1a).com.bdsw.proto.service.HeartbeatResponse\x12^\n" +
	"\x10clientDisconnect\x12).com.bdsw.proto.service.DisconnectRequest\x1a\x1f.com.bdsw.proto.common.ResponseBa\n" +
	"\x16com.bdsw.proto.serviceB\x13GatewayServiceProtoP\x01Z0github.com/bdsw/bdsw-im-ws/proto/service;serviceb\x06proto3"

var (
	file_proto_service_gateway_service_proto_rawDescOnce sync.Once
	file_proto_service_gateway_service_proto_rawDescData []byte
)

func file_proto_service_gateway_service_proto_rawDescGZIP() []byte {
	file_proto_service_gateway_service_proto_rawDescOnce.Do(func() {
		file_proto_service_gateway_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_service_gateway_service_proto_rawDesc), len(file_proto_service_gateway_service_proto_rawDesc)))
	})
	return file_proto_service_gateway_service_proto_rawDescData
}

var file_proto_service_gateway_service_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_service_gateway_service_proto_goTypes = []any{
	(*ClientMessageRequest)(nil),      // 0: com.bdsw.proto.service.ClientMessageRequest
	(*ClientMessageResponse)(nil),     // 1: com.bdsw.proto.service.ClientMessageResponse
	(*FetchMessagesRequest)(nil),      // 2: com.bdsw.proto.service.FetchMessagesRequest
	(*DeliveredNotification)(nil),     // 3: com.bdsw.proto.service.DeliveredNotification
	(*ReadNotification)(nil),          // 4: com.bdsw.proto.service.ReadNotification
	(*HeartbeatRequest)(nil),          // 5: com.bdsw.proto.service.HeartbeatRequest
	(*HeartbeatResponse)(nil),         // 6: com.bdsw.proto.service.HeartbeatResponse
	(*DisconnectRequest)(nil),         // 7: com.bdsw.proto.service.DisconnectRequest
	(common.Message_MessageStatus)(0), // 8: com.bdsw.proto.common.Message.MessageStatus
	(*common.Message)(nil),            // 9: com.bdsw.proto.common.Message
	(*common.Response)(nil),           // 10: com.bdsw.proto.common.Response
}
var file_proto_service_gateway_service_proto_depIdxs = []int32{
	8,  // 0: com.bdsw.proto.service.ClientMessageResponse.status:type_name -> com.bdsw.proto.common.Message.MessageStatus
	0,  // 1: com.bdsw.proto.service.GatewayService.handleClientMessage:input_type -> com.bdsw.proto.service.ClientMessageRequest
	2,  // 2: com.bdsw.proto.service.GatewayService.fetchPendingMessages:input_type -> com.bdsw.proto.service.FetchMessagesRequest
	3,  // 3: com.bdsw.proto.service.GatewayService.notifyMessageDelivered:input_type -> com.bdsw.proto.service.DeliveredNotification
	4,  // 4: com.bdsw.proto.service.GatewayService.notifyMessageRead:input_type -> com.bdsw.proto.service.ReadNotification
	5,  // 5: com.bdsw.proto.service.GatewayService.heartbeat:input_type -> com.bdsw.proto.service.HeartbeatRequest
	7,  // 6: com.bdsw.proto.service.GatewayService.clientDisconnect:input_type -> com.bdsw.proto.service.DisconnectRequest
	1,  // 7: com.bdsw.proto.service.GatewayService.handleClientMessage:output_type -> com.bdsw.proto.service.ClientMessageResponse
	9,  // 8: com.bdsw.proto.service.GatewayService.fetchPendingMessages:output_type -> com.bdsw.proto.common.Message
	10, // 9: com.bdsw.proto.service.GatewayService.notifyMessageDelivered:output_type -> com.bdsw.proto.common.Response
	10, // 10: com.bdsw.proto.service.GatewayService.notifyMessageRead:output_type -> com.bdsw.proto.common.Response
	6,  // 11: com.bdsw.proto.service.GatewayService.heartbeat:output_type -> com.bdsw.proto.service.HeartbeatResponse
	10, // 12: com.bdsw.proto.service.GatewayService.clientDisconnect:output_type -> com.bdsw.proto.common.Response
	7,  // [7:13] is the sub-list for method output_type
	1,  // [1:7] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_proto_service_gateway_service_proto_init() }
func file_proto_service_gateway_service_proto_init() {
	if File_proto_service_gateway_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_service_gateway_service_proto_rawDesc), len(file_proto_service_gateway_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_service_gateway_service_proto_goTypes,
		DependencyIndexes: file_proto_service_gateway_service_proto_depIdxs,
		MessageInfos:      file_proto_service_gateway_service_proto_msgTypes,
	}.Build()
	File_proto_service_gateway_service_proto = out.File
	file_proto_service_gateway_service_proto_goTypes = nil
	file_proto_service_gateway_service_proto_depIdxs = nil
}
