// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: proto/service/group_service.proto

// Java 包的命名空间

package service

import (
	common "github.com/bdsw/bdsw-im-ws/proto/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateGroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CreatorId     string                 `protobuf:"bytes,1,opt,name=creator_id,json=creatorId,proto3" json:"creator_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	AvatarUrl     string                 `protobuf:"bytes,3,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	MemberIds     []string               `protobuf:"bytes,5,rep,name=member_ids,json=memberIds,proto3" json:"member_ids,omitempty"`
	Settings      map[string]string      `protobuf:"bytes,6,rep,name=settings,proto3" json:"settings,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 群设置
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateGroupRequest) Reset() {
	*x = CreateGroupRequest{}
	mi := &file_proto_service_group_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGroupRequest) ProtoMessage() {}

func (x *CreateGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_group_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGroupRequest.ProtoReflect.Descriptor instead.
func (*CreateGroupRequest) Descriptor() ([]byte, []int) {
	return file_proto_service_group_service_proto_rawDescGZIP(), []int{0}
}

func (x *CreateGroupRequest) GetCreatorId() string {
	if x != nil {
		return x.CreatorId
	}
	return ""
}

func (x *CreateGroupRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateGroupRequest) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

func (x *CreateGroupRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateGroupRequest) GetMemberIds() []string {
	if x != nil {
		return x.MemberIds
	}
	return nil
}

func (x *CreateGroupRequest) GetSettings() map[string]string {
	if x != nil {
		return x.Settings
	}
	return nil
}

type CreateGroupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Group         *common.Group          `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateGroupResponse) Reset() {
	*x = CreateGroupResponse{}
	mi := &file_proto_service_group_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGroupResponse) ProtoMessage() {}

func (x *CreateGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_group_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGroupResponse.ProtoReflect.Descriptor instead.
func (*CreateGroupResponse) Descriptor() ([]byte, []int) {
	return file_proto_service_group_service_proto_rawDescGZIP(), []int{1}
}

func (x *CreateGroupResponse) GetGroup() *common.Group {
	if x != nil {
		return x.Group
	}
	return nil
}

type GroupInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       string                 `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	WithMembers   bool                   `protobuf:"varint,2,opt,name=with_members,json=withMembers,proto3" json:"with_members,omitempty"` // 是否包含成员列表
	MemberLimit   int32                  `protobuf:"varint,3,opt,name=member_limit,json=memberLimit,proto3" json:"member_limit,omitempty"` // 成员数量限制
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupInfoRequest) Reset() {
	*x = GroupInfoRequest{}
	mi := &file_proto_service_group_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupInfoRequest) ProtoMessage() {}

func (x *GroupInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_group_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupInfoRequest.ProtoReflect.Descriptor instead.
func (*GroupInfoRequest) Descriptor() ([]byte, []int) {
	return file_proto_service_group_service_proto_rawDescGZIP(), []int{2}
}

func (x *GroupInfoRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *GroupInfoRequest) GetWithMembers() bool {
	if x != nil {
		return x.WithMembers
	}
	return false
}

func (x *GroupInfoRequest) GetMemberLimit() int32 {
	if x != nil {
		return x.MemberLimit
	}
	return 0
}

type UpdateGroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       string                 `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	OperatorId    string                 `protobuf:"bytes,2,opt,name=operator_id,json=operatorId,proto3" json:"operator_id,omitempty"`
	Updates       map[string]string      `protobuf:"bytes,3,rep,name=updates,proto3" json:"updates,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 更新的字段
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateGroupRequest) Reset() {
	*x = UpdateGroupRequest{}
	mi := &file_proto_service_group_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateGroupRequest) ProtoMessage() {}

func (x *UpdateGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_group_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateGroupRequest.ProtoReflect.Descriptor instead.
func (*UpdateGroupRequest) Descriptor() ([]byte, []int) {
	return file_proto_service_group_service_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateGroupRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *UpdateGroupRequest) GetOperatorId() string {
	if x != nil {
		return x.OperatorId
	}
	return ""
}

func (x *UpdateGroupRequest) GetUpdates() map[string]string {
	if x != nil {
		return x.Updates
	}
	return nil
}

type DismissGroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       string                 `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	OperatorId    string                 `protobuf:"bytes,2,opt,name=operator_id,json=operatorId,proto3" json:"operator_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DismissGroupRequest) Reset() {
	*x = DismissGroupRequest{}
	mi := &file_proto_service_group_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DismissGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DismissGroupRequest) ProtoMessage() {}

func (x *DismissGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_group_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DismissGroupRequest.ProtoReflect.Descriptor instead.
func (*DismissGroupRequest) Descriptor() ([]byte, []int) {
	return file_proto_service_group_service_proto_rawDescGZIP(), []int{4}
}

func (x *DismissGroupRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *DismissGroupRequest) GetOperatorId() string {
	if x != nil {
		return x.OperatorId
	}
	return ""
}

type GroupMembersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       string                 `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	Page          *common.PageRequest    `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	Keyword       string                 `protobuf:"bytes,3,opt,name=keyword,proto3" json:"keyword,omitempty"`     // 搜索关键词（昵称/备注）
	Roles         []int32                `protobuf:"varint,4,rep,packed,name=roles,proto3" json:"roles,omitempty"` // 筛选角色
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupMembersRequest) Reset() {
	*x = GroupMembersRequest{}
	mi := &file_proto_service_group_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupMembersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupMembersRequest) ProtoMessage() {}

func (x *GroupMembersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_group_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupMembersRequest.ProtoReflect.Descriptor instead.
func (*GroupMembersRequest) Descriptor() ([]byte, []int) {
	return file_proto_service_group_service_proto_rawDescGZIP(), []int{5}
}

func (x *GroupMembersRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *GroupMembersRequest) GetPage() *common.PageRequest {
	if x != nil {
		return x.Page
	}
	return nil
}

func (x *GroupMembersRequest) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *GroupMembersRequest) GetRoles() []int32 {
	if x != nil {
		return x.Roles
	}
	return nil
}

type GroupMembersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Members       []*common.GroupMember  `protobuf:"bytes,1,rep,name=members,proto3" json:"members,omitempty"`
	Page          *common.PageResponse   `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	Total         int32                  `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupMembersResponse) Reset() {
	*x = GroupMembersResponse{}
	mi := &file_proto_service_group_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupMembersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupMembersResponse) ProtoMessage() {}

func (x *GroupMembersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_group_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupMembersResponse.ProtoReflect.Descriptor instead.
func (*GroupMembersResponse) Descriptor() ([]byte, []int) {
	return file_proto_service_group_service_proto_rawDescGZIP(), []int{6}
}

func (x *GroupMembersResponse) GetMembers() []*common.GroupMember {
	if x != nil {
		return x.Members
	}
	return nil
}

func (x *GroupMembersResponse) GetPage() *common.PageResponse {
	if x != nil {
		return x.Page
	}
	return nil
}

func (x *GroupMembersResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type AddMembersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       string                 `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	OperatorId    string                 `protobuf:"bytes,2,opt,name=operator_id,json=operatorId,proto3" json:"operator_id,omitempty"`
	UserIds       []string               `protobuf:"bytes,3,rep,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"`
	Reason        string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	NeedApproval  bool                   `protobuf:"varint,5,opt,name=need_approval,json=needApproval,proto3" json:"need_approval,omitempty"` // 是否需要审批
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddMembersRequest) Reset() {
	*x = AddMembersRequest{}
	mi := &file_proto_service_group_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddMembersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddMembersRequest) ProtoMessage() {}

func (x *AddMembersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_group_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddMembersRequest.ProtoReflect.Descriptor instead.
func (*AddMembersRequest) Descriptor() ([]byte, []int) {
	return file_proto_service_group_service_proto_rawDescGZIP(), []int{7}
}

func (x *AddMembersRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *AddMembersRequest) GetOperatorId() string {
	if x != nil {
		return x.OperatorId
	}
	return ""
}

func (x *AddMembersRequest) GetUserIds() []string {
	if x != nil {
		return x.UserIds
	}
	return nil
}

func (x *AddMembersRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *AddMembersRequest) GetNeedApproval() bool {
	if x != nil {
		return x.NeedApproval
	}
	return false
}

type RemoveMembersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       string                 `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	OperatorId    string                 `protobuf:"bytes,2,opt,name=operator_id,json=operatorId,proto3" json:"operator_id,omitempty"`
	UserIds       []string               `protobuf:"bytes,3,rep,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"`
	Reason        string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveMembersRequest) Reset() {
	*x = RemoveMembersRequest{}
	mi := &file_proto_service_group_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveMembersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveMembersRequest) ProtoMessage() {}

func (x *RemoveMembersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_group_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveMembersRequest.ProtoReflect.Descriptor instead.
func (*RemoveMembersRequest) Descriptor() ([]byte, []int) {
	return file_proto_service_group_service_proto_rawDescGZIP(), []int{8}
}

func (x *RemoveMembersRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *RemoveMembersRequest) GetOperatorId() string {
	if x != nil {
		return x.OperatorId
	}
	return ""
}

func (x *RemoveMembersRequest) GetUserIds() []string {
	if x != nil {
		return x.UserIds
	}
	return nil
}

func (x *RemoveMembersRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type UpdateMemberRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       string                 `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	OperatorId    string                 `protobuf:"bytes,3,opt,name=operator_id,json=operatorId,proto3" json:"operator_id,omitempty"`
	Updates       map[string]string      `protobuf:"bytes,4,rep,name=updates,proto3" json:"updates,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMemberRequest) Reset() {
	*x = UpdateMemberRequest{}
	mi := &file_proto_service_group_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMemberRequest) ProtoMessage() {}

func (x *UpdateMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_group_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMemberRequest.ProtoReflect.Descriptor instead.
func (*UpdateMemberRequest) Descriptor() ([]byte, []int) {
	return file_proto_service_group_service_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateMemberRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *UpdateMemberRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateMemberRequest) GetOperatorId() string {
	if x != nil {
		return x.OperatorId
	}
	return ""
}

func (x *UpdateMemberRequest) GetUpdates() map[string]string {
	if x != nil {
		return x.Updates
	}
	return nil
}

type HandleApplyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApplyId       string                 `protobuf:"bytes,1,opt,name=apply_id,json=applyId,proto3" json:"apply_id,omitempty"`
	HandlerId     string                 `protobuf:"bytes,2,opt,name=handler_id,json=handlerId,proto3" json:"handler_id,omitempty"`
	Approve       bool                   `protobuf:"varint,3,opt,name=approve,proto3" json:"approve,omitempty"` // true:同意 false:拒绝
	Reason        string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandleApplyRequest) Reset() {
	*x = HandleApplyRequest{}
	mi := &file_proto_service_group_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandleApplyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandleApplyRequest) ProtoMessage() {}

func (x *HandleApplyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_group_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandleApplyRequest.ProtoReflect.Descriptor instead.
func (*HandleApplyRequest) Descriptor() ([]byte, []int) {
	return file_proto_service_group_service_proto_rawDescGZIP(), []int{10}
}

func (x *HandleApplyRequest) GetApplyId() string {
	if x != nil {
		return x.ApplyId
	}
	return ""
}

func (x *HandleApplyRequest) GetHandlerId() string {
	if x != nil {
		return x.HandlerId
	}
	return ""
}

func (x *HandleApplyRequest) GetApprove() bool {
	if x != nil {
		return x.Approve
	}
	return false
}

func (x *HandleApplyRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type GroupAppliesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       string                 `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	Status        int32                  `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"` // 申请状态
	Page          *common.PageRequest    `protobuf:"bytes,3,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupAppliesRequest) Reset() {
	*x = GroupAppliesRequest{}
	mi := &file_proto_service_group_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupAppliesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupAppliesRequest) ProtoMessage() {}

func (x *GroupAppliesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_group_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupAppliesRequest.ProtoReflect.Descriptor instead.
func (*GroupAppliesRequest) Descriptor() ([]byte, []int) {
	return file_proto_service_group_service_proto_rawDescGZIP(), []int{11}
}

func (x *GroupAppliesRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *GroupAppliesRequest) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *GroupAppliesRequest) GetPage() *common.PageRequest {
	if x != nil {
		return x.Page
	}
	return nil
}

type GroupAppliesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Applies       []*common.GroupApply   `protobuf:"bytes,1,rep,name=applies,proto3" json:"applies,omitempty"`
	Page          *common.PageResponse   `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupAppliesResponse) Reset() {
	*x = GroupAppliesResponse{}
	mi := &file_proto_service_group_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupAppliesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupAppliesResponse) ProtoMessage() {}

func (x *GroupAppliesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_group_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupAppliesResponse.ProtoReflect.Descriptor instead.
func (*GroupAppliesResponse) Descriptor() ([]byte, []int) {
	return file_proto_service_group_service_proto_rawDescGZIP(), []int{12}
}

func (x *GroupAppliesResponse) GetApplies() []*common.GroupApply {
	if x != nil {
		return x.Applies
	}
	return nil
}

func (x *GroupAppliesResponse) GetPage() *common.PageResponse {
	if x != nil {
		return x.Page
	}
	return nil
}

type SetAdminRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       string                 `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	OperatorId    string                 `protobuf:"bytes,2,opt,name=operator_id,json=operatorId,proto3" json:"operator_id,omitempty"`
	TargetUserId  string                 `protobuf:"bytes,3,opt,name=target_user_id,json=targetUserId,proto3" json:"target_user_id,omitempty"`
	SetAdmin      bool                   `protobuf:"varint,4,opt,name=set_admin,json=setAdmin,proto3" json:"set_admin,omitempty"` // true:设置管理员 false:取消管理员
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetAdminRequest) Reset() {
	*x = SetAdminRequest{}
	mi := &file_proto_service_group_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetAdminRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetAdminRequest) ProtoMessage() {}

func (x *SetAdminRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_group_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetAdminRequest.ProtoReflect.Descriptor instead.
func (*SetAdminRequest) Descriptor() ([]byte, []int) {
	return file_proto_service_group_service_proto_rawDescGZIP(), []int{13}
}

func (x *SetAdminRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *SetAdminRequest) GetOperatorId() string {
	if x != nil {
		return x.OperatorId
	}
	return ""
}

func (x *SetAdminRequest) GetTargetUserId() string {
	if x != nil {
		return x.TargetUserId
	}
	return ""
}

func (x *SetAdminRequest) GetSetAdmin() bool {
	if x != nil {
		return x.SetAdmin
	}
	return false
}

type MuteMemberRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       string                 `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	OperatorId    string                 `protobuf:"bytes,2,opt,name=operator_id,json=operatorId,proto3" json:"operator_id,omitempty"`
	TargetUserId  string                 `protobuf:"bytes,3,opt,name=target_user_id,json=targetUserId,proto3" json:"target_user_id,omitempty"`
	MuteDuration  int64                  `protobuf:"varint,4,opt,name=mute_duration,json=muteDuration,proto3" json:"mute_duration,omitempty"` // 禁言时长（秒），0表示解禁
	Reason        string                 `protobuf:"bytes,5,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MuteMemberRequest) Reset() {
	*x = MuteMemberRequest{}
	mi := &file_proto_service_group_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MuteMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MuteMemberRequest) ProtoMessage() {}

func (x *MuteMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_group_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MuteMemberRequest.ProtoReflect.Descriptor instead.
func (*MuteMemberRequest) Descriptor() ([]byte, []int) {
	return file_proto_service_group_service_proto_rawDescGZIP(), []int{14}
}

func (x *MuteMemberRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *MuteMemberRequest) GetOperatorId() string {
	if x != nil {
		return x.OperatorId
	}
	return ""
}

func (x *MuteMemberRequest) GetTargetUserId() string {
	if x != nil {
		return x.TargetUserId
	}
	return ""
}

func (x *MuteMemberRequest) GetMuteDuration() int64 {
	if x != nil {
		return x.MuteDuration
	}
	return 0
}

func (x *MuteMemberRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type MuteAllRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       string                 `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	OperatorId    string                 `protobuf:"bytes,2,opt,name=operator_id,json=operatorId,proto3" json:"operator_id,omitempty"`
	Mute          bool                   `protobuf:"varint,3,opt,name=mute,proto3" json:"mute,omitempty"` // true:禁言 false:解禁
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MuteAllRequest) Reset() {
	*x = MuteAllRequest{}
	mi := &file_proto_service_group_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MuteAllRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MuteAllRequest) ProtoMessage() {}

func (x *MuteAllRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_group_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MuteAllRequest.ProtoReflect.Descriptor instead.
func (*MuteAllRequest) Descriptor() ([]byte, []int) {
	return file_proto_service_group_service_proto_rawDescGZIP(), []int{15}
}

func (x *MuteAllRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *MuteAllRequest) GetOperatorId() string {
	if x != nil {
		return x.OperatorId
	}
	return ""
}

func (x *MuteAllRequest) GetMute() bool {
	if x != nil {
		return x.Mute
	}
	return false
}

type TransferOwnerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       string                 `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	OldOwnerId    string                 `protobuf:"bytes,2,opt,name=old_owner_id,json=oldOwnerId,proto3" json:"old_owner_id,omitempty"`
	NewOwnerId    string                 `protobuf:"bytes,3,opt,name=new_owner_id,json=newOwnerId,proto3" json:"new_owner_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferOwnerRequest) Reset() {
	*x = TransferOwnerRequest{}
	mi := &file_proto_service_group_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferOwnerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferOwnerRequest) ProtoMessage() {}

func (x *TransferOwnerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_group_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferOwnerRequest.ProtoReflect.Descriptor instead.
func (*TransferOwnerRequest) Descriptor() ([]byte, []int) {
	return file_proto_service_group_service_proto_rawDescGZIP(), []int{16}
}

func (x *TransferOwnerRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *TransferOwnerRequest) GetOldOwnerId() string {
	if x != nil {
		return x.OldOwnerId
	}
	return ""
}

func (x *TransferOwnerRequest) GetNewOwnerId() string {
	if x != nil {
		return x.NewOwnerId
	}
	return ""
}

var File_proto_service_group_service_proto protoreflect.FileDescriptor

const file_proto_service_group_service_proto_rawDesc = "" +
	"\n" +
	"!proto/service/group_service.proto\x12\x16com.bdsw.proto.service\x1a\x19proto/common/common.proto\x1a\x18proto/common/group.proto\"\xba\x02\n" +
	"\x12CreateGroupRequest\x12\x1d\n" +
	"\n" +
	"creator_id\x18\x01 \x01(\tR\tcreatorId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\x03 \x01(\tR\tavatarUrl\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"member_ids\x18\x05 \x03(\tR\tmemberIds\x12T\n" +
	"\bsettings\x18\x06 \x03(\v28.com.bdsw.proto.service.CreateGroupRequest.SettingsEntryR\bsettings\x1a;\n" +
	"\rSettingsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"I\n" +
	"\x13CreateGroupResponse\x122\n" +
	"\x05group\x18\x01 \x01(\v2\x1c.com.bdsw.proto.common.GroupR\x05group\"s\n" +
	"\x10GroupInfoRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\tR\agroupId\x12!\n" +
	"\fwith_members\x18\x02 \x01(\bR\vwithMembers\x12!\n" +
	"\fmember_limit\x18\x03 \x01(\x05R\vmemberLimit\"\xdf\x01\n" +
	"\x12UpdateGroupRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\tR\agroupId\x12\x1f\n" +
	"\voperator_id\x18\x02 \x01(\tR\n" +
	"operatorId\x12Q\n" +
	"\aupdates\x18\x03 \x03(\v27.com.bdsw.proto.service.UpdateGroupRequest.UpdatesEntryR\aupdates\x1a:\n" +
	"\fUpdatesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"Q\n" +
	"\x13DismissGroupRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\tR\agroupId\x12\x1f\n" +
	"\voperator_id\x18\x02 \x01(\tR\n" +
	"operatorId\"\x98\x01\n" +
	"\x13GroupMembersRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\tR\agroupId\x126\n" +
	"\x04page\x18\x02 \x01(\v2\".com.bdsw.proto.common.PageRequestR\x04page\x12\x18\n" +
	"\akeyword\x18\x03 \x01(\tR\akeyword\x12\x14\n" +
	"\x05roles\x18\x04 \x03(\x05R\x05roles\"\xa3\x01\n" +
	"\x14GroupMembersResponse\x12<\n" +
	"\amembers\x18\x01 \x03(\v2\".com.bdsw.proto.common.GroupMemberR\amembers\x127\n" +
	"\x04page\x18\x02 \x01(\v2#.com.bdsw.proto.common.PageResponseR\x04page\x12\x14\n" +
	"\x05total\x18\x03 \x01(\x05R\x05total\"\xa7\x01\n" +
	"\x11AddMembersRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\tR\agroupId\x12\x1f\n" +
	"\voperator_id\x18\x02 \x01(\tR\n" +
	"operatorId\x12\x19\n" +
	"\buser_ids\x18\x03 \x03(\tR\auserIds\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\x12#\n" +
	"\rneed_approval\x18\x05 \x01(\bR\fneedApproval\"\x85\x01\n" +
	"\x14RemoveMembersRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\tR\agroupId\x12\x1f\n" +
	"\voperator_id\x18\x02 \x01(\tR\n" +
	"operatorId\x12\x19\n" +
	"\buser_ids\x18\x03 \x03(\tR\auserIds\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\"\xfa\x01\n" +
	"\x13UpdateMemberRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\tR\agroupId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1f\n" +
	"\voperator_id\x18\x03 \x01(\tR\n" +
	"operatorId\x12R\n" +
	"\aupdates\x18\x04 \x03(\v28.com.bdsw.proto.service.UpdateMemberRequest.UpdatesEntryR\aupdates\x1a:\n" +
	"\fUpdatesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x80\x01\n" +
	"\x12HandleApplyRequest\x12\x19\n" +
	"\bapply_id\x18\x01 \x01(\tR\aapplyId\x12\x1d\n" +
	"\n" +
	"handler_id\x18\x02 \x01(\tR\thandlerId\x12\x18\n" +
	"\aapprove\x18\x03 \x01(\bR\aapprove\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\"\x80\x01\n" +
	"\x13GroupAppliesRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\tR\agroupId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\x05R\x06status\x126\n" +
	"\x04page\x18\x03 \x01(\v2\".com.bdsw.proto.common.PageRequestR\x04page\"\x8c\x01\n" +
	"\x14GroupAppliesResponse\x12;\n" +
	"\aapplies\x18\x01 \x03(\v2!.com.bdsw.proto.common.GroupApplyR\aapplies\x127\n" +
	"\x04page\x18\x02 \x01(\v2#.com.bdsw.proto.common.PageResponseR\x04page\"\x90\x01\n" +
	"\x0fSetAdminRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\tR\agroupId\x12\x1f\n" +
	"\voperator_id\x18\x02 \x01(\tR\n" +
	"operatorId\x12$\n" +
	"\x0etarget_user_id\x18\x03 \x01(\tR\ftargetUserId\x12\x1b\n" +
	"\tset_admin\x18\x04 \x01(\bR\bsetAdmin\"\xb2\x01\n" +
	"\x11MuteMemberRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\tR\agroupId\x12\x1f\n" +
	"\voperator_id\x18\x02 \x01(\tR\n" +
	"operatorId\x12$\n" +
	"\x0etarget_user_id\x18\x03 \x01(\tR\ftargetUserId\x12#\n" +
	"\rmute_duration\x18\x04 \x01(\x03R\fmuteDuration\x12\x16\n" +
	"\x06reason\x18\x05 \x01(\tR\x06reason\"`\n" +
	"\x0eMuteAllRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\tR\agroupId\x12\x1f\n" +
	"\voperator_id\x18\x02 \x01(\tR\n" +
	"operatorId\x12\x12\n" +
	"\x04mute\x18\x03 \x01(\bR\x04mute\"u\n" +
	"\x14TransferOwnerRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\tR\agroupId\x12 \n" +
	"\fold_owner_id\x18\x02 \x01(\tR\n" +
	"oldOwnerId\x12 \n" +
	"\fnew_owner_id\x18\x03 \x01(\tR\n" +
	"newOwnerId2\xea\n" +
	"\n" +
	"\fGroupService\x12f\n" +
	"\vcreateGroup\x12*.com.bdsw.proto.service.CreateGroupRequest\x1a+.com.bdsw.proto.service.CreateGroupResponse\x12V\n" +
	"\fgetGroupInfo\x12(.com.bdsw.proto.service.GroupInfoRequest\x1a\x1c.com.bdsw.proto.common.Group\x12^\n" +
	"\x0fupdateGroupInfo\x12*.com.bdsw.proto.service.UpdateGroupRequest\x1a\x1f.com.bdsw.proto.common.Response\x12\\\n" +
	"\fdismissGroup\x12+.com.bdsw.proto.service.DismissGroupRequest\x1a\x1f.com.bdsw.proto.common.Response\x12l\n" +
	"\x0fgetGroupMembers\x12+.com.bdsw.proto.service.GroupMembersRequest\x1a,.com.bdsw.proto.service.GroupMembersResponse\x12]\n" +
	"\x0faddGroupMembers\x12).com.bdsw.proto.service.AddMembersRequest\x1a\x1f.com.bdsw.proto.common.Response\x12c\n" +
	"\x12removeGroupMembers\x12,.com.bdsw.proto.service.RemoveMembersRequest\x1a\x1f.com.bdsw.proto.common.Response\x12a\n" +
	"\x11updateGroupMember\x12+.com.bdsw.proto.service.UpdateMemberRequest\x1a\x1f.com.bdsw.proto.common.Response\x12_\n" +
	"\x10handleGroupApply\x12*.com.bdsw.proto.service.HandleApplyRequest\x1a\x1f.com.bdsw.proto.common.Response\x12l\n" +
	"\x0fgetGroupApplies\x12+.com.bdsw.proto.service.GroupAppliesRequest\x1a,.com.bdsw.proto.service.GroupAppliesResponse\x12Y\n" +
	"\rsetGroupAdmin\x12'.com.bdsw.proto.service.SetAdminRequest\x1a\x1f.com.bdsw.proto.common.Response\x12]\n" +
	"\x0fmuteGroupMember\x12).com.bdsw.proto.service.MuteMemberRequest\x1a\x1f.com.bdsw.proto.common.Response\x12Y\n" +
	"\x0emuteAllMembers\x12&.com.bdsw.proto.service.MuteAllRequest\x1a\x1f.com.bdsw.proto.common.Response\x12c\n" +
	"\x12transferGroupOwner\x12,.com.bdsw.proto.service.TransferOwnerRequest\x1a\x1f.com.bdsw.proto.common.ResponseB_\n" +
	"\x16com.bdsw.proto.serviceB\x11GroupServiceProtoP\x01Z0github.com/bdsw/bdsw-im-ws/proto/service;serviceb\x06proto3"

var (
	file_proto_service_group_service_proto_rawDescOnce sync.Once
	file_proto_service_group_service_proto_rawDescData []byte
)

func file_proto_service_group_service_proto_rawDescGZIP() []byte {
	file_proto_service_group_service_proto_rawDescOnce.Do(func() {
		file_proto_service_group_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_service_group_service_proto_rawDesc), len(file_proto_service_group_service_proto_rawDesc)))
	})
	return file_proto_service_group_service_proto_rawDescData
}

var file_proto_service_group_service_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_proto_service_group_service_proto_goTypes = []any{
	(*CreateGroupRequest)(nil),   // 0: com.bdsw.proto.service.CreateGroupRequest
	(*CreateGroupResponse)(nil),  // 1: com.bdsw.proto.service.CreateGroupResponse
	(*GroupInfoRequest)(nil),     // 2: com.bdsw.proto.service.GroupInfoRequest
	(*UpdateGroupRequest)(nil),   // 3: com.bdsw.proto.service.UpdateGroupRequest
	(*DismissGroupRequest)(nil),  // 4: com.bdsw.proto.service.DismissGroupRequest
	(*GroupMembersRequest)(nil),  // 5: com.bdsw.proto.service.GroupMembersRequest
	(*GroupMembersResponse)(nil), // 6: com.bdsw.proto.service.GroupMembersResponse
	(*AddMembersRequest)(nil),    // 7: com.bdsw.proto.service.AddMembersRequest
	(*RemoveMembersRequest)(nil), // 8: com.bdsw.proto.service.RemoveMembersRequest
	(*UpdateMemberRequest)(nil),  // 9: com.bdsw.proto.service.UpdateMemberRequest
	(*HandleApplyRequest)(nil),   // 10: com.bdsw.proto.service.HandleApplyRequest
	(*GroupAppliesRequest)(nil),  // 11: com.bdsw.proto.service.GroupAppliesRequest
	(*GroupAppliesResponse)(nil), // 12: com.bdsw.proto.service.GroupAppliesResponse
	(*SetAdminRequest)(nil),      // 13: com.bdsw.proto.service.SetAdminRequest
	(*MuteMemberRequest)(nil),    // 14: com.bdsw.proto.service.MuteMemberRequest
	(*MuteAllRequest)(nil),       // 15: com.bdsw.proto.service.MuteAllRequest
	(*TransferOwnerRequest)(nil), // 16: com.bdsw.proto.service.TransferOwnerRequest
	nil,                          // 17: com.bdsw.proto.service.CreateGroupRequest.SettingsEntry
	nil,                          // 18: com.bdsw.proto.service.UpdateGroupRequest.UpdatesEntry
	nil,                          // 19: com.bdsw.proto.service.UpdateMemberRequest.UpdatesEntry
	(*common.Group)(nil),         // 20: com.bdsw.proto.common.Group
	(*common.PageRequest)(nil),   // 21: com.bdsw.proto.common.PageRequest
	(*common.GroupMember)(nil),   // 22: com.bdsw.proto.common.GroupMember
	(*common.PageResponse)(nil),  // 23: com.bdsw.proto.common.PageResponse
	(*common.GroupApply)(nil),    // 24: com.bdsw.proto.common.GroupApply
	(*common.Response)(nil),      // 25: com.bdsw.proto.common.Response
}
var file_proto_service_group_service_proto_depIdxs = []int32{
	17, // 0: com.bdsw.proto.service.CreateGroupRequest.settings:type_name -> com.bdsw.proto.service.CreateGroupRequest.SettingsEntry
	20, // 1: com.bdsw.proto.service.CreateGroupResponse.group:type_name -> com.bdsw.proto.common.Group
	18, // 2: com.bdsw.proto.service.UpdateGroupRequest.updates:type_name -> com.bdsw.proto.service.UpdateGroupRequest.UpdatesEntry
	21, // 3: com.bdsw.proto.service.GroupMembersRequest.page:type_name -> com.bdsw.proto.common.PageRequest
	22, // 4: com.bdsw.proto.service.GroupMembersResponse.members:type_name -> com.bdsw.proto.common.GroupMember
	23, // 5: com.bdsw.proto.service.GroupMembersResponse.page:type_name -> com.bdsw.proto.common.PageResponse
	19, // 6: com.bdsw.proto.service.UpdateMemberRequest.updates:type_name -> com.bdsw.proto.service.UpdateMemberRequest.UpdatesEntry
	21, // 7: com.bdsw.proto.service.GroupAppliesRequest.page:type_name -> com.bdsw.proto.common.PageRequest
	24, // 8: com.bdsw.proto.service.GroupAppliesResponse.applies:type_name -> com.bdsw.proto.common.GroupApply
	23, // 9: com.bdsw.proto.service.GroupAppliesResponse.page:type_name -> com.bdsw.proto.common.PageResponse
	0,  // 10: com.bdsw.proto.service.GroupService.createGroup:input_type -> com.bdsw.proto.service.CreateGroupRequest
	2,  // 11: com.bdsw.proto.service.GroupService.getGroupInfo:input_type -> com.bdsw.proto.service.GroupInfoRequest
	3,  // 12: com.bdsw.proto.service.GroupService.updateGroupInfo:input_type -> com.bdsw.proto.service.UpdateGroupRequest
	4,  // 13: com.bdsw.proto.service.GroupService.dismissGroup:input_type -> com.bdsw.proto.service.DismissGroupRequest
	5,  // 14: com.bdsw.proto.service.GroupService.getGroupMembers:input_type -> com.bdsw.proto.service.GroupMembersRequest
	7,  // 15: com.bdsw.proto.service.GroupService.addGroupMembers:input_type -> com.bdsw.proto.service.AddMembersRequest
	8,  // 16: com.bdsw.proto.service.GroupService.removeGroupMembers:input_type -> com.bdsw.proto.service.RemoveMembersRequest
	9,  // 17: com.bdsw.proto.service.GroupService.updateGroupMember:input_type -> com.bdsw.proto.service.UpdateMemberRequest
	10, // 18: com.bdsw.proto.service.GroupService.handleGroupApply:input_type -> com.bdsw.proto.service.HandleApplyRequest
	11, // 19: com.bdsw.proto.service.GroupService.getGroupApplies:input_type -> com.bdsw.proto.service.GroupAppliesRequest
	13, // 20: com.bdsw.proto.service.GroupService.setGroupAdmin:input_type -> com.bdsw.proto.service.SetAdminRequest
	14, // 21: com.bdsw.proto.service.GroupService.muteGroupMember:input_type -> com.bdsw.proto.service.MuteMemberRequest
	15, // 22: com.bdsw.proto.service.GroupService.muteAllMembers:input_type -> com.bdsw.proto.service.MuteAllRequest
	16, // 23: com.bdsw.proto.service.GroupService.transferGroupOwner:input_type -> com.bdsw.proto.service.TransferOwnerRequest
	1,  // 24: com.bdsw.proto.service.GroupService.createGroup:output_type -> com.bdsw.proto.service.CreateGroupResponse
	20, // 25: com.bdsw.proto.service.GroupService.getGroupInfo:output_type -> com.bdsw.proto.common.Group
	25, // 26: com.bdsw.proto.service.GroupService.updateGroupInfo:output_type -> com.bdsw.proto.common.Response
	25, // 27: com.bdsw.proto.service.GroupService.dismissGroup:output_type -> com.bdsw.proto.common.Response
	6,  // 28: com.bdsw.proto.service.GroupService.getGroupMembers:output_type -> com.bdsw.proto.service.GroupMembersResponse
	25, // 29: com.bdsw.proto.service.GroupService.addGroupMembers:output_type -> com.bdsw.proto.common.Response
	25, // 30: com.bdsw.proto.service.GroupService.removeGroupMembers:output_type -> com.bdsw.proto.common.Response
	25, // 31: com.bdsw.proto.service.GroupService.updateGroupMember:output_type -> com.bdsw.proto.common.Response
	25, // 32: com.bdsw.proto.service.GroupService.handleGroupApply:output_type -> com.bdsw.proto.common.Response
	12, // 33: com.bdsw.proto.service.GroupService.getGroupApplies:output_type -> com.bdsw.proto.service.GroupAppliesResponse
	25, // 34: com.bdsw.proto.service.GroupService.setGroupAdmin:output_type -> com.bdsw.proto.common.Response
	25, // 35: com.bdsw.proto.service.GroupService.muteGroupMember:output_type -> com.bdsw.proto.common.Response
	25, // 36: com.bdsw.proto.service.GroupService.muteAllMembers:output_type -> com.bdsw.proto.common.Response
	25, // 37: com.bdsw.proto.service.GroupService.transferGroupOwner:output_type -> com.bdsw.proto.common.Response
	24, // [24:38] is the sub-list for method output_type
	10, // [10:24] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_proto_service_group_service_proto_init() }
func file_proto_service_group_service_proto_init() {
	if File_proto_service_group_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_service_group_service_proto_rawDesc), len(file_proto_service_group_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_service_group_service_proto_goTypes,
		DependencyIndexes: file_proto_service_group_service_proto_depIdxs,
		MessageInfos:      file_proto_service_group_service_proto_msgTypes,
	}.Build()
	File_proto_service_group_service_proto = out.File
	file_proto_service_group_service_proto_goTypes = nil
	file_proto_service_group_service_proto_depIdxs = nil
}
