// Code generated by protoc-gen-go-triple. DO NOT EDIT.
// versions:
// - protoc-gen-go-triple v1.0.8
// - protoc             v6.32.1
// source: proto/service/message_service.proto

package service

import (
	context "context"
	protocol "dubbo.apache.org/dubbo-go/v3/protocol"
	dubbo3 "dubbo.apache.org/dubbo-go/v3/protocol/dubbo3"
	invocation "dubbo.apache.org/dubbo-go/v3/protocol/invocation"
	common1 "github.com/bdsw/bdsw-im-ws/proto/common"
	grpc_go "github.com/dubbogo/grpc-go"
	codes "github.com/dubbogo/grpc-go/codes"
	metadata "github.com/dubbogo/grpc-go/metadata"
	status "github.com/dubbogo/grpc-go/status"
	common "github.com/dubbogo/triple/pkg/common"
	constant "github.com/dubbogo/triple/pkg/common/constant"
	triple "github.com/dubbogo/triple/pkg/triple"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc_go.SupportPackageIsVersion7

// MessageServiceClient is the client API for MessageService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MessageServiceClient interface {
	// 发送消息
	SendMessage(ctx context.Context, in *SendMessageRequest, opts ...grpc_go.CallOption) (*SendMessageResponse, common.ErrorWithAttachment)
	// 消息投递到MQ
	DeliverMessage(ctx context.Context, in *DeliverMessageRequest, opts ...grpc_go.CallOption) (*common1.Response, common.ErrorWithAttachment)
	// 撤回消息
	RecallMessage(ctx context.Context, in *RecallMessageRequest, opts ...grpc_go.CallOption) (*common1.Response, common.ErrorWithAttachment)
	// 删除消息
	DeleteMessage(ctx context.Context, in *DeleteMessageRequest, opts ...grpc_go.CallOption) (*common1.Response, common.ErrorWithAttachment)
	// 标记消息已读
	MarkMessageRead(ctx context.Context, in *MarkReadRequest, opts ...grpc_go.CallOption) (*common1.Response, common.ErrorWithAttachment)
	// 获取单条消息
	GetMessage(ctx context.Context, in *GetMessageRequest, opts ...grpc_go.CallOption) (*common1.Message, common.ErrorWithAttachment)
	// 获取历史消息
	GetHistoryMessages(ctx context.Context, in *HistoryRequest, opts ...grpc_go.CallOption) (*HistoryResponse, common.ErrorWithAttachment)
	// 搜索消息
	SearchMessages(ctx context.Context, in *SearchRequest, opts ...grpc_go.CallOption) (*SearchResponse, common.ErrorWithAttachment)
	// 获取会话列表
	GetConversations(ctx context.Context, in *ConversationRequest, opts ...grpc_go.CallOption) (*ConversationResponse, common.ErrorWithAttachment)
	// 清空会话消息
	ClearConversation(ctx context.Context, in *ClearConversationRequest, opts ...grpc_go.CallOption) (*common1.Response, common.ErrorWithAttachment)
}

type messageServiceClient struct {
	cc *triple.TripleConn
}

type MessageServiceClientImpl struct {
	SendMessage        func(ctx context.Context, in *SendMessageRequest) (*SendMessageResponse, error)
	DeliverMessage     func(ctx context.Context, in *DeliverMessageRequest) (*common1.Response, error)
	RecallMessage      func(ctx context.Context, in *RecallMessageRequest) (*common1.Response, error)
	DeleteMessage      func(ctx context.Context, in *DeleteMessageRequest) (*common1.Response, error)
	MarkMessageRead    func(ctx context.Context, in *MarkReadRequest) (*common1.Response, error)
	GetMessage         func(ctx context.Context, in *GetMessageRequest) (*common1.Message, error)
	GetHistoryMessages func(ctx context.Context, in *HistoryRequest) (*HistoryResponse, error)
	SearchMessages     func(ctx context.Context, in *SearchRequest) (*SearchResponse, error)
	GetConversations   func(ctx context.Context, in *ConversationRequest) (*ConversationResponse, error)
	ClearConversation  func(ctx context.Context, in *ClearConversationRequest) (*common1.Response, error)
}

func (c *MessageServiceClientImpl) GetDubboStub(cc *triple.TripleConn) MessageServiceClient {
	return NewMessageServiceClient(cc)
}

func (c *MessageServiceClientImpl) XXX_InterfaceName() string {
	return "com.bdsw.proto.service.MessageService"
}

func NewMessageServiceClient(cc *triple.TripleConn) MessageServiceClient {
	return &messageServiceClient{cc}
}

func (c *messageServiceClient) SendMessage(ctx context.Context, in *SendMessageRequest, opts ...grpc_go.CallOption) (*SendMessageResponse, common.ErrorWithAttachment) {
	out := new(SendMessageResponse)
	interfaceKey := ctx.Value(constant.InterfaceKey).(string)
	return out, c.cc.Invoke(ctx, "/"+interfaceKey+"/SendMessage", in, out)
}

func (c *messageServiceClient) DeliverMessage(ctx context.Context, in *DeliverMessageRequest, opts ...grpc_go.CallOption) (*common1.Response, common.ErrorWithAttachment) {
	out := new(common1.Response)
	interfaceKey := ctx.Value(constant.InterfaceKey).(string)
	return out, c.cc.Invoke(ctx, "/"+interfaceKey+"/DeliverMessage", in, out)
}

func (c *messageServiceClient) RecallMessage(ctx context.Context, in *RecallMessageRequest, opts ...grpc_go.CallOption) (*common1.Response, common.ErrorWithAttachment) {
	out := new(common1.Response)
	interfaceKey := ctx.Value(constant.InterfaceKey).(string)
	return out, c.cc.Invoke(ctx, "/"+interfaceKey+"/RecallMessage", in, out)
}

func (c *messageServiceClient) DeleteMessage(ctx context.Context, in *DeleteMessageRequest, opts ...grpc_go.CallOption) (*common1.Response, common.ErrorWithAttachment) {
	out := new(common1.Response)
	interfaceKey := ctx.Value(constant.InterfaceKey).(string)
	return out, c.cc.Invoke(ctx, "/"+interfaceKey+"/DeleteMessage", in, out)
}

func (c *messageServiceClient) MarkMessageRead(ctx context.Context, in *MarkReadRequest, opts ...grpc_go.CallOption) (*common1.Response, common.ErrorWithAttachment) {
	out := new(common1.Response)
	interfaceKey := ctx.Value(constant.InterfaceKey).(string)
	return out, c.cc.Invoke(ctx, "/"+interfaceKey+"/MarkMessageRead", in, out)
}

func (c *messageServiceClient) GetMessage(ctx context.Context, in *GetMessageRequest, opts ...grpc_go.CallOption) (*common1.Message, common.ErrorWithAttachment) {
	out := new(common1.Message)
	interfaceKey := ctx.Value(constant.InterfaceKey).(string)
	return out, c.cc.Invoke(ctx, "/"+interfaceKey+"/GetMessage", in, out)
}

func (c *messageServiceClient) GetHistoryMessages(ctx context.Context, in *HistoryRequest, opts ...grpc_go.CallOption) (*HistoryResponse, common.ErrorWithAttachment) {
	out := new(HistoryResponse)
	interfaceKey := ctx.Value(constant.InterfaceKey).(string)
	return out, c.cc.Invoke(ctx, "/"+interfaceKey+"/GetHistoryMessages", in, out)
}

func (c *messageServiceClient) SearchMessages(ctx context.Context, in *SearchRequest, opts ...grpc_go.CallOption) (*SearchResponse, common.ErrorWithAttachment) {
	out := new(SearchResponse)
	interfaceKey := ctx.Value(constant.InterfaceKey).(string)
	return out, c.cc.Invoke(ctx, "/"+interfaceKey+"/SearchMessages", in, out)
}

func (c *messageServiceClient) GetConversations(ctx context.Context, in *ConversationRequest, opts ...grpc_go.CallOption) (*ConversationResponse, common.ErrorWithAttachment) {
	out := new(ConversationResponse)
	interfaceKey := ctx.Value(constant.InterfaceKey).(string)
	return out, c.cc.Invoke(ctx, "/"+interfaceKey+"/GetConversations", in, out)
}

func (c *messageServiceClient) ClearConversation(ctx context.Context, in *ClearConversationRequest, opts ...grpc_go.CallOption) (*common1.Response, common.ErrorWithAttachment) {
	out := new(common1.Response)
	interfaceKey := ctx.Value(constant.InterfaceKey).(string)
	return out, c.cc.Invoke(ctx, "/"+interfaceKey+"/ClearConversation", in, out)
}

// MessageServiceServer is the server API for MessageService service.
// All implementations must embed UnimplementedMessageServiceServer
// for forward compatibility
type MessageServiceServer interface {
	// 发送消息
	SendMessage(context.Context, *SendMessageRequest) (*SendMessageResponse, error)
	// 消息投递到MQ
	DeliverMessage(context.Context, *DeliverMessageRequest) (*common1.Response, error)
	// 撤回消息
	RecallMessage(context.Context, *RecallMessageRequest) (*common1.Response, error)
	// 删除消息
	DeleteMessage(context.Context, *DeleteMessageRequest) (*common1.Response, error)
	// 标记消息已读
	MarkMessageRead(context.Context, *MarkReadRequest) (*common1.Response, error)
	// 获取单条消息
	GetMessage(context.Context, *GetMessageRequest) (*common1.Message, error)
	// 获取历史消息
	GetHistoryMessages(context.Context, *HistoryRequest) (*HistoryResponse, error)
	// 搜索消息
	SearchMessages(context.Context, *SearchRequest) (*SearchResponse, error)
	// 获取会话列表
	GetConversations(context.Context, *ConversationRequest) (*ConversationResponse, error)
	// 清空会话消息
	ClearConversation(context.Context, *ClearConversationRequest) (*common1.Response, error)
	mustEmbedUnimplementedMessageServiceServer()
}

// UnimplementedMessageServiceServer must be embedded to have forward compatible implementations.
type UnimplementedMessageServiceServer struct {
	proxyImpl protocol.Invoker
}

func (UnimplementedMessageServiceServer) SendMessage(context.Context, *SendMessageRequest) (*SendMessageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendMessage not implemented")
}
func (UnimplementedMessageServiceServer) DeliverMessage(context.Context, *DeliverMessageRequest) (*common1.Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeliverMessage not implemented")
}
func (UnimplementedMessageServiceServer) RecallMessage(context.Context, *RecallMessageRequest) (*common1.Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RecallMessage not implemented")
}
func (UnimplementedMessageServiceServer) DeleteMessage(context.Context, *DeleteMessageRequest) (*common1.Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteMessage not implemented")
}
func (UnimplementedMessageServiceServer) MarkMessageRead(context.Context, *MarkReadRequest) (*common1.Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MarkMessageRead not implemented")
}
func (UnimplementedMessageServiceServer) GetMessage(context.Context, *GetMessageRequest) (*common1.Message, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMessage not implemented")
}
func (UnimplementedMessageServiceServer) GetHistoryMessages(context.Context, *HistoryRequest) (*HistoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetHistoryMessages not implemented")
}
func (UnimplementedMessageServiceServer) SearchMessages(context.Context, *SearchRequest) (*SearchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchMessages not implemented")
}
func (UnimplementedMessageServiceServer) GetConversations(context.Context, *ConversationRequest) (*ConversationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetConversations not implemented")
}
func (UnimplementedMessageServiceServer) ClearConversation(context.Context, *ClearConversationRequest) (*common1.Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClearConversation not implemented")
}
func (s *UnimplementedMessageServiceServer) XXX_SetProxyImpl(impl protocol.Invoker) {
	s.proxyImpl = impl
}

func (s *UnimplementedMessageServiceServer) XXX_GetProxyImpl() protocol.Invoker {
	return s.proxyImpl
}

func (s *UnimplementedMessageServiceServer) XXX_ServiceDesc() *grpc_go.ServiceDesc {
	return &MessageService_ServiceDesc
}
func (s *UnimplementedMessageServiceServer) XXX_InterfaceName() string {
	return "com.bdsw.proto.service.MessageService"
}

func (UnimplementedMessageServiceServer) mustEmbedUnimplementedMessageServiceServer() {}

// UnsafeMessageServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MessageServiceServer will
// result in compilation errors.
type UnsafeMessageServiceServer interface {
	mustEmbedUnimplementedMessageServiceServer()
}

func RegisterMessageServiceServer(s grpc_go.ServiceRegistrar, srv MessageServiceServer) {
	s.RegisterService(&MessageService_ServiceDesc, srv)
}

func _MessageService_SendMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc_go.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	base := srv.(dubbo3.Dubbo3GrpcService)
	args := []interface{}{}
	args = append(args, in)
	md, _ := metadata.FromIncomingContext(ctx)
	invAttachment := make(map[string]interface{}, len(md))
	for k, v := range md {
		invAttachment[k] = v
	}
	invo := invocation.NewRPCInvocation("SendMessage", args, invAttachment)
	if interceptor == nil {
		result := base.XXX_GetProxyImpl().Invoke(ctx, invo)
		return result, result.Error()
	}
	info := &grpc_go.UnaryServerInfo{
		Server:     srv,
		FullMethod: ctx.Value("XXX_TRIPLE_GO_INTERFACE_NAME").(string),
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		result := base.XXX_GetProxyImpl().Invoke(ctx, invo)
		return result, result.Error()
	}
	return interceptor(ctx, in, info, handler)
}

func _MessageService_DeliverMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc_go.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeliverMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	base := srv.(dubbo3.Dubbo3GrpcService)
	args := []interface{}{}
	args = append(args, in)
	md, _ := metadata.FromIncomingContext(ctx)
	invAttachment := make(map[string]interface{}, len(md))
	for k, v := range md {
		invAttachment[k] = v
	}
	invo := invocation.NewRPCInvocation("DeliverMessage", args, invAttachment)
	if interceptor == nil {
		result := base.XXX_GetProxyImpl().Invoke(ctx, invo)
		return result, result.Error()
	}
	info := &grpc_go.UnaryServerInfo{
		Server:     srv,
		FullMethod: ctx.Value("XXX_TRIPLE_GO_INTERFACE_NAME").(string),
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		result := base.XXX_GetProxyImpl().Invoke(ctx, invo)
		return result, result.Error()
	}
	return interceptor(ctx, in, info, handler)
}

func _MessageService_RecallMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc_go.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecallMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	base := srv.(dubbo3.Dubbo3GrpcService)
	args := []interface{}{}
	args = append(args, in)
	md, _ := metadata.FromIncomingContext(ctx)
	invAttachment := make(map[string]interface{}, len(md))
	for k, v := range md {
		invAttachment[k] = v
	}
	invo := invocation.NewRPCInvocation("RecallMessage", args, invAttachment)
	if interceptor == nil {
		result := base.XXX_GetProxyImpl().Invoke(ctx, invo)
		return result, result.Error()
	}
	info := &grpc_go.UnaryServerInfo{
		Server:     srv,
		FullMethod: ctx.Value("XXX_TRIPLE_GO_INTERFACE_NAME").(string),
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		result := base.XXX_GetProxyImpl().Invoke(ctx, invo)
		return result, result.Error()
	}
	return interceptor(ctx, in, info, handler)
}

func _MessageService_DeleteMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc_go.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	base := srv.(dubbo3.Dubbo3GrpcService)
	args := []interface{}{}
	args = append(args, in)
	md, _ := metadata.FromIncomingContext(ctx)
	invAttachment := make(map[string]interface{}, len(md))
	for k, v := range md {
		invAttachment[k] = v
	}
	invo := invocation.NewRPCInvocation("DeleteMessage", args, invAttachment)
	if interceptor == nil {
		result := base.XXX_GetProxyImpl().Invoke(ctx, invo)
		return result, result.Error()
	}
	info := &grpc_go.UnaryServerInfo{
		Server:     srv,
		FullMethod: ctx.Value("XXX_TRIPLE_GO_INTERFACE_NAME").(string),
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		result := base.XXX_GetProxyImpl().Invoke(ctx, invo)
		return result, result.Error()
	}
	return interceptor(ctx, in, info, handler)
}

func _MessageService_MarkMessageRead_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc_go.UnaryServerInterceptor) (interface{}, error) {
	in := new(MarkReadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	base := srv.(dubbo3.Dubbo3GrpcService)
	args := []interface{}{}
	args = append(args, in)
	md, _ := metadata.FromIncomingContext(ctx)
	invAttachment := make(map[string]interface{}, len(md))
	for k, v := range md {
		invAttachment[k] = v
	}
	invo := invocation.NewRPCInvocation("MarkMessageRead", args, invAttachment)
	if interceptor == nil {
		result := base.XXX_GetProxyImpl().Invoke(ctx, invo)
		return result, result.Error()
	}
	info := &grpc_go.UnaryServerInfo{
		Server:     srv,
		FullMethod: ctx.Value("XXX_TRIPLE_GO_INTERFACE_NAME").(string),
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		result := base.XXX_GetProxyImpl().Invoke(ctx, invo)
		return result, result.Error()
	}
	return interceptor(ctx, in, info, handler)
}

func _MessageService_GetMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc_go.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	base := srv.(dubbo3.Dubbo3GrpcService)
	args := []interface{}{}
	args = append(args, in)
	md, _ := metadata.FromIncomingContext(ctx)
	invAttachment := make(map[string]interface{}, len(md))
	for k, v := range md {
		invAttachment[k] = v
	}
	invo := invocation.NewRPCInvocation("GetMessage", args, invAttachment)
	if interceptor == nil {
		result := base.XXX_GetProxyImpl().Invoke(ctx, invo)
		return result, result.Error()
	}
	info := &grpc_go.UnaryServerInfo{
		Server:     srv,
		FullMethod: ctx.Value("XXX_TRIPLE_GO_INTERFACE_NAME").(string),
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		result := base.XXX_GetProxyImpl().Invoke(ctx, invo)
		return result, result.Error()
	}
	return interceptor(ctx, in, info, handler)
}

func _MessageService_GetHistoryMessages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc_go.UnaryServerInterceptor) (interface{}, error) {
	in := new(HistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	base := srv.(dubbo3.Dubbo3GrpcService)
	args := []interface{}{}
	args = append(args, in)
	md, _ := metadata.FromIncomingContext(ctx)
	invAttachment := make(map[string]interface{}, len(md))
	for k, v := range md {
		invAttachment[k] = v
	}
	invo := invocation.NewRPCInvocation("GetHistoryMessages", args, invAttachment)
	if interceptor == nil {
		result := base.XXX_GetProxyImpl().Invoke(ctx, invo)
		return result, result.Error()
	}
	info := &grpc_go.UnaryServerInfo{
		Server:     srv,
		FullMethod: ctx.Value("XXX_TRIPLE_GO_INTERFACE_NAME").(string),
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		result := base.XXX_GetProxyImpl().Invoke(ctx, invo)
		return result, result.Error()
	}
	return interceptor(ctx, in, info, handler)
}

func _MessageService_SearchMessages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc_go.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	base := srv.(dubbo3.Dubbo3GrpcService)
	args := []interface{}{}
	args = append(args, in)
	md, _ := metadata.FromIncomingContext(ctx)
	invAttachment := make(map[string]interface{}, len(md))
	for k, v := range md {
		invAttachment[k] = v
	}
	invo := invocation.NewRPCInvocation("SearchMessages", args, invAttachment)
	if interceptor == nil {
		result := base.XXX_GetProxyImpl().Invoke(ctx, invo)
		return result, result.Error()
	}
	info := &grpc_go.UnaryServerInfo{
		Server:     srv,
		FullMethod: ctx.Value("XXX_TRIPLE_GO_INTERFACE_NAME").(string),
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		result := base.XXX_GetProxyImpl().Invoke(ctx, invo)
		return result, result.Error()
	}
	return interceptor(ctx, in, info, handler)
}

func _MessageService_GetConversations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc_go.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConversationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	base := srv.(dubbo3.Dubbo3GrpcService)
	args := []interface{}{}
	args = append(args, in)
	md, _ := metadata.FromIncomingContext(ctx)
	invAttachment := make(map[string]interface{}, len(md))
	for k, v := range md {
		invAttachment[k] = v
	}
	invo := invocation.NewRPCInvocation("GetConversations", args, invAttachment)
	if interceptor == nil {
		result := base.XXX_GetProxyImpl().Invoke(ctx, invo)
		return result, result.Error()
	}
	info := &grpc_go.UnaryServerInfo{
		Server:     srv,
		FullMethod: ctx.Value("XXX_TRIPLE_GO_INTERFACE_NAME").(string),
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		result := base.XXX_GetProxyImpl().Invoke(ctx, invo)
		return result, result.Error()
	}
	return interceptor(ctx, in, info, handler)
}

func _MessageService_ClearConversation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc_go.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClearConversationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	base := srv.(dubbo3.Dubbo3GrpcService)
	args := []interface{}{}
	args = append(args, in)
	md, _ := metadata.FromIncomingContext(ctx)
	invAttachment := make(map[string]interface{}, len(md))
	for k, v := range md {
		invAttachment[k] = v
	}
	invo := invocation.NewRPCInvocation("ClearConversation", args, invAttachment)
	if interceptor == nil {
		result := base.XXX_GetProxyImpl().Invoke(ctx, invo)
		return result, result.Error()
	}
	info := &grpc_go.UnaryServerInfo{
		Server:     srv,
		FullMethod: ctx.Value("XXX_TRIPLE_GO_INTERFACE_NAME").(string),
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		result := base.XXX_GetProxyImpl().Invoke(ctx, invo)
		return result, result.Error()
	}
	return interceptor(ctx, in, info, handler)
}

// MessageService_ServiceDesc is the grpc_go.ServiceDesc for MessageService service.
// It's only intended for direct use with grpc_go.RegisterService,
// and not to be introspected or modified (even as a copy)
var MessageService_ServiceDesc = grpc_go.ServiceDesc{
	ServiceName: "com.bdsw.proto.service.MessageService",
	HandlerType: (*MessageServiceServer)(nil),
	Methods: []grpc_go.MethodDesc{
		{
			MethodName: "sendMessage",
			Handler:    _MessageService_SendMessage_Handler,
		},
		{
			MethodName: "deliverMessage",
			Handler:    _MessageService_DeliverMessage_Handler,
		},
		{
			MethodName: "recallMessage",
			Handler:    _MessageService_RecallMessage_Handler,
		},
		{
			MethodName: "deleteMessage",
			Handler:    _MessageService_DeleteMessage_Handler,
		},
		{
			MethodName: "markMessageRead",
			Handler:    _MessageService_MarkMessageRead_Handler,
		},
		{
			MethodName: "getMessage",
			Handler:    _MessageService_GetMessage_Handler,
		},
		{
			MethodName: "getHistoryMessages",
			Handler:    _MessageService_GetHistoryMessages_Handler,
		},
		{
			MethodName: "searchMessages",
			Handler:    _MessageService_SearchMessages_Handler,
		},
		{
			MethodName: "getConversations",
			Handler:    _MessageService_GetConversations_Handler,
		},
		{
			MethodName: "clearConversation",
			Handler:    _MessageService_ClearConversation_Handler,
		},
	},
	Streams:  []grpc_go.StreamDesc{},
	Metadata: "proto/service/message_service.proto",
}
