// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: proto/service/message_service.proto

// Java 包的命名空间

package service

import (
	common "github.com/bdsw/bdsw-im-ws/proto/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SendMessageRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Message         *common.Message        `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	NeedReceipt     bool                   `protobuf:"varint,2,opt,name=need_receipt,json=needReceipt,proto3" json:"need_receipt,omitempty"`               // 是否需要送达回执
	NeedReadReceipt bool                   `protobuf:"varint,3,opt,name=need_read_receipt,json=needReadReceipt,proto3" json:"need_read_receipt,omitempty"` // 是否需要已读回执
	StoreOnly       bool                   `protobuf:"varint,4,opt,name=store_only,json=storeOnly,proto3" json:"store_only,omitempty"`                     // 是否只存储不推送（用于漫游消息同步）
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SendMessageRequest) Reset() {
	*x = SendMessageRequest{}
	mi := &file_proto_service_message_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageRequest) ProtoMessage() {}

func (x *SendMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_message_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageRequest.ProtoReflect.Descriptor instead.
func (*SendMessageRequest) Descriptor() ([]byte, []int) {
	return file_proto_service_message_service_proto_rawDescGZIP(), []int{0}
}

func (x *SendMessageRequest) GetMessage() *common.Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *SendMessageRequest) GetNeedReceipt() bool {
	if x != nil {
		return x.NeedReceipt
	}
	return false
}

func (x *SendMessageRequest) GetNeedReadReceipt() bool {
	if x != nil {
		return x.NeedReadReceipt
	}
	return false
}

func (x *SendMessageRequest) GetStoreOnly() bool {
	if x != nil {
		return x.StoreOnly
	}
	return false
}

type SendMessageResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	MsgId          string                 `protobuf:"bytes,1,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
	Seq            int64                  `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`
	ConvSeq        int64                  `protobuf:"varint,3,opt,name=conv_seq,json=convSeq,proto3" json:"conv_seq,omitempty"`
	ServerTime     int64                  `protobuf:"varint,4,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"`
	OfflineUserIds []string               `protobuf:"bytes,5,rep,name=offline_user_ids,json=offlineUserIds,proto3" json:"offline_user_ids,omitempty"` // 离线的用户ID列表
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SendMessageResponse) Reset() {
	*x = SendMessageResponse{}
	mi := &file_proto_service_message_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageResponse) ProtoMessage() {}

func (x *SendMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_message_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageResponse.ProtoReflect.Descriptor instead.
func (*SendMessageResponse) Descriptor() ([]byte, []int) {
	return file_proto_service_message_service_proto_rawDescGZIP(), []int{1}
}

func (x *SendMessageResponse) GetMsgId() string {
	if x != nil {
		return x.MsgId
	}
	return ""
}

func (x *SendMessageResponse) GetSeq() int64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *SendMessageResponse) GetConvSeq() int64 {
	if x != nil {
		return x.ConvSeq
	}
	return 0
}

func (x *SendMessageResponse) GetServerTime() int64 {
	if x != nil {
		return x.ServerTime
	}
	return 0
}

func (x *SendMessageResponse) GetOfflineUserIds() []string {
	if x != nil {
		return x.OfflineUserIds
	}
	return nil
}

type DeliverMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       *common.Message        `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	UserIds       []string               `protobuf:"bytes,2,rep,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"`                 // 需要投递的用户ID列表
	NeedPush      bool                   `protobuf:"varint,3,opt,name=need_push,json=needPush,proto3" json:"need_push,omitempty"`             // 是否需要推送
	PushStrategy  int32                  `protobuf:"varint,4,opt,name=push_strategy,json=pushStrategy,proto3" json:"push_strategy,omitempty"` // 推送策略: 0:实时 1:定时 2:合并
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeliverMessageRequest) Reset() {
	*x = DeliverMessageRequest{}
	mi := &file_proto_service_message_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeliverMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliverMessageRequest) ProtoMessage() {}

func (x *DeliverMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_message_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliverMessageRequest.ProtoReflect.Descriptor instead.
func (*DeliverMessageRequest) Descriptor() ([]byte, []int) {
	return file_proto_service_message_service_proto_rawDescGZIP(), []int{2}
}

func (x *DeliverMessageRequest) GetMessage() *common.Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *DeliverMessageRequest) GetUserIds() []string {
	if x != nil {
		return x.UserIds
	}
	return nil
}

func (x *DeliverMessageRequest) GetNeedPush() bool {
	if x != nil {
		return x.NeedPush
	}
	return false
}

func (x *DeliverMessageRequest) GetPushStrategy() int32 {
	if x != nil {
		return x.PushStrategy
	}
	return 0
}

type RecallMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MsgId         string                 `protobuf:"bytes,1,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
	OperatorId    string                 `protobuf:"bytes,2,opt,name=operator_id,json=operatorId,proto3" json:"operator_id,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecallMessageRequest) Reset() {
	*x = RecallMessageRequest{}
	mi := &file_proto_service_message_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecallMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecallMessageRequest) ProtoMessage() {}

func (x *RecallMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_message_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecallMessageRequest.ProtoReflect.Descriptor instead.
func (*RecallMessageRequest) Descriptor() ([]byte, []int) {
	return file_proto_service_message_service_proto_rawDescGZIP(), []int{3}
}

func (x *RecallMessageRequest) GetMsgId() string {
	if x != nil {
		return x.MsgId
	}
	return ""
}

func (x *RecallMessageRequest) GetOperatorId() string {
	if x != nil {
		return x.OperatorId
	}
	return ""
}

func (x *RecallMessageRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type DeleteMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	MsgIds        []string               `protobuf:"bytes,2,rep,name=msg_ids,json=msgIds,proto3" json:"msg_ids,omitempty"`
	DeleteForAll  bool                   `protobuf:"varint,3,opt,name=delete_for_all,json=deleteForAll,proto3" json:"delete_for_all,omitempty"` // 是否所有人删除（仅群主/管理员）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMessageRequest) Reset() {
	*x = DeleteMessageRequest{}
	mi := &file_proto_service_message_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMessageRequest) ProtoMessage() {}

func (x *DeleteMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_message_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMessageRequest.ProtoReflect.Descriptor instead.
func (*DeleteMessageRequest) Descriptor() ([]byte, []int) {
	return file_proto_service_message_service_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteMessageRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *DeleteMessageRequest) GetMsgIds() []string {
	if x != nil {
		return x.MsgIds
	}
	return nil
}

func (x *DeleteMessageRequest) GetDeleteForAll() bool {
	if x != nil {
		return x.DeleteForAll
	}
	return false
}

type MarkReadRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	UserId             string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ConversationId     string                 `protobuf:"bytes,2,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	ReadSeq            int64                  `protobuf:"varint,3,opt,name=read_seq,json=readSeq,proto3" json:"read_seq,omitempty"`
	SyncToOtherDevices bool                   `protobuf:"varint,4,opt,name=sync_to_other_devices,json=syncToOtherDevices,proto3" json:"sync_to_other_devices,omitempty"` // 是否同步到其他设备
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *MarkReadRequest) Reset() {
	*x = MarkReadRequest{}
	mi := &file_proto_service_message_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkReadRequest) ProtoMessage() {}

func (x *MarkReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_message_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkReadRequest.ProtoReflect.Descriptor instead.
func (*MarkReadRequest) Descriptor() ([]byte, []int) {
	return file_proto_service_message_service_proto_rawDescGZIP(), []int{5}
}

func (x *MarkReadRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *MarkReadRequest) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *MarkReadRequest) GetReadSeq() int64 {
	if x != nil {
		return x.ReadSeq
	}
	return 0
}

func (x *MarkReadRequest) GetSyncToOtherDevices() bool {
	if x != nil {
		return x.SyncToOtherDevices
	}
	return false
}

type GetMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MsgId         string                 `protobuf:"bytes,1,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMessageRequest) Reset() {
	*x = GetMessageRequest{}
	mi := &file_proto_service_message_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMessageRequest) ProtoMessage() {}

func (x *GetMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_message_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMessageRequest.ProtoReflect.Descriptor instead.
func (*GetMessageRequest) Descriptor() ([]byte, []int) {
	return file_proto_service_message_service_proto_rawDescGZIP(), []int{6}
}

func (x *GetMessageRequest) GetMsgId() string {
	if x != nil {
		return x.MsgId
	}
	return ""
}

type HistoryRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId string                 `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	StartSeq       int64                  `protobuf:"varint,2,opt,name=start_seq,json=startSeq,proto3" json:"start_seq,omitempty"` // 起始序列号（不包含）
	EndSeq         int64                  `protobuf:"varint,3,opt,name=end_seq,json=endSeq,proto3" json:"end_seq,omitempty"`       // 结束序列号（包含）
	Limit          int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	Reverse        bool                   `protobuf:"varint,5,opt,name=reverse,proto3" json:"reverse,omitempty"` // 是否反向查询（用于下拉加载更多）
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *HistoryRequest) Reset() {
	*x = HistoryRequest{}
	mi := &file_proto_service_message_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistoryRequest) ProtoMessage() {}

func (x *HistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_message_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistoryRequest.ProtoReflect.Descriptor instead.
func (*HistoryRequest) Descriptor() ([]byte, []int) {
	return file_proto_service_message_service_proto_rawDescGZIP(), []int{7}
}

func (x *HistoryRequest) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *HistoryRequest) GetStartSeq() int64 {
	if x != nil {
		return x.StartSeq
	}
	return 0
}

func (x *HistoryRequest) GetEndSeq() int64 {
	if x != nil {
		return x.EndSeq
	}
	return 0
}

func (x *HistoryRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *HistoryRequest) GetReverse() bool {
	if x != nil {
		return x.Reverse
	}
	return false
}

type HistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*common.Message      `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	HasMore       bool                   `protobuf:"varint,2,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	MinSeq        int64                  `protobuf:"varint,3,opt,name=min_seq,json=minSeq,proto3" json:"min_seq,omitempty"`
	MaxSeq        int64                  `protobuf:"varint,4,opt,name=max_seq,json=maxSeq,proto3" json:"max_seq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HistoryResponse) Reset() {
	*x = HistoryResponse{}
	mi := &file_proto_service_message_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistoryResponse) ProtoMessage() {}

func (x *HistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_message_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistoryResponse.ProtoReflect.Descriptor instead.
func (*HistoryResponse) Descriptor() ([]byte, []int) {
	return file_proto_service_message_service_proto_rawDescGZIP(), []int{8}
}

func (x *HistoryResponse) GetMessages() []*common.Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *HistoryResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

func (x *HistoryResponse) GetMinSeq() int64 {
	if x != nil {
		return x.MinSeq
	}
	return 0
}

func (x *HistoryResponse) GetMaxSeq() int64 {
	if x != nil {
		return x.MaxSeq
	}
	return 0
}

type SearchRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Keyword        string                 `protobuf:"bytes,2,opt,name=keyword,proto3" json:"keyword,omitempty"`
	ConversationId string                 `protobuf:"bytes,3,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"` // 可选，指定会话搜索
	StartTime      int64                  `protobuf:"varint,4,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime        int64                  `protobuf:"varint,5,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	MessageTypes   []common.MessageType   `protobuf:"varint,6,rep,packed,name=message_types,json=messageTypes,proto3,enum=com.bdsw.proto.common.MessageType" json:"message_types,omitempty"`
	Page           *common.PageRequest    `protobuf:"bytes,7,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_proto_service_message_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_message_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_proto_service_message_service_proto_rawDescGZIP(), []int{9}
}

func (x *SearchRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SearchRequest) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *SearchRequest) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *SearchRequest) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *SearchRequest) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *SearchRequest) GetMessageTypes() []common.MessageType {
	if x != nil {
		return x.MessageTypes
	}
	return nil
}

func (x *SearchRequest) GetPage() *common.PageRequest {
	if x != nil {
		return x.Page
	}
	return nil
}

type SearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*common.Message      `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	Page          *common.PageResponse   `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	Total         int32                  `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResponse) Reset() {
	*x = SearchResponse{}
	mi := &file_proto_service_message_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponse) ProtoMessage() {}

func (x *SearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_message_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponse.ProtoReflect.Descriptor instead.
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return file_proto_service_message_service_proto_rawDescGZIP(), []int{10}
}

func (x *SearchResponse) GetMessages() []*common.Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *SearchResponse) GetPage() *common.PageResponse {
	if x != nil {
		return x.Page
	}
	return nil
}

func (x *SearchResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type ConversationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UpdateTime    int64                  `protobuf:"varint,2,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"` // 客户端最后更新时间，用于增量同步
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConversationRequest) Reset() {
	*x = ConversationRequest{}
	mi := &file_proto_service_message_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConversationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConversationRequest) ProtoMessage() {}

func (x *ConversationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_message_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConversationRequest.ProtoReflect.Descriptor instead.
func (*ConversationRequest) Descriptor() ([]byte, []int) {
	return file_proto_service_message_service_proto_rawDescGZIP(), []int{11}
}

func (x *ConversationRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ConversationRequest) GetUpdateTime() int64 {
	if x != nil {
		return x.UpdateTime
	}
	return 0
}

type ConversationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Conversations []*common.Conversation `protobuf:"bytes,1,rep,name=conversations,proto3" json:"conversations,omitempty"`
	ServerTime    int64                  `protobuf:"varint,2,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"`
	FullSync      bool                   `protobuf:"varint,3,opt,name=full_sync,json=fullSync,proto3" json:"full_sync,omitempty"` // 是否全量同步
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConversationResponse) Reset() {
	*x = ConversationResponse{}
	mi := &file_proto_service_message_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConversationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConversationResponse) ProtoMessage() {}

func (x *ConversationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_message_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConversationResponse.ProtoReflect.Descriptor instead.
func (*ConversationResponse) Descriptor() ([]byte, []int) {
	return file_proto_service_message_service_proto_rawDescGZIP(), []int{12}
}

func (x *ConversationResponse) GetConversations() []*common.Conversation {
	if x != nil {
		return x.Conversations
	}
	return nil
}

func (x *ConversationResponse) GetServerTime() int64 {
	if x != nil {
		return x.ServerTime
	}
	return 0
}

func (x *ConversationResponse) GetFullSync() bool {
	if x != nil {
		return x.FullSync
	}
	return false
}

type ClearConversationRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ConversationId string                 `protobuf:"bytes,2,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	ClearHistory   bool                   `protobuf:"varint,3,opt,name=clear_history,json=clearHistory,proto3" json:"clear_history,omitempty"` // 是否清除历史消息
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ClearConversationRequest) Reset() {
	*x = ClearConversationRequest{}
	mi := &file_proto_service_message_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearConversationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearConversationRequest) ProtoMessage() {}

func (x *ClearConversationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_message_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearConversationRequest.ProtoReflect.Descriptor instead.
func (*ClearConversationRequest) Descriptor() ([]byte, []int) {
	return file_proto_service_message_service_proto_rawDescGZIP(), []int{13}
}

func (x *ClearConversationRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ClearConversationRequest) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *ClearConversationRequest) GetClearHistory() bool {
	if x != nil {
		return x.ClearHistory
	}
	return false
}

var File_proto_service_message_service_proto protoreflect.FileDescriptor

const file_proto_service_message_service_proto_rawDesc = "" +
	"\n" +
	"#proto/service/message_service.proto\x12\x16com.bdsw.proto.service\x1a\x19proto/common/common.proto\x1a\x1aproto/common/message.proto\"\xbc\x01\n" +
	"\x12SendMessageRequest\x128\n" +
	"\amessage\x18\x01 \x01(\v2\x1e.com.bdsw.proto.common.MessageR\amessage\x12!\n" +
	"\fneed_receipt\x18\x02 \x01(\bR\vneedReceipt\x12*\n" +
	"\x11need_read_receipt\x18\x03 \x01(\bR\x0fneedReadReceipt\x12\x1d\n" +
	"\n" +
	"store_only\x18\x04 \x01(\bR\tstoreOnly\"\xa4\x01\n" +
	"\x13SendMessageResponse\x12\x15\n" +
	"\x06msg_id\x18\x01 \x01(\tR\x05msgId\x12\x10\n" +
	"\x03seq\x18\x02 \x01(\x03R\x03seq\x12\x19\n" +
	"\bconv_seq\x18\x03 \x01(\x03R\aconvSeq\x12\x1f\n" +
	"\vserver_time\x18\x04 \x01(\x03R\n" +
	"serverTime\x12(\n" +
	"\x10offline_user_ids\x18\x05 \x03(\tR\x0eofflineUserIds\"\xae\x01\n" +
	"\x15DeliverMessageRequest\x128\n" +
	"\amessage\x18\x01 \x01(\v2\x1e.com.bdsw.proto.common.MessageR\amessage\x12\x19\n" +
	"\buser_ids\x18\x02 \x03(\tR\auserIds\x12\x1b\n" +
	"\tneed_push\x18\x03 \x01(\bR\bneedPush\x12#\n" +
	"\rpush_strategy\x18\x04 \x01(\x05R\fpushStrategy\"f\n" +
	"\x14RecallMessageRequest\x12\x15\n" +
	"\x06msg_id\x18\x01 \x01(\tR\x05msgId\x12\x1f\n" +
	"\voperator_id\x18\x02 \x01(\tR\n" +
	"operatorId\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"n\n" +
	"\x14DeleteMessageRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x17\n" +
	"\amsg_ids\x18\x02 \x03(\tR\x06msgIds\x12$\n" +
	"\x0edelete_for_all\x18\x03 \x01(\bR\fdeleteForAll\"\xa1\x01\n" +
	"\x0fMarkReadRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12'\n" +
	"\x0fconversation_id\x18\x02 \x01(\tR\x0econversationId\x12\x19\n" +
	"\bread_seq\x18\x03 \x01(\x03R\areadSeq\x121\n" +
	"\x15sync_to_other_devices\x18\x04 \x01(\bR\x12syncToOtherDevices\"*\n" +
	"\x11GetMessageRequest\x12\x15\n" +
	"\x06msg_id\x18\x01 \x01(\tR\x05msgId\"\x9f\x01\n" +
	"\x0eHistoryRequest\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId\x12\x1b\n" +
	"\tstart_seq\x18\x02 \x01(\x03R\bstartSeq\x12\x17\n" +
	"\aend_seq\x18\x03 \x01(\x03R\x06endSeq\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\x12\x18\n" +
	"\areverse\x18\x05 \x01(\bR\areverse\"\x9a\x01\n" +
	"\x0fHistoryResponse\x12:\n" +
	"\bmessages\x18\x01 \x03(\v2\x1e.com.bdsw.proto.common.MessageR\bmessages\x12\x19\n" +
	"\bhas_more\x18\x02 \x01(\bR\ahasMore\x12\x17\n" +
	"\amin_seq\x18\x03 \x01(\x03R\x06minSeq\x12\x17\n" +
	"\amax_seq\x18\x04 \x01(\x03R\x06maxSeq\"\xa6\x02\n" +
	"\rSearchRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x18\n" +
	"\akeyword\x18\x02 \x01(\tR\akeyword\x12'\n" +
	"\x0fconversation_id\x18\x03 \x01(\tR\x0econversationId\x12\x1d\n" +
	"\n" +
	"start_time\x18\x04 \x01(\x03R\tstartTime\x12\x19\n" +
	"\bend_time\x18\x05 \x01(\x03R\aendTime\x12G\n" +
	"\rmessage_types\x18\x06 \x03(\x0e2\".com.bdsw.proto.common.MessageTypeR\fmessageTypes\x126\n" +
	"\x04page\x18\a \x01(\v2\".com.bdsw.proto.common.PageRequestR\x04page\"\x9b\x01\n" +
	"\x0eSearchResponse\x12:\n" +
	"\bmessages\x18\x01 \x03(\v2\x1e.com.bdsw.proto.common.MessageR\bmessages\x127\n" +
	"\x04page\x18\x02 \x01(\v2#.com.bdsw.proto.common.PageResponseR\x04page\x12\x14\n" +
	"\x05total\x18\x03 \x01(\x05R\x05total\"O\n" +
	"\x13ConversationRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1f\n" +
	"\vupdate_time\x18\x02 \x01(\x03R\n" +
	"updateTime\"\x9f\x01\n" +
	"\x14ConversationResponse\x12I\n" +
	"\rconversations\x18\x01 \x03(\v2#.com.bdsw.proto.common.ConversationR\rconversations\x12\x1f\n" +
	"\vserver_time\x18\x02 \x01(\x03R\n" +
	"serverTime\x12\x1b\n" +
	"\tfull_sync\x18\x03 \x01(\bR\bfullSync\"\x81\x01\n" +
	"\x18ClearConversationRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12'\n" +
	"\x0fconversation_id\x18\x02 \x01(\tR\x0econversationId\x12#\n" +
	"\rclear_history\x18\x03 \x01(\bR\fclearHistory2\xef\a\n" +
	"\x0eMessageService\x12f\n" +
	"\vsendMessage\x12*.com.bdsw.proto.service.SendMessageRequest\x1a+.com.bdsw.proto.service.SendMessageResponse\x12`\n" +
	"\x0edeliverMessage\x12-.com.bdsw.proto.service.DeliverMessageRequest\x1a\x1f.com.bdsw.proto.common.Response\x12^\n" +
	"\rrecallMessage\x12,.com.bdsw.proto.service.RecallMessageRequest\x1a\x1f.com.bdsw.proto.common.Response\x12^\n" +
	"\rdeleteMessage\x12,.com.bdsw.proto.service.DeleteMessageRequest\x1a\x1f.com.bdsw.proto.common.Response\x12[\n" +
	"\x0fmarkMessageRead\x12'.com.bdsw.proto.service.MarkReadRequest\x1a\x1f.com.bdsw.proto.common.Response\x12W\n" +
	"\n" +
	"getMessage\x12).com.bdsw.proto.service.GetMessageRequest\x1a\x1e.com.bdsw.proto.common.Message\x12e\n" +
	"\x12getHistoryMessages\x12&.com.bdsw.proto.service.HistoryRequest\x1a'.com.bdsw.proto.service.HistoryResponse\x12_\n" +
	"\x0esearchMessages\x12%.com.bdsw.proto.service.SearchRequest\x1a&.com.bdsw.proto.service.SearchResponse\x12m\n" +
	"\x10getConversations\x12+.com.bdsw.proto.service.ConversationRequest\x1a,.com.bdsw.proto.service.ConversationResponse\x12f\n" +
	"\x11clearConversation\x120.com.bdsw.proto.service.ClearConversationRequest\x1a\x1f.com.bdsw.proto.common.ResponseBa\n" +
	"\x16com.bdsw.proto.serviceB\x13MessageServiceProtoP\x01Z0github.com/bdsw/bdsw-im-ws/proto/service;serviceb\x06proto3"

var (
	file_proto_service_message_service_proto_rawDescOnce sync.Once
	file_proto_service_message_service_proto_rawDescData []byte
)

func file_proto_service_message_service_proto_rawDescGZIP() []byte {
	file_proto_service_message_service_proto_rawDescOnce.Do(func() {
		file_proto_service_message_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_service_message_service_proto_rawDesc), len(file_proto_service_message_service_proto_rawDesc)))
	})
	return file_proto_service_message_service_proto_rawDescData
}

var file_proto_service_message_service_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_proto_service_message_service_proto_goTypes = []any{
	(*SendMessageRequest)(nil),       // 0: com.bdsw.proto.service.SendMessageRequest
	(*SendMessageResponse)(nil),      // 1: com.bdsw.proto.service.SendMessageResponse
	(*DeliverMessageRequest)(nil),    // 2: com.bdsw.proto.service.DeliverMessageRequest
	(*RecallMessageRequest)(nil),     // 3: com.bdsw.proto.service.RecallMessageRequest
	(*DeleteMessageRequest)(nil),     // 4: com.bdsw.proto.service.DeleteMessageRequest
	(*MarkReadRequest)(nil),          // 5: com.bdsw.proto.service.MarkReadRequest
	(*GetMessageRequest)(nil),        // 6: com.bdsw.proto.service.GetMessageRequest
	(*HistoryRequest)(nil),           // 7: com.bdsw.proto.service.HistoryRequest
	(*HistoryResponse)(nil),          // 8: com.bdsw.proto.service.HistoryResponse
	(*SearchRequest)(nil),            // 9: com.bdsw.proto.service.SearchRequest
	(*SearchResponse)(nil),           // 10: com.bdsw.proto.service.SearchResponse
	(*ConversationRequest)(nil),      // 11: com.bdsw.proto.service.ConversationRequest
	(*ConversationResponse)(nil),     // 12: com.bdsw.proto.service.ConversationResponse
	(*ClearConversationRequest)(nil), // 13: com.bdsw.proto.service.ClearConversationRequest
	(*common.Message)(nil),           // 14: com.bdsw.proto.common.Message
	(common.MessageType)(0),          // 15: com.bdsw.proto.common.MessageType
	(*common.PageRequest)(nil),       // 16: com.bdsw.proto.common.PageRequest
	(*common.PageResponse)(nil),      // 17: com.bdsw.proto.common.PageResponse
	(*common.Conversation)(nil),      // 18: com.bdsw.proto.common.Conversation
	(*common.Response)(nil),          // 19: com.bdsw.proto.common.Response
}
var file_proto_service_message_service_proto_depIdxs = []int32{
	14, // 0: com.bdsw.proto.service.SendMessageRequest.message:type_name -> com.bdsw.proto.common.Message
	14, // 1: com.bdsw.proto.service.DeliverMessageRequest.message:type_name -> com.bdsw.proto.common.Message
	14, // 2: com.bdsw.proto.service.HistoryResponse.messages:type_name -> com.bdsw.proto.common.Message
	15, // 3: com.bdsw.proto.service.SearchRequest.message_types:type_name -> com.bdsw.proto.common.MessageType
	16, // 4: com.bdsw.proto.service.SearchRequest.page:type_name -> com.bdsw.proto.common.PageRequest
	14, // 5: com.bdsw.proto.service.SearchResponse.messages:type_name -> com.bdsw.proto.common.Message
	17, // 6: com.bdsw.proto.service.SearchResponse.page:type_name -> com.bdsw.proto.common.PageResponse
	18, // 7: com.bdsw.proto.service.ConversationResponse.conversations:type_name -> com.bdsw.proto.common.Conversation
	0,  // 8: com.bdsw.proto.service.MessageService.sendMessage:input_type -> com.bdsw.proto.service.SendMessageRequest
	2,  // 9: com.bdsw.proto.service.MessageService.deliverMessage:input_type -> com.bdsw.proto.service.DeliverMessageRequest
	3,  // 10: com.bdsw.proto.service.MessageService.recallMessage:input_type -> com.bdsw.proto.service.RecallMessageRequest
	4,  // 11: com.bdsw.proto.service.MessageService.deleteMessage:input_type -> com.bdsw.proto.service.DeleteMessageRequest
	5,  // 12: com.bdsw.proto.service.MessageService.markMessageRead:input_type -> com.bdsw.proto.service.MarkReadRequest
	6,  // 13: com.bdsw.proto.service.MessageService.getMessage:input_type -> com.bdsw.proto.service.GetMessageRequest
	7,  // 14: com.bdsw.proto.service.MessageService.getHistoryMessages:input_type -> com.bdsw.proto.service.HistoryRequest
	9,  // 15: com.bdsw.proto.service.MessageService.searchMessages:input_type -> com.bdsw.proto.service.SearchRequest
	11, // 16: com.bdsw.proto.service.MessageService.getConversations:input_type -> com.bdsw.proto.service.ConversationRequest
	13, // 17: com.bdsw.proto.service.MessageService.clearConversation:input_type -> com.bdsw.proto.service.ClearConversationRequest
	1,  // 18: com.bdsw.proto.service.MessageService.sendMessage:output_type -> com.bdsw.proto.service.SendMessageResponse
	19, // 19: com.bdsw.proto.service.MessageService.deliverMessage:output_type -> com.bdsw.proto.common.Response
	19, // 20: com.bdsw.proto.service.MessageService.recallMessage:output_type -> com.bdsw.proto.common.Response
	19, // 21: com.bdsw.proto.service.MessageService.deleteMessage:output_type -> com.bdsw.proto.common.Response
	19, // 22: com.bdsw.proto.service.MessageService.markMessageRead:output_type -> com.bdsw.proto.common.Response
	14, // 23: com.bdsw.proto.service.MessageService.getMessage:output_type -> com.bdsw.proto.common.Message
	8,  // 24: com.bdsw.proto.service.MessageService.getHistoryMessages:output_type -> com.bdsw.proto.service.HistoryResponse
	10, // 25: com.bdsw.proto.service.MessageService.searchMessages:output_type -> com.bdsw.proto.service.SearchResponse
	12, // 26: com.bdsw.proto.service.MessageService.getConversations:output_type -> com.bdsw.proto.service.ConversationResponse
	19, // 27: com.bdsw.proto.service.MessageService.clearConversation:output_type -> com.bdsw.proto.common.Response
	18, // [18:28] is the sub-list for method output_type
	8,  // [8:18] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_proto_service_message_service_proto_init() }
func file_proto_service_message_service_proto_init() {
	if File_proto_service_message_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_service_message_service_proto_rawDesc), len(file_proto_service_message_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_service_message_service_proto_goTypes,
		DependencyIndexes: file_proto_service_message_service_proto_depIdxs,
		MessageInfos:      file_proto_service_message_service_proto_msgTypes,
	}.Build()
	File_proto_service_message_service_proto = out.File
	file_proto_service_message_service_proto_goTypes = nil
	file_proto_service_message_service_proto_depIdxs = nil
}
