// Code generated by protoc-gen-go-triple. DO NOT EDIT.
// versions:
// - protoc-gen-go-triple v1.0.8
// - protoc             v6.32.1
// source: proto/service/push_service.proto

package service

import (
	context "context"
	protocol "dubbo.apache.org/dubbo-go/v3/protocol"
	dubbo3 "dubbo.apache.org/dubbo-go/v3/protocol/dubbo3"
	invocation "dubbo.apache.org/dubbo-go/v3/protocol/invocation"
	common "github.com/bdsw/bdsw-im-ws/proto/common"
	grpc_go "github.com/dubbogo/grpc-go"
	codes "github.com/dubbogo/grpc-go/codes"
	metadata "github.com/dubbogo/grpc-go/metadata"
	status "github.com/dubbogo/grpc-go/status"
	common1 "github.com/dubbogo/triple/pkg/common"
	constant "github.com/dubbogo/triple/pkg/common/constant"
	triple "github.com/dubbogo/triple/pkg/triple"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc_go.SupportPackageIsVersion7

// PushServiceClient is the client API for PushService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PushServiceClient interface {
	// 单用户推送
	PushToUser(ctx context.Context, in *PushToUserRequest, opts ...grpc_go.CallOption) (*common.PushResponse, common1.ErrorWithAttachment)
	// 批量用户推送
	BatchPushToUsers(ctx context.Context, in *BatchPushToUsersRequest, opts ...grpc_go.CallOption) (*common.PushResponse, common1.ErrorWithAttachment)
	// 群组推送（如群聊消息）
	PushToGroup(ctx context.Context, in *PushToGroupRequest, opts ...grpc_go.CallOption) (*common.PushResponse, common1.ErrorWithAttachment)
	// 获取推送结果
	GetPushResult(ctx context.Context, in *GetPushResultRequest, opts ...grpc_go.CallOption) (*GetPushResultResponse, common1.ErrorWithAttachment)
	// 取消推送（针对可撤回消息）
	CancelPush(ctx context.Context, in *CancelPushRequest, opts ...grpc_go.CallOption) (*common.Response, common1.ErrorWithAttachment)
	// 广播消息
	PushBroadcast(ctx context.Context, in *common.PushBroadcastRequest, opts ...grpc_go.CallOption) (*common.PushResponse, common1.ErrorWithAttachment)
}

type pushServiceClient struct {
	cc *triple.TripleConn
}

type PushServiceClientImpl struct {
	PushToUser       func(ctx context.Context, in *PushToUserRequest) (*common.PushResponse, error)
	BatchPushToUsers func(ctx context.Context, in *BatchPushToUsersRequest) (*common.PushResponse, error)
	PushToGroup      func(ctx context.Context, in *PushToGroupRequest) (*common.PushResponse, error)
	GetPushResult    func(ctx context.Context, in *GetPushResultRequest) (*GetPushResultResponse, error)
	CancelPush       func(ctx context.Context, in *CancelPushRequest) (*common.Response, error)
	PushBroadcast    func(ctx context.Context, in *common.PushBroadcastRequest) (*common.PushResponse, error)
}

func (c *PushServiceClientImpl) GetDubboStub(cc *triple.TripleConn) PushServiceClient {
	return NewPushServiceClient(cc)
}

func (c *PushServiceClientImpl) XXX_InterfaceName() string {
	return "com.bdsw.proto.service.PushService"
}

func NewPushServiceClient(cc *triple.TripleConn) PushServiceClient {
	return &pushServiceClient{cc}
}

func (c *pushServiceClient) PushToUser(ctx context.Context, in *PushToUserRequest, opts ...grpc_go.CallOption) (*common.PushResponse, common1.ErrorWithAttachment) {
	out := new(common.PushResponse)
	interfaceKey := ctx.Value(constant.InterfaceKey).(string)
	return out, c.cc.Invoke(ctx, "/"+interfaceKey+"/PushToUser", in, out)
}

func (c *pushServiceClient) BatchPushToUsers(ctx context.Context, in *BatchPushToUsersRequest, opts ...grpc_go.CallOption) (*common.PushResponse, common1.ErrorWithAttachment) {
	out := new(common.PushResponse)
	interfaceKey := ctx.Value(constant.InterfaceKey).(string)
	return out, c.cc.Invoke(ctx, "/"+interfaceKey+"/BatchPushToUsers", in, out)
}

func (c *pushServiceClient) PushToGroup(ctx context.Context, in *PushToGroupRequest, opts ...grpc_go.CallOption) (*common.PushResponse, common1.ErrorWithAttachment) {
	out := new(common.PushResponse)
	interfaceKey := ctx.Value(constant.InterfaceKey).(string)
	return out, c.cc.Invoke(ctx, "/"+interfaceKey+"/PushToGroup", in, out)
}

func (c *pushServiceClient) GetPushResult(ctx context.Context, in *GetPushResultRequest, opts ...grpc_go.CallOption) (*GetPushResultResponse, common1.ErrorWithAttachment) {
	out := new(GetPushResultResponse)
	interfaceKey := ctx.Value(constant.InterfaceKey).(string)
	return out, c.cc.Invoke(ctx, "/"+interfaceKey+"/GetPushResult", in, out)
}

func (c *pushServiceClient) CancelPush(ctx context.Context, in *CancelPushRequest, opts ...grpc_go.CallOption) (*common.Response, common1.ErrorWithAttachment) {
	out := new(common.Response)
	interfaceKey := ctx.Value(constant.InterfaceKey).(string)
	return out, c.cc.Invoke(ctx, "/"+interfaceKey+"/CancelPush", in, out)
}

func (c *pushServiceClient) PushBroadcast(ctx context.Context, in *common.PushBroadcastRequest, opts ...grpc_go.CallOption) (*common.PushResponse, common1.ErrorWithAttachment) {
	out := new(common.PushResponse)
	interfaceKey := ctx.Value(constant.InterfaceKey).(string)
	return out, c.cc.Invoke(ctx, "/"+interfaceKey+"/PushBroadcast", in, out)
}

// PushServiceServer is the server API for PushService service.
// All implementations must embed UnimplementedPushServiceServer
// for forward compatibility
type PushServiceServer interface {
	// 单用户推送
	PushToUser(context.Context, *PushToUserRequest) (*common.PushResponse, error)
	// 批量用户推送
	BatchPushToUsers(context.Context, *BatchPushToUsersRequest) (*common.PushResponse, error)
	// 群组推送（如群聊消息）
	PushToGroup(context.Context, *PushToGroupRequest) (*common.PushResponse, error)
	// 获取推送结果
	GetPushResult(context.Context, *GetPushResultRequest) (*GetPushResultResponse, error)
	// 取消推送（针对可撤回消息）
	CancelPush(context.Context, *CancelPushRequest) (*common.Response, error)
	// 广播消息
	PushBroadcast(context.Context, *common.PushBroadcastRequest) (*common.PushResponse, error)
	mustEmbedUnimplementedPushServiceServer()
}

// UnimplementedPushServiceServer must be embedded to have forward compatible implementations.
type UnimplementedPushServiceServer struct {
	proxyImpl protocol.Invoker
}

func (UnimplementedPushServiceServer) PushToUser(context.Context, *PushToUserRequest) (*common.PushResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PushToUser not implemented")
}
func (UnimplementedPushServiceServer) BatchPushToUsers(context.Context, *BatchPushToUsersRequest) (*common.PushResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BatchPushToUsers not implemented")
}
func (UnimplementedPushServiceServer) PushToGroup(context.Context, *PushToGroupRequest) (*common.PushResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PushToGroup not implemented")
}
func (UnimplementedPushServiceServer) GetPushResult(context.Context, *GetPushResultRequest) (*GetPushResultResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPushResult not implemented")
}
func (UnimplementedPushServiceServer) CancelPush(context.Context, *CancelPushRequest) (*common.Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelPush not implemented")
}
func (UnimplementedPushServiceServer) PushBroadcast(context.Context, *common.PushBroadcastRequest) (*common.PushResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PushBroadcast not implemented")
}
func (s *UnimplementedPushServiceServer) XXX_SetProxyImpl(impl protocol.Invoker) {
	s.proxyImpl = impl
}

func (s *UnimplementedPushServiceServer) XXX_GetProxyImpl() protocol.Invoker {
	return s.proxyImpl
}

func (s *UnimplementedPushServiceServer) XXX_ServiceDesc() *grpc_go.ServiceDesc {
	return &PushService_ServiceDesc
}
func (s *UnimplementedPushServiceServer) XXX_InterfaceName() string {
	return "com.bdsw.proto.service.PushService"
}

func (UnimplementedPushServiceServer) mustEmbedUnimplementedPushServiceServer() {}

// UnsafePushServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PushServiceServer will
// result in compilation errors.
type UnsafePushServiceServer interface {
	mustEmbedUnimplementedPushServiceServer()
}

func RegisterPushServiceServer(s grpc_go.ServiceRegistrar, srv PushServiceServer) {
	s.RegisterService(&PushService_ServiceDesc, srv)
}

func _PushService_PushToUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc_go.UnaryServerInterceptor) (interface{}, error) {
	in := new(PushToUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	base := srv.(dubbo3.Dubbo3GrpcService)
	args := []interface{}{}
	args = append(args, in)
	md, _ := metadata.FromIncomingContext(ctx)
	invAttachment := make(map[string]interface{}, len(md))
	for k, v := range md {
		invAttachment[k] = v
	}
	invo := invocation.NewRPCInvocation("PushToUser", args, invAttachment)
	if interceptor == nil {
		result := base.XXX_GetProxyImpl().Invoke(ctx, invo)
		return result, result.Error()
	}
	info := &grpc_go.UnaryServerInfo{
		Server:     srv,
		FullMethod: ctx.Value("XXX_TRIPLE_GO_INTERFACE_NAME").(string),
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		result := base.XXX_GetProxyImpl().Invoke(ctx, invo)
		return result, result.Error()
	}
	return interceptor(ctx, in, info, handler)
}

func _PushService_BatchPushToUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc_go.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchPushToUsersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	base := srv.(dubbo3.Dubbo3GrpcService)
	args := []interface{}{}
	args = append(args, in)
	md, _ := metadata.FromIncomingContext(ctx)
	invAttachment := make(map[string]interface{}, len(md))
	for k, v := range md {
		invAttachment[k] = v
	}
	invo := invocation.NewRPCInvocation("BatchPushToUsers", args, invAttachment)
	if interceptor == nil {
		result := base.XXX_GetProxyImpl().Invoke(ctx, invo)
		return result, result.Error()
	}
	info := &grpc_go.UnaryServerInfo{
		Server:     srv,
		FullMethod: ctx.Value("XXX_TRIPLE_GO_INTERFACE_NAME").(string),
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		result := base.XXX_GetProxyImpl().Invoke(ctx, invo)
		return result, result.Error()
	}
	return interceptor(ctx, in, info, handler)
}

func _PushService_PushToGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc_go.UnaryServerInterceptor) (interface{}, error) {
	in := new(PushToGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	base := srv.(dubbo3.Dubbo3GrpcService)
	args := []interface{}{}
	args = append(args, in)
	md, _ := metadata.FromIncomingContext(ctx)
	invAttachment := make(map[string]interface{}, len(md))
	for k, v := range md {
		invAttachment[k] = v
	}
	invo := invocation.NewRPCInvocation("PushToGroup", args, invAttachment)
	if interceptor == nil {
		result := base.XXX_GetProxyImpl().Invoke(ctx, invo)
		return result, result.Error()
	}
	info := &grpc_go.UnaryServerInfo{
		Server:     srv,
		FullMethod: ctx.Value("XXX_TRIPLE_GO_INTERFACE_NAME").(string),
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		result := base.XXX_GetProxyImpl().Invoke(ctx, invo)
		return result, result.Error()
	}
	return interceptor(ctx, in, info, handler)
}

func _PushService_GetPushResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc_go.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPushResultRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	base := srv.(dubbo3.Dubbo3GrpcService)
	args := []interface{}{}
	args = append(args, in)
	md, _ := metadata.FromIncomingContext(ctx)
	invAttachment := make(map[string]interface{}, len(md))
	for k, v := range md {
		invAttachment[k] = v
	}
	invo := invocation.NewRPCInvocation("GetPushResult", args, invAttachment)
	if interceptor == nil {
		result := base.XXX_GetProxyImpl().Invoke(ctx, invo)
		return result, result.Error()
	}
	info := &grpc_go.UnaryServerInfo{
		Server:     srv,
		FullMethod: ctx.Value("XXX_TRIPLE_GO_INTERFACE_NAME").(string),
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		result := base.XXX_GetProxyImpl().Invoke(ctx, invo)
		return result, result.Error()
	}
	return interceptor(ctx, in, info, handler)
}

func _PushService_CancelPush_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc_go.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelPushRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	base := srv.(dubbo3.Dubbo3GrpcService)
	args := []interface{}{}
	args = append(args, in)
	md, _ := metadata.FromIncomingContext(ctx)
	invAttachment := make(map[string]interface{}, len(md))
	for k, v := range md {
		invAttachment[k] = v
	}
	invo := invocation.NewRPCInvocation("CancelPush", args, invAttachment)
	if interceptor == nil {
		result := base.XXX_GetProxyImpl().Invoke(ctx, invo)
		return result, result.Error()
	}
	info := &grpc_go.UnaryServerInfo{
		Server:     srv,
		FullMethod: ctx.Value("XXX_TRIPLE_GO_INTERFACE_NAME").(string),
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		result := base.XXX_GetProxyImpl().Invoke(ctx, invo)
		return result, result.Error()
	}
	return interceptor(ctx, in, info, handler)
}

func _PushService_PushBroadcast_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc_go.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.PushBroadcastRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	base := srv.(dubbo3.Dubbo3GrpcService)
	args := []interface{}{}
	args = append(args, in)
	md, _ := metadata.FromIncomingContext(ctx)
	invAttachment := make(map[string]interface{}, len(md))
	for k, v := range md {
		invAttachment[k] = v
	}
	invo := invocation.NewRPCInvocation("PushBroadcast", args, invAttachment)
	if interceptor == nil {
		result := base.XXX_GetProxyImpl().Invoke(ctx, invo)
		return result, result.Error()
	}
	info := &grpc_go.UnaryServerInfo{
		Server:     srv,
		FullMethod: ctx.Value("XXX_TRIPLE_GO_INTERFACE_NAME").(string),
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		result := base.XXX_GetProxyImpl().Invoke(ctx, invo)
		return result, result.Error()
	}
	return interceptor(ctx, in, info, handler)
}

// PushService_ServiceDesc is the grpc_go.ServiceDesc for PushService service.
// It's only intended for direct use with grpc_go.RegisterService,
// and not to be introspected or modified (even as a copy)
var PushService_ServiceDesc = grpc_go.ServiceDesc{
	ServiceName: "com.bdsw.proto.service.PushService",
	HandlerType: (*PushServiceServer)(nil),
	Methods: []grpc_go.MethodDesc{
		{
			MethodName: "pushToUser",
			Handler:    _PushService_PushToUser_Handler,
		},
		{
			MethodName: "batchPushToUsers",
			Handler:    _PushService_BatchPushToUsers_Handler,
		},
		{
			MethodName: "pushToGroup",
			Handler:    _PushService_PushToGroup_Handler,
		},
		{
			MethodName: "getPushResult",
			Handler:    _PushService_GetPushResult_Handler,
		},
		{
			MethodName: "cancelPush",
			Handler:    _PushService_CancelPush_Handler,
		},
		{
			MethodName: "PushBroadcast",
			Handler:    _PushService_PushBroadcast_Handler,
		},
	},
	Streams:  []grpc_go.StreamDesc{},
	Metadata: "proto/service/push_service.proto",
}
