// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: proto/service/sync_service.proto

// Java 包的命名空间

package service

import (
	common "github.com/bdsw/bdsw-im-ws/proto/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SyncRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	UserId           string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DeviceId         string                 `protobuf:"bytes,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	LastSyncTime     int64                  `protobuf:"varint,3,opt,name=last_sync_time,json=lastSyncTime,proto3" json:"last_sync_time,omitempty"`
	ConversationSeqs map[string]int64       `protobuf:"bytes,4,rep,name=conversation_seqs,json=conversationSeqs,proto3" json:"conversation_seqs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"` // 各会话最后同步的序列号
	Limit            int32                  `protobuf:"varint,5,opt,name=limit,proto3" json:"limit,omitempty"`
	PullOffline      bool                   `protobuf:"varint,6,opt,name=pull_offline,json=pullOffline,proto3" json:"pull_offline,omitempty"` // 是否拉取离线消息
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SyncRequest) Reset() {
	*x = SyncRequest{}
	mi := &file_proto_service_sync_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncRequest) ProtoMessage() {}

func (x *SyncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_sync_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncRequest.ProtoReflect.Descriptor instead.
func (*SyncRequest) Descriptor() ([]byte, []int) {
	return file_proto_service_sync_service_proto_rawDescGZIP(), []int{0}
}

func (x *SyncRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SyncRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *SyncRequest) GetLastSyncTime() int64 {
	if x != nil {
		return x.LastSyncTime
	}
	return 0
}

func (x *SyncRequest) GetConversationSeqs() map[string]int64 {
	if x != nil {
		return x.ConversationSeqs
	}
	return nil
}

func (x *SyncRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *SyncRequest) GetPullOffline() bool {
	if x != nil {
		return x.PullOffline
	}
	return false
}

type SyncResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Messages         []*common.Message      `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	LatestTime       int64                  `protobuf:"varint,2,opt,name=latest_time,json=latestTime,proto3" json:"latest_time,omitempty"`
	HasMore          bool                   `protobuf:"varint,3,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	LatestSeqs       map[string]int64       `protobuf:"bytes,4,rep,name=latest_seqs,json=latestSeqs,proto3" json:"latest_seqs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"` // 各会话最新的序列号
	NextPullInterval int64                  `protobuf:"varint,5,opt,name=next_pull_interval,json=nextPullInterval,proto3" json:"next_pull_interval,omitempty"`                                                       // 下次拉取间隔（毫秒）
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SyncResponse) Reset() {
	*x = SyncResponse{}
	mi := &file_proto_service_sync_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncResponse) ProtoMessage() {}

func (x *SyncResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_sync_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncResponse.ProtoReflect.Descriptor instead.
func (*SyncResponse) Descriptor() ([]byte, []int) {
	return file_proto_service_sync_service_proto_rawDescGZIP(), []int{1}
}

func (x *SyncResponse) GetMessages() []*common.Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *SyncResponse) GetLatestTime() int64 {
	if x != nil {
		return x.LatestTime
	}
	return 0
}

func (x *SyncResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

func (x *SyncResponse) GetLatestSeqs() map[string]int64 {
	if x != nil {
		return x.LatestSeqs
	}
	return nil
}

func (x *SyncResponse) GetNextPullInterval() int64 {
	if x != nil {
		return x.NextPullInterval
	}
	return 0
}

type UnreadRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	UserId          string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ConversationIds []string               `protobuf:"bytes,2,rep,name=conversation_ids,json=conversationIds,proto3" json:"conversation_ids,omitempty"` // 为空则获取所有会话
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UnreadRequest) Reset() {
	*x = UnreadRequest{}
	mi := &file_proto_service_sync_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnreadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnreadRequest) ProtoMessage() {}

func (x *UnreadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_sync_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnreadRequest.ProtoReflect.Descriptor instead.
func (*UnreadRequest) Descriptor() ([]byte, []int) {
	return file_proto_service_sync_service_proto_rawDescGZIP(), []int{2}
}

func (x *UnreadRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UnreadRequest) GetConversationIds() []string {
	if x != nil {
		return x.ConversationIds
	}
	return nil
}

type UnreadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UnreadCounts  map[string]int32       `protobuf:"bytes,1,rep,name=unread_counts,json=unreadCounts,proto3" json:"unread_counts,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"` // key:conversation_id, value:unread_count
	TotalUnread   int64                  `protobuf:"varint,2,opt,name=total_unread,json=totalUnread,proto3" json:"total_unread,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnreadResponse) Reset() {
	*x = UnreadResponse{}
	mi := &file_proto_service_sync_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnreadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnreadResponse) ProtoMessage() {}

func (x *UnreadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_sync_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnreadResponse.ProtoReflect.Descriptor instead.
func (*UnreadResponse) Descriptor() ([]byte, []int) {
	return file_proto_service_sync_service_proto_rawDescGZIP(), []int{3}
}

func (x *UnreadResponse) GetUnreadCounts() map[string]int32 {
	if x != nil {
		return x.UnreadCounts
	}
	return nil
}

func (x *UnreadResponse) GetTotalUnread() int64 {
	if x != nil {
		return x.TotalUnread
	}
	return 0
}

type ConversationSyncRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	LastUpdateTime int64                  `protobuf:"varint,2,opt,name=last_update_time,json=lastUpdateTime,proto3" json:"last_update_time,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ConversationSyncRequest) Reset() {
	*x = ConversationSyncRequest{}
	mi := &file_proto_service_sync_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConversationSyncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConversationSyncRequest) ProtoMessage() {}

func (x *ConversationSyncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_sync_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConversationSyncRequest.ProtoReflect.Descriptor instead.
func (*ConversationSyncRequest) Descriptor() ([]byte, []int) {
	return file_proto_service_sync_service_proto_rawDescGZIP(), []int{4}
}

func (x *ConversationSyncRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ConversationSyncRequest) GetLastUpdateTime() int64 {
	if x != nil {
		return x.LastUpdateTime
	}
	return 0
}

type ConversationSyncResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Conversations []*common.Conversation `protobuf:"bytes,1,rep,name=conversations,proto3" json:"conversations,omitempty"`
	ServerTime    int64                  `protobuf:"varint,2,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"`
	HasChange     bool                   `protobuf:"varint,3,opt,name=has_change,json=hasChange,proto3" json:"has_change,omitempty"` // 是否有变更
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConversationSyncResponse) Reset() {
	*x = ConversationSyncResponse{}
	mi := &file_proto_service_sync_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConversationSyncResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConversationSyncResponse) ProtoMessage() {}

func (x *ConversationSyncResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_sync_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConversationSyncResponse.ProtoReflect.Descriptor instead.
func (*ConversationSyncResponse) Descriptor() ([]byte, []int) {
	return file_proto_service_sync_service_proto_rawDescGZIP(), []int{5}
}

func (x *ConversationSyncResponse) GetConversations() []*common.Conversation {
	if x != nil {
		return x.Conversations
	}
	return nil
}

func (x *ConversationSyncResponse) GetServerTime() int64 {
	if x != nil {
		return x.ServerTime
	}
	return 0
}

func (x *ConversationSyncResponse) GetHasChange() bool {
	if x != nil {
		return x.HasChange
	}
	return false
}

type GetSeqRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ConversationId string                 `protobuf:"bytes,2,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetSeqRequest) Reset() {
	*x = GetSeqRequest{}
	mi := &file_proto_service_sync_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSeqRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSeqRequest) ProtoMessage() {}

func (x *GetSeqRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_sync_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSeqRequest.ProtoReflect.Descriptor instead.
func (*GetSeqRequest) Descriptor() ([]byte, []int) {
	return file_proto_service_sync_service_proto_rawDescGZIP(), []int{6}
}

func (x *GetSeqRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetSeqRequest) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

type GetSeqResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seq           int64                  `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`
	ConvSeq       int64                  `protobuf:"varint,2,opt,name=conv_seq,json=convSeq,proto3" json:"conv_seq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSeqResponse) Reset() {
	*x = GetSeqResponse{}
	mi := &file_proto_service_sync_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSeqResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSeqResponse) ProtoMessage() {}

func (x *GetSeqResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_sync_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSeqResponse.ProtoReflect.Descriptor instead.
func (*GetSeqResponse) Descriptor() ([]byte, []int) {
	return file_proto_service_sync_service_proto_rawDescGZIP(), []int{7}
}

func (x *GetSeqResponse) GetSeq() int64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *GetSeqResponse) GetConvSeq() int64 {
	if x != nil {
		return x.ConvSeq
	}
	return 0
}

type GroupSyncRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	LastSyncTime  int64                  `protobuf:"varint,2,opt,name=last_sync_time,json=lastSyncTime,proto3" json:"last_sync_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupSyncRequest) Reset() {
	*x = GroupSyncRequest{}
	mi := &file_proto_service_sync_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupSyncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupSyncRequest) ProtoMessage() {}

func (x *GroupSyncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_sync_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupSyncRequest.ProtoReflect.Descriptor instead.
func (*GroupSyncRequest) Descriptor() ([]byte, []int) {
	return file_proto_service_sync_service_proto_rawDescGZIP(), []int{8}
}

func (x *GroupSyncRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GroupSyncRequest) GetLastSyncTime() int64 {
	if x != nil {
		return x.LastSyncTime
	}
	return 0
}

type GroupSyncResponse struct {
	state         protoimpl.MessageState         `protogen:"open.v1"`
	Groups        []*common.Group                `protobuf:"bytes,1,rep,name=groups,proto3" json:"groups,omitempty"`
	Memberships   map[string]*common.GroupMember `protobuf:"bytes,2,rep,name=memberships,proto3" json:"memberships,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 用户在群中的成员信息
	ServerTime    int64                          `protobuf:"varint,3,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupSyncResponse) Reset() {
	*x = GroupSyncResponse{}
	mi := &file_proto_service_sync_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupSyncResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupSyncResponse) ProtoMessage() {}

func (x *GroupSyncResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_sync_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupSyncResponse.ProtoReflect.Descriptor instead.
func (*GroupSyncResponse) Descriptor() ([]byte, []int) {
	return file_proto_service_sync_service_proto_rawDescGZIP(), []int{9}
}

func (x *GroupSyncResponse) GetGroups() []*common.Group {
	if x != nil {
		return x.Groups
	}
	return nil
}

func (x *GroupSyncResponse) GetMemberships() map[string]*common.GroupMember {
	if x != nil {
		return x.Memberships
	}
	return nil
}

func (x *GroupSyncResponse) GetServerTime() int64 {
	if x != nil {
		return x.ServerTime
	}
	return 0
}

type FriendSyncRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	LastSyncTime  int64                  `protobuf:"varint,2,opt,name=last_sync_time,json=lastSyncTime,proto3" json:"last_sync_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FriendSyncRequest) Reset() {
	*x = FriendSyncRequest{}
	mi := &file_proto_service_sync_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FriendSyncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendSyncRequest) ProtoMessage() {}

func (x *FriendSyncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_sync_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendSyncRequest.ProtoReflect.Descriptor instead.
func (*FriendSyncRequest) Descriptor() ([]byte, []int) {
	return file_proto_service_sync_service_proto_rawDescGZIP(), []int{10}
}

func (x *FriendSyncRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *FriendSyncRequest) GetLastSyncTime() int64 {
	if x != nil {
		return x.LastSyncTime
	}
	return 0
}

type FriendSyncResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Friends       []*common.Friend       `protobuf:"bytes,1,rep,name=friends,proto3" json:"friends,omitempty"`
	Applies       []*common.FriendApply  `protobuf:"bytes,2,rep,name=applies,proto3" json:"applies,omitempty"` // 好友申请
	ServerTime    int64                  `protobuf:"varint,3,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FriendSyncResponse) Reset() {
	*x = FriendSyncResponse{}
	mi := &file_proto_service_sync_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FriendSyncResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendSyncResponse) ProtoMessage() {}

func (x *FriendSyncResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_sync_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendSyncResponse.ProtoReflect.Descriptor instead.
func (*FriendSyncResponse) Descriptor() ([]byte, []int) {
	return file_proto_service_sync_service_proto_rawDescGZIP(), []int{11}
}

func (x *FriendSyncResponse) GetFriends() []*common.Friend {
	if x != nil {
		return x.Friends
	}
	return nil
}

func (x *FriendSyncResponse) GetApplies() []*common.FriendApply {
	if x != nil {
		return x.Applies
	}
	return nil
}

func (x *FriendSyncResponse) GetServerTime() int64 {
	if x != nil {
		return x.ServerTime
	}
	return 0
}

type FullSyncRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DeviceId      string                 `protobuf:"bytes,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	SyncTime      int64                  `protobuf:"varint,3,opt,name=sync_time,json=syncTime,proto3" json:"sync_time,omitempty"` // 客户端当前时间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FullSyncRequest) Reset() {
	*x = FullSyncRequest{}
	mi := &file_proto_service_sync_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FullSyncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FullSyncRequest) ProtoMessage() {}

func (x *FullSyncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_sync_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FullSyncRequest.ProtoReflect.Descriptor instead.
func (*FullSyncRequest) Descriptor() ([]byte, []int) {
	return file_proto_service_sync_service_proto_rawDescGZIP(), []int{12}
}

func (x *FullSyncRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *FullSyncRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *FullSyncRequest) GetSyncTime() int64 {
	if x != nil {
		return x.SyncTime
	}
	return 0
}

type FullSyncResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 用户信息
	UserInfo *common.User `protobuf:"bytes,1,opt,name=user_info,json=userInfo,proto3" json:"user_info,omitempty"`
	// 所有会话
	Conversations []*common.Conversation `protobuf:"bytes,2,rep,name=conversations,proto3" json:"conversations,omitempty"`
	// 所有群组
	Groups []*common.Group `protobuf:"bytes,3,rep,name=groups,proto3" json:"groups,omitempty"`
	// 所有好友
	Friends []*common.Friend `protobuf:"bytes,4,rep,name=friends,proto3" json:"friends,omitempty"`
	// 系统时间
	ServerTime int64 `protobuf:"varint,5,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"`
	// 同步完成标记
	SyncCompleted bool `protobuf:"varint,6,opt,name=sync_completed,json=syncCompleted,proto3" json:"sync_completed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FullSyncResponse) Reset() {
	*x = FullSyncResponse{}
	mi := &file_proto_service_sync_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FullSyncResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FullSyncResponse) ProtoMessage() {}

func (x *FullSyncResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_sync_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FullSyncResponse.ProtoReflect.Descriptor instead.
func (*FullSyncResponse) Descriptor() ([]byte, []int) {
	return file_proto_service_sync_service_proto_rawDescGZIP(), []int{13}
}

func (x *FullSyncResponse) GetUserInfo() *common.User {
	if x != nil {
		return x.UserInfo
	}
	return nil
}

func (x *FullSyncResponse) GetConversations() []*common.Conversation {
	if x != nil {
		return x.Conversations
	}
	return nil
}

func (x *FullSyncResponse) GetGroups() []*common.Group {
	if x != nil {
		return x.Groups
	}
	return nil
}

func (x *FullSyncResponse) GetFriends() []*common.Friend {
	if x != nil {
		return x.Friends
	}
	return nil
}

func (x *FullSyncResponse) GetServerTime() int64 {
	if x != nil {
		return x.ServerTime
	}
	return 0
}

func (x *FullSyncResponse) GetSyncCompleted() bool {
	if x != nil {
		return x.SyncCompleted
	}
	return false
}

var File_proto_service_sync_service_proto protoreflect.FileDescriptor

const file_proto_service_sync_service_proto_rawDesc = "" +
	"\n" +
	" proto/service/sync_service.proto\x12\x16com.bdsw.proto.service\x1a\x1aproto/common/message.proto\x1a\x17proto/common/user.proto\x1a\x18proto/common/group.proto\"\xcf\x02\n" +
	"\vSyncRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tdevice_id\x18\x02 \x01(\tR\bdeviceId\x12$\n" +
	"\x0elast_sync_time\x18\x03 \x01(\x03R\flastSyncTime\x12f\n" +
	"\x11conversation_seqs\x18\x04 \x03(\v29.com.bdsw.proto.service.SyncRequest.ConversationSeqsEntryR\x10conversationSeqs\x12\x14\n" +
	"\x05limit\x18\x05 \x01(\x05R\x05limit\x12!\n" +
	"\fpull_offline\x18\x06 \x01(\bR\vpullOffline\x1aC\n" +
	"\x15ConversationSeqsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\"\xca\x02\n" +
	"\fSyncResponse\x12:\n" +
	"\bmessages\x18\x01 \x03(\v2\x1e.com.bdsw.proto.common.MessageR\bmessages\x12\x1f\n" +
	"\vlatest_time\x18\x02 \x01(\x03R\n" +
	"latestTime\x12\x19\n" +
	"\bhas_more\x18\x03 \x01(\bR\ahasMore\x12U\n" +
	"\vlatest_seqs\x18\x04 \x03(\v24.com.bdsw.proto.service.SyncResponse.LatestSeqsEntryR\n" +
	"latestSeqs\x12,\n" +
	"\x12next_pull_interval\x18\x05 \x01(\x03R\x10nextPullInterval\x1a=\n" +
	"\x0fLatestSeqsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\"S\n" +
	"\rUnreadRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12)\n" +
	"\x10conversation_ids\x18\x02 \x03(\tR\x0fconversationIds\"\xd3\x01\n" +
	"\x0eUnreadResponse\x12]\n" +
	"\runread_counts\x18\x01 \x03(\v28.com.bdsw.proto.service.UnreadResponse.UnreadCountsEntryR\funreadCounts\x12!\n" +
	"\ftotal_unread\x18\x02 \x01(\x03R\vtotalUnread\x1a?\n" +
	"\x11UnreadCountsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\"\\\n" +
	"\x17ConversationSyncRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12(\n" +
	"\x10last_update_time\x18\x02 \x01(\x03R\x0elastUpdateTime\"\xa5\x01\n" +
	"\x18ConversationSyncResponse\x12I\n" +
	"\rconversations\x18\x01 \x03(\v2#.com.bdsw.proto.common.ConversationR\rconversations\x12\x1f\n" +
	"\vserver_time\x18\x02 \x01(\x03R\n" +
	"serverTime\x12\x1d\n" +
	"\n" +
	"has_change\x18\x03 \x01(\bR\thasChange\"Q\n" +
	"\rGetSeqRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12'\n" +
	"\x0fconversation_id\x18\x02 \x01(\tR\x0econversationId\"=\n" +
	"\x0eGetSeqResponse\x12\x10\n" +
	"\x03seq\x18\x01 \x01(\x03R\x03seq\x12\x19\n" +
	"\bconv_seq\x18\x02 \x01(\x03R\aconvSeq\"Q\n" +
	"\x10GroupSyncRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12$\n" +
	"\x0elast_sync_time\x18\x02 \x01(\x03R\flastSyncTime\"\xac\x02\n" +
	"\x11GroupSyncResponse\x124\n" +
	"\x06groups\x18\x01 \x03(\v2\x1c.com.bdsw.proto.common.GroupR\x06groups\x12\\\n" +
	"\vmemberships\x18\x02 \x03(\v2:.com.bdsw.proto.service.GroupSyncResponse.MembershipsEntryR\vmemberships\x12\x1f\n" +
	"\vserver_time\x18\x03 \x01(\x03R\n" +
	"serverTime\x1ab\n" +
	"\x10MembershipsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x128\n" +
	"\x05value\x18\x02 \x01(\v2\".com.bdsw.proto.common.GroupMemberR\x05value:\x028\x01\"R\n" +
	"\x11FriendSyncRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12$\n" +
	"\x0elast_sync_time\x18\x02 \x01(\x03R\flastSyncTime\"\xac\x01\n" +
	"\x12FriendSyncResponse\x127\n" +
	"\afriends\x18\x01 \x03(\v2\x1d.com.bdsw.proto.common.FriendR\afriends\x12<\n" +
	"\aapplies\x18\x02 \x03(\v2\".com.bdsw.proto.common.FriendApplyR\aapplies\x12\x1f\n" +
	"\vserver_time\x18\x03 \x01(\x03R\n" +
	"serverTime\"d\n" +
	"\x0fFullSyncRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tdevice_id\x18\x02 \x01(\tR\bdeviceId\x12\x1b\n" +
	"\tsync_time\x18\x03 \x01(\x03R\bsyncTime\"\xce\x02\n" +
	"\x10FullSyncResponse\x128\n" +
	"\tuser_info\x18\x01 \x01(\v2\x1b.com.bdsw.proto.common.UserR\buserInfo\x12I\n" +
	"\rconversations\x18\x02 \x03(\v2#.com.bdsw.proto.common.ConversationR\rconversations\x124\n" +
	"\x06groups\x18\x03 \x03(\v2\x1c.com.bdsw.proto.common.GroupR\x06groups\x127\n" +
	"\afriends\x18\x04 \x03(\v2\x1d.com.bdsw.proto.common.FriendR\afriends\x12\x1f\n" +
	"\vserver_time\x18\x05 \x01(\x03R\n" +
	"serverTime\x12%\n" +
	"\x0esync_completed\x18\x06 \x01(\bR\rsyncCompleted2\xca\x05\n" +
	"\vSyncService\x12Y\n" +
	"\fsyncMessages\x12#.com.bdsw.proto.service.SyncRequest\x1a$.com.bdsw.proto.service.SyncResponse\x12`\n" +
	"\x0fgetUnreadCounts\x12%.com.bdsw.proto.service.UnreadRequest\x1a&.com.bdsw.proto.service.UnreadResponse\x12v\n" +
	"\x11syncConversations\x12/.com.bdsw.proto.service.ConversationSyncRequest\x1a0.com.bdsw.proto.service.ConversationSyncResponse\x12^\n" +
	"\rgetMessageSeq\x12%.com.bdsw.proto.service.GetSeqRequest\x1a&.com.bdsw.proto.service.GetSeqResponse\x12a\n" +
	"\n" +
	"syncGroups\x12(.com.bdsw.proto.service.GroupSyncRequest\x1a).com.bdsw.proto.service.GroupSyncResponse\x12d\n" +
	"\vsyncFriends\x12).com.bdsw.proto.service.FriendSyncRequest\x1a*.com.bdsw.proto.service.FriendSyncResponse\x12]\n" +
	"\bfullSync\x12'.com.bdsw.proto.service.FullSyncRequest\x1a(.com.bdsw.proto.service.FullSyncResponseB^\n" +
	"\x16com.bdsw.proto.serviceB\x10SyncServiceProtoP\x01Z0github.com/bdsw/bdsw-im-ws/proto/service;serviceb\x06proto3"

var (
	file_proto_service_sync_service_proto_rawDescOnce sync.Once
	file_proto_service_sync_service_proto_rawDescData []byte
)

func file_proto_service_sync_service_proto_rawDescGZIP() []byte {
	file_proto_service_sync_service_proto_rawDescOnce.Do(func() {
		file_proto_service_sync_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_service_sync_service_proto_rawDesc), len(file_proto_service_sync_service_proto_rawDesc)))
	})
	return file_proto_service_sync_service_proto_rawDescData
}

var file_proto_service_sync_service_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_proto_service_sync_service_proto_goTypes = []any{
	(*SyncRequest)(nil),              // 0: com.bdsw.proto.service.SyncRequest
	(*SyncResponse)(nil),             // 1: com.bdsw.proto.service.SyncResponse
	(*UnreadRequest)(nil),            // 2: com.bdsw.proto.service.UnreadRequest
	(*UnreadResponse)(nil),           // 3: com.bdsw.proto.service.UnreadResponse
	(*ConversationSyncRequest)(nil),  // 4: com.bdsw.proto.service.ConversationSyncRequest
	(*ConversationSyncResponse)(nil), // 5: com.bdsw.proto.service.ConversationSyncResponse
	(*GetSeqRequest)(nil),            // 6: com.bdsw.proto.service.GetSeqRequest
	(*GetSeqResponse)(nil),           // 7: com.bdsw.proto.service.GetSeqResponse
	(*GroupSyncRequest)(nil),         // 8: com.bdsw.proto.service.GroupSyncRequest
	(*GroupSyncResponse)(nil),        // 9: com.bdsw.proto.service.GroupSyncResponse
	(*FriendSyncRequest)(nil),        // 10: com.bdsw.proto.service.FriendSyncRequest
	(*FriendSyncResponse)(nil),       // 11: com.bdsw.proto.service.FriendSyncResponse
	(*FullSyncRequest)(nil),          // 12: com.bdsw.proto.service.FullSyncRequest
	(*FullSyncResponse)(nil),         // 13: com.bdsw.proto.service.FullSyncResponse
	nil,                              // 14: com.bdsw.proto.service.SyncRequest.ConversationSeqsEntry
	nil,                              // 15: com.bdsw.proto.service.SyncResponse.LatestSeqsEntry
	nil,                              // 16: com.bdsw.proto.service.UnreadResponse.UnreadCountsEntry
	nil,                              // 17: com.bdsw.proto.service.GroupSyncResponse.MembershipsEntry
	(*common.Message)(nil),           // 18: com.bdsw.proto.common.Message
	(*common.Conversation)(nil),      // 19: com.bdsw.proto.common.Conversation
	(*common.Group)(nil),             // 20: com.bdsw.proto.common.Group
	(*common.Friend)(nil),            // 21: com.bdsw.proto.common.Friend
	(*common.FriendApply)(nil),       // 22: com.bdsw.proto.common.FriendApply
	(*common.User)(nil),              // 23: com.bdsw.proto.common.User
	(*common.GroupMember)(nil),       // 24: com.bdsw.proto.common.GroupMember
}
var file_proto_service_sync_service_proto_depIdxs = []int32{
	14, // 0: com.bdsw.proto.service.SyncRequest.conversation_seqs:type_name -> com.bdsw.proto.service.SyncRequest.ConversationSeqsEntry
	18, // 1: com.bdsw.proto.service.SyncResponse.messages:type_name -> com.bdsw.proto.common.Message
	15, // 2: com.bdsw.proto.service.SyncResponse.latest_seqs:type_name -> com.bdsw.proto.service.SyncResponse.LatestSeqsEntry
	16, // 3: com.bdsw.proto.service.UnreadResponse.unread_counts:type_name -> com.bdsw.proto.service.UnreadResponse.UnreadCountsEntry
	19, // 4: com.bdsw.proto.service.ConversationSyncResponse.conversations:type_name -> com.bdsw.proto.common.Conversation
	20, // 5: com.bdsw.proto.service.GroupSyncResponse.groups:type_name -> com.bdsw.proto.common.Group
	17, // 6: com.bdsw.proto.service.GroupSyncResponse.memberships:type_name -> com.bdsw.proto.service.GroupSyncResponse.MembershipsEntry
	21, // 7: com.bdsw.proto.service.FriendSyncResponse.friends:type_name -> com.bdsw.proto.common.Friend
	22, // 8: com.bdsw.proto.service.FriendSyncResponse.applies:type_name -> com.bdsw.proto.common.FriendApply
	23, // 9: com.bdsw.proto.service.FullSyncResponse.user_info:type_name -> com.bdsw.proto.common.User
	19, // 10: com.bdsw.proto.service.FullSyncResponse.conversations:type_name -> com.bdsw.proto.common.Conversation
	20, // 11: com.bdsw.proto.service.FullSyncResponse.groups:type_name -> com.bdsw.proto.common.Group
	21, // 12: com.bdsw.proto.service.FullSyncResponse.friends:type_name -> com.bdsw.proto.common.Friend
	24, // 13: com.bdsw.proto.service.GroupSyncResponse.MembershipsEntry.value:type_name -> com.bdsw.proto.common.GroupMember
	0,  // 14: com.bdsw.proto.service.SyncService.syncMessages:input_type -> com.bdsw.proto.service.SyncRequest
	2,  // 15: com.bdsw.proto.service.SyncService.getUnreadCounts:input_type -> com.bdsw.proto.service.UnreadRequest
	4,  // 16: com.bdsw.proto.service.SyncService.syncConversations:input_type -> com.bdsw.proto.service.ConversationSyncRequest
	6,  // 17: com.bdsw.proto.service.SyncService.getMessageSeq:input_type -> com.bdsw.proto.service.GetSeqRequest
	8,  // 18: com.bdsw.proto.service.SyncService.syncGroups:input_type -> com.bdsw.proto.service.GroupSyncRequest
	10, // 19: com.bdsw.proto.service.SyncService.syncFriends:input_type -> com.bdsw.proto.service.FriendSyncRequest
	12, // 20: com.bdsw.proto.service.SyncService.fullSync:input_type -> com.bdsw.proto.service.FullSyncRequest
	1,  // 21: com.bdsw.proto.service.SyncService.syncMessages:output_type -> com.bdsw.proto.service.SyncResponse
	3,  // 22: com.bdsw.proto.service.SyncService.getUnreadCounts:output_type -> com.bdsw.proto.service.UnreadResponse
	5,  // 23: com.bdsw.proto.service.SyncService.syncConversations:output_type -> com.bdsw.proto.service.ConversationSyncResponse
	7,  // 24: com.bdsw.proto.service.SyncService.getMessageSeq:output_type -> com.bdsw.proto.service.GetSeqResponse
	9,  // 25: com.bdsw.proto.service.SyncService.syncGroups:output_type -> com.bdsw.proto.service.GroupSyncResponse
	11, // 26: com.bdsw.proto.service.SyncService.syncFriends:output_type -> com.bdsw.proto.service.FriendSyncResponse
	13, // 27: com.bdsw.proto.service.SyncService.fullSync:output_type -> com.bdsw.proto.service.FullSyncResponse
	21, // [21:28] is the sub-list for method output_type
	14, // [14:21] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_proto_service_sync_service_proto_init() }
func file_proto_service_sync_service_proto_init() {
	if File_proto_service_sync_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_service_sync_service_proto_rawDesc), len(file_proto_service_sync_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_service_sync_service_proto_goTypes,
		DependencyIndexes: file_proto_service_sync_service_proto_depIdxs,
		MessageInfos:      file_proto_service_sync_service_proto_msgTypes,
	}.Build()
	File_proto_service_sync_service_proto = out.File
	file_proto_service_sync_service_proto_goTypes = nil
	file_proto_service_sync_service_proto_depIdxs = nil
}
