// Code generated by protoc-gen-go-triple. DO NOT EDIT.
// versions:
// - protoc-gen-go-triple v1.0.8
// - protoc             v6.32.1
// source: proto/service/ws_service.proto

package service

import (
	context "context"
	protocol "dubbo.apache.org/dubbo-go/v3/protocol"
	dubbo3 "dubbo.apache.org/dubbo-go/v3/protocol/dubbo3"
	invocation "dubbo.apache.org/dubbo-go/v3/protocol/invocation"
	common "github.com/bdsw/bdsw-im-ws/proto/common"
	grpc_go "github.com/dubbogo/grpc-go"
	codes "github.com/dubbogo/grpc-go/codes"
	metadata "github.com/dubbogo/grpc-go/metadata"
	status "github.com/dubbogo/grpc-go/status"
	common1 "github.com/dubbogo/triple/pkg/common"
	constant "github.com/dubbogo/triple/pkg/common/constant"
	triple "github.com/dubbogo/triple/pkg/triple"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc_go.SupportPackageIsVersion7

// WsServiceClient is the client API for WsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WsServiceClient interface {
	// 向指定用户推送消息（使用通用结构）
	PushToTarget(ctx context.Context, in *common.PushRequest, opts ...grpc_go.CallOption) (*common.PushResponse, common1.ErrorWithAttachment)
	// 踢用户下线
	KickTarget(ctx context.Context, in *WsKickUserRequest, opts ...grpc_go.CallOption) (*common.Response, common1.ErrorWithAttachment)
	// 广播消息（给所有在线用户）
	Broadcast(ctx context.Context, in *common.PushBroadcastRequest, opts ...grpc_go.CallOption) (*WsBroadcastResponse, common1.ErrorWithAttachment)
}

type wsServiceClient struct {
	cc *triple.TripleConn
}

type WsServiceClientImpl struct {
	PushToTarget func(ctx context.Context, in *common.PushRequest) (*common.PushResponse, error)
	KickTarget   func(ctx context.Context, in *WsKickUserRequest) (*common.Response, error)
	Broadcast    func(ctx context.Context, in *common.PushBroadcastRequest) (*WsBroadcastResponse, error)
}

func (c *WsServiceClientImpl) GetDubboStub(cc *triple.TripleConn) WsServiceClient {
	return NewWsServiceClient(cc)
}

func (c *WsServiceClientImpl) XXX_InterfaceName() string {
	return "com.bdsw.proto.service.WsService"
}

func NewWsServiceClient(cc *triple.TripleConn) WsServiceClient {
	return &wsServiceClient{cc}
}

func (c *wsServiceClient) PushToTarget(ctx context.Context, in *common.PushRequest, opts ...grpc_go.CallOption) (*common.PushResponse, common1.ErrorWithAttachment) {
	out := new(common.PushResponse)
	interfaceKey := ctx.Value(constant.InterfaceKey).(string)
	return out, c.cc.Invoke(ctx, "/"+interfaceKey+"/PushToTarget", in, out)
}

func (c *wsServiceClient) KickTarget(ctx context.Context, in *WsKickUserRequest, opts ...grpc_go.CallOption) (*common.Response, common1.ErrorWithAttachment) {
	out := new(common.Response)
	interfaceKey := ctx.Value(constant.InterfaceKey).(string)
	return out, c.cc.Invoke(ctx, "/"+interfaceKey+"/KickTarget", in, out)
}

func (c *wsServiceClient) Broadcast(ctx context.Context, in *common.PushBroadcastRequest, opts ...grpc_go.CallOption) (*WsBroadcastResponse, common1.ErrorWithAttachment) {
	out := new(WsBroadcastResponse)
	interfaceKey := ctx.Value(constant.InterfaceKey).(string)
	return out, c.cc.Invoke(ctx, "/"+interfaceKey+"/Broadcast", in, out)
}

// WsServiceServer is the server API for WsService service.
// All implementations must embed UnimplementedWsServiceServer
// for forward compatibility
type WsServiceServer interface {
	// 向指定用户推送消息（使用通用结构）
	PushToTarget(context.Context, *common.PushRequest) (*common.PushResponse, error)
	// 踢用户下线
	KickTarget(context.Context, *WsKickUserRequest) (*common.Response, error)
	// 广播消息（给所有在线用户）
	Broadcast(context.Context, *common.PushBroadcastRequest) (*WsBroadcastResponse, error)
	mustEmbedUnimplementedWsServiceServer()
}

// UnimplementedWsServiceServer must be embedded to have forward compatible implementations.
type UnimplementedWsServiceServer struct {
	proxyImpl protocol.Invoker
}

func (UnimplementedWsServiceServer) PushToTarget(context.Context, *common.PushRequest) (*common.PushResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PushToTarget not implemented")
}
func (UnimplementedWsServiceServer) KickTarget(context.Context, *WsKickUserRequest) (*common.Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method KickTarget not implemented")
}
func (UnimplementedWsServiceServer) Broadcast(context.Context, *common.PushBroadcastRequest) (*WsBroadcastResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Broadcast not implemented")
}
func (s *UnimplementedWsServiceServer) XXX_SetProxyImpl(impl protocol.Invoker) {
	s.proxyImpl = impl
}

func (s *UnimplementedWsServiceServer) XXX_GetProxyImpl() protocol.Invoker {
	return s.proxyImpl
}

func (s *UnimplementedWsServiceServer) XXX_ServiceDesc() *grpc_go.ServiceDesc {
	return &WsService_ServiceDesc
}
func (s *UnimplementedWsServiceServer) XXX_InterfaceName() string {
	return "com.bdsw.proto.service.WsService"
}

func (UnimplementedWsServiceServer) mustEmbedUnimplementedWsServiceServer() {}

// UnsafeWsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WsServiceServer will
// result in compilation errors.
type UnsafeWsServiceServer interface {
	mustEmbedUnimplementedWsServiceServer()
}

func RegisterWsServiceServer(s grpc_go.ServiceRegistrar, srv WsServiceServer) {
	s.RegisterService(&WsService_ServiceDesc, srv)
}

func _WsService_PushToTarget_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc_go.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.PushRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	base := srv.(dubbo3.Dubbo3GrpcService)
	args := []interface{}{}
	args = append(args, in)
	md, _ := metadata.FromIncomingContext(ctx)
	invAttachment := make(map[string]interface{}, len(md))
	for k, v := range md {
		invAttachment[k] = v
	}
	invo := invocation.NewRPCInvocation("PushToTarget", args, invAttachment)
	if interceptor == nil {
		result := base.XXX_GetProxyImpl().Invoke(ctx, invo)
		return result, result.Error()
	}
	info := &grpc_go.UnaryServerInfo{
		Server:     srv,
		FullMethod: ctx.Value("XXX_TRIPLE_GO_INTERFACE_NAME").(string),
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		result := base.XXX_GetProxyImpl().Invoke(ctx, invo)
		return result, result.Error()
	}
	return interceptor(ctx, in, info, handler)
}

func _WsService_KickTarget_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc_go.UnaryServerInterceptor) (interface{}, error) {
	in := new(WsKickUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	base := srv.(dubbo3.Dubbo3GrpcService)
	args := []interface{}{}
	args = append(args, in)
	md, _ := metadata.FromIncomingContext(ctx)
	invAttachment := make(map[string]interface{}, len(md))
	for k, v := range md {
		invAttachment[k] = v
	}
	invo := invocation.NewRPCInvocation("KickTarget", args, invAttachment)
	if interceptor == nil {
		result := base.XXX_GetProxyImpl().Invoke(ctx, invo)
		return result, result.Error()
	}
	info := &grpc_go.UnaryServerInfo{
		Server:     srv,
		FullMethod: ctx.Value("XXX_TRIPLE_GO_INTERFACE_NAME").(string),
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		result := base.XXX_GetProxyImpl().Invoke(ctx, invo)
		return result, result.Error()
	}
	return interceptor(ctx, in, info, handler)
}

func _WsService_Broadcast_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc_go.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.PushBroadcastRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	base := srv.(dubbo3.Dubbo3GrpcService)
	args := []interface{}{}
	args = append(args, in)
	md, _ := metadata.FromIncomingContext(ctx)
	invAttachment := make(map[string]interface{}, len(md))
	for k, v := range md {
		invAttachment[k] = v
	}
	invo := invocation.NewRPCInvocation("Broadcast", args, invAttachment)
	if interceptor == nil {
		result := base.XXX_GetProxyImpl().Invoke(ctx, invo)
		return result, result.Error()
	}
	info := &grpc_go.UnaryServerInfo{
		Server:     srv,
		FullMethod: ctx.Value("XXX_TRIPLE_GO_INTERFACE_NAME").(string),
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		result := base.XXX_GetProxyImpl().Invoke(ctx, invo)
		return result, result.Error()
	}
	return interceptor(ctx, in, info, handler)
}

// WsService_ServiceDesc is the grpc_go.ServiceDesc for WsService service.
// It's only intended for direct use with grpc_go.RegisterService,
// and not to be introspected or modified (even as a copy)
var WsService_ServiceDesc = grpc_go.ServiceDesc{
	ServiceName: "com.bdsw.proto.service.WsService",
	HandlerType: (*WsServiceServer)(nil),
	Methods: []grpc_go.MethodDesc{
		{
			MethodName: "PushToTarget",
			Handler:    _WsService_PushToTarget_Handler,
		},
		{
			MethodName: "KickTarget",
			Handler:    _WsService_KickTarget_Handler,
		},
		{
			MethodName: "broadcast",
			Handler:    _WsService_Broadcast_Handler,
		},
	},
	Streams:  []grpc_go.StreamDesc{},
	Metadata: "proto/service/ws_service.proto",
}
