// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: proto/service/ws_service.proto

// Java 包的命名空间

package service

import (
	common "github.com/bdsw/bdsw-im-ws/proto/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 踢用户下线
type WsKickUserRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 推送设备目标列表（必填）
	// 所有推送最终都归结为设备列表
	TargetDevices    *common.DeviceTargetList `protobuf:"bytes,1,opt,name=target_devices,json=targetDevices,proto3" json:"target_devices,omitempty"`
	OperatorId       string                   `protobuf:"bytes,2,opt,name=operator_id,json=operatorId,proto3" json:"operator_id,omitempty"`                     // 操作人ID（可选）
	Reason           int32                    `protobuf:"varint,3,opt,name=reason,proto3" json:"reason,omitempty"`                                              // 下线原因：0-正常下线 1-被踢下线 2-账号异常 3-多端登录冲突
	ReasonMessage    string                   `protobuf:"bytes,4,opt,name=reason_message,json=reasonMessage,proto3" json:"reason_message,omitempty"`            // 原因描述
	ExcludeDeviceIds []string                 `protobuf:"bytes,5,rep,name=exclude_device_ids,json=excludeDeviceIds,proto3" json:"exclude_device_ids,omitempty"` // 排除的设备ID（不踢下线）
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *WsKickUserRequest) Reset() {
	*x = WsKickUserRequest{}
	mi := &file_proto_service_ws_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WsKickUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WsKickUserRequest) ProtoMessage() {}

func (x *WsKickUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_ws_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WsKickUserRequest.ProtoReflect.Descriptor instead.
func (*WsKickUserRequest) Descriptor() ([]byte, []int) {
	return file_proto_service_ws_service_proto_rawDescGZIP(), []int{0}
}

func (x *WsKickUserRequest) GetTargetDevices() *common.DeviceTargetList {
	if x != nil {
		return x.TargetDevices
	}
	return nil
}

func (x *WsKickUserRequest) GetOperatorId() string {
	if x != nil {
		return x.OperatorId
	}
	return ""
}

func (x *WsKickUserRequest) GetReason() int32 {
	if x != nil {
		return x.Reason
	}
	return 0
}

func (x *WsKickUserRequest) GetReasonMessage() string {
	if x != nil {
		return x.ReasonMessage
	}
	return ""
}

func (x *WsKickUserRequest) GetExcludeDeviceIds() []string {
	if x != nil {
		return x.ExcludeDeviceIds
	}
	return nil
}

// 广播响应
type WsBroadcastResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalUsers    int64                  `protobuf:"varint,1,opt,name=total_users,json=totalUsers,proto3" json:"total_users,omitempty"`    // 总在线用户数
	PushedUsers   int64                  `protobuf:"varint,2,opt,name=pushed_users,json=pushedUsers,proto3" json:"pushed_users,omitempty"` // 已推送用户数
	FailedUsers   int64                  `protobuf:"varint,3,opt,name=failed_users,json=failedUsers,proto3" json:"failed_users,omitempty"` // 推送失败用户数
	TaskId        string                 `protobuf:"bytes,4,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WsBroadcastResponse) Reset() {
	*x = WsBroadcastResponse{}
	mi := &file_proto_service_ws_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WsBroadcastResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WsBroadcastResponse) ProtoMessage() {}

func (x *WsBroadcastResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_ws_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WsBroadcastResponse.ProtoReflect.Descriptor instead.
func (*WsBroadcastResponse) Descriptor() ([]byte, []int) {
	return file_proto_service_ws_service_proto_rawDescGZIP(), []int{1}
}

func (x *WsBroadcastResponse) GetTotalUsers() int64 {
	if x != nil {
		return x.TotalUsers
	}
	return 0
}

func (x *WsBroadcastResponse) GetPushedUsers() int64 {
	if x != nil {
		return x.PushedUsers
	}
	return 0
}

func (x *WsBroadcastResponse) GetFailedUsers() int64 {
	if x != nil {
		return x.FailedUsers
	}
	return 0
}

func (x *WsBroadcastResponse) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

var File_proto_service_ws_service_proto protoreflect.FileDescriptor

const file_proto_service_ws_service_proto_rawDesc = "" +
	"\n" +
	"\x1eproto/service/ws_service.proto\x12\x16com.bdsw.proto.service\x1a\x19proto/common/common.proto\x1a\x17proto/common/push.proto\"\xf1\x01\n" +
	"\x11WsKickUserRequest\x12N\n" +
	"\x0etarget_devices\x18\x01 \x01(\v2'.com.bdsw.proto.common.DeviceTargetListR\rtargetDevices\x12\x1f\n" +
	"\voperator_id\x18\x02 \x01(\tR\n" +
	"operatorId\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\x05R\x06reason\x12%\n" +
	"\x0ereason_message\x18\x04 \x01(\tR\rreasonMessage\x12,\n" +
	"\x12exclude_device_ids\x18\x05 \x03(\tR\x10excludeDeviceIds\"\x95\x01\n" +
	"\x13WsBroadcastResponse\x12\x1f\n" +
	"\vtotal_users\x18\x01 \x01(\x03R\n" +
	"totalUsers\x12!\n" +
	"\fpushed_users\x18\x02 \x01(\x03R\vpushedUsers\x12!\n" +
	"\ffailed_users\x18\x03 \x01(\x03R\vfailedUsers\x12\x17\n" +
	"\atask_id\x18\x04 \x01(\tR\x06taskId2\xa5\x02\n" +
	"\tWsService\x12W\n" +
	"\fPushToTarget\x12\".com.bdsw.proto.common.PushRequest\x1a#.com.bdsw.proto.common.PushResponse\x12X\n" +
	"\n" +
	"KickTarget\x12).com.bdsw.proto.service.WsKickUserRequest\x1a\x1f.com.bdsw.proto.common.Response\x12e\n" +
	"\tbroadcast\x12+.com.bdsw.proto.common.PushBroadcastRequest\x1a+.com.bdsw.proto.service.WsBroadcastResponseB\\\n" +
	"\x16com.bdsw.proto.serviceB\x0eWsServiceProtoP\x01Z0github.com/bdsw/bdsw-im-ws/proto/service;serviceb\x06proto3"

var (
	file_proto_service_ws_service_proto_rawDescOnce sync.Once
	file_proto_service_ws_service_proto_rawDescData []byte
)

func file_proto_service_ws_service_proto_rawDescGZIP() []byte {
	file_proto_service_ws_service_proto_rawDescOnce.Do(func() {
		file_proto_service_ws_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_service_ws_service_proto_rawDesc), len(file_proto_service_ws_service_proto_rawDesc)))
	})
	return file_proto_service_ws_service_proto_rawDescData
}

var file_proto_service_ws_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_service_ws_service_proto_goTypes = []any{
	(*WsKickUserRequest)(nil),           // 0: com.bdsw.proto.service.WsKickUserRequest
	(*WsBroadcastResponse)(nil),         // 1: com.bdsw.proto.service.WsBroadcastResponse
	(*common.DeviceTargetList)(nil),     // 2: com.bdsw.proto.common.DeviceTargetList
	(*common.PushRequest)(nil),          // 3: com.bdsw.proto.common.PushRequest
	(*common.PushBroadcastRequest)(nil), // 4: com.bdsw.proto.common.PushBroadcastRequest
	(*common.PushResponse)(nil),         // 5: com.bdsw.proto.common.PushResponse
	(*common.Response)(nil),             // 6: com.bdsw.proto.common.Response
}
var file_proto_service_ws_service_proto_depIdxs = []int32{
	2, // 0: com.bdsw.proto.service.WsKickUserRequest.target_devices:type_name -> com.bdsw.proto.common.DeviceTargetList
	3, // 1: com.bdsw.proto.service.WsService.PushToTarget:input_type -> com.bdsw.proto.common.PushRequest
	0, // 2: com.bdsw.proto.service.WsService.KickTarget:input_type -> com.bdsw.proto.service.WsKickUserRequest
	4, // 3: com.bdsw.proto.service.WsService.broadcast:input_type -> com.bdsw.proto.common.PushBroadcastRequest
	5, // 4: com.bdsw.proto.service.WsService.PushToTarget:output_type -> com.bdsw.proto.common.PushResponse
	6, // 5: com.bdsw.proto.service.WsService.KickTarget:output_type -> com.bdsw.proto.common.Response
	1, // 6: com.bdsw.proto.service.WsService.broadcast:output_type -> com.bdsw.proto.service.WsBroadcastResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_service_ws_service_proto_init() }
func file_proto_service_ws_service_proto_init() {
	if File_proto_service_ws_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_service_ws_service_proto_rawDesc), len(file_proto_service_ws_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_service_ws_service_proto_goTypes,
		DependencyIndexes: file_proto_service_ws_service_proto_depIdxs,
		MessageInfos:      file_proto_service_ws_service_proto_msgTypes,
	}.Build()
	File_proto_service_ws_service_proto = out.File
	file_proto_service_ws_service_proto_goTypes = nil
	file_proto_service_ws_service_proto_depIdxs = nil
}
