// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: api/ima_gateway/ima_gateway.proto

package ima_gateway

import (
	common "bdsw-im-ws/api/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 推送请求
type PushRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DeviceId      string                 `protobuf:"bytes,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Message       *common.ServerMessage  `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushRequest) Reset() {
	*x = PushRequest{}
	mi := &file_api_ima_gateway_ima_gateway_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushRequest) ProtoMessage() {}

func (x *PushRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_ima_gateway_ima_gateway_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushRequest.ProtoReflect.Descriptor instead.
func (*PushRequest) Descriptor() ([]byte, []int) {
	return file_api_ima_gateway_ima_gateway_proto_rawDescGZIP(), []int{0}
}

func (x *PushRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *PushRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *PushRequest) GetMessage() *common.ServerMessage {
	if x != nil {
		return x.Message
	}
	return nil
}

// 批量推送
type BatchPushRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pushes        []*PushRequest         `protobuf:"bytes,1,rep,name=pushes,proto3" json:"pushes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchPushRequest) Reset() {
	*x = BatchPushRequest{}
	mi := &file_api_ima_gateway_ima_gateway_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchPushRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchPushRequest) ProtoMessage() {}

func (x *BatchPushRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_ima_gateway_ima_gateway_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchPushRequest.ProtoReflect.Descriptor instead.
func (*BatchPushRequest) Descriptor() ([]byte, []int) {
	return file_api_ima_gateway_ima_gateway_proto_rawDescGZIP(), []int{1}
}

func (x *BatchPushRequest) GetPushes() []*PushRequest {
	if x != nil {
		return x.Pushes
	}
	return nil
}

// 广播消息
type BroadcastMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       *common.ServerMessage  `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	TargetUsers   []string               `protobuf:"bytes,2,rep,name=target_users,json=targetUsers,proto3" json:"target_users,omitempty"` // 空表示广播给所有人
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BroadcastMessage) Reset() {
	*x = BroadcastMessage{}
	mi := &file_api_ima_gateway_ima_gateway_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BroadcastMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BroadcastMessage) ProtoMessage() {}

func (x *BroadcastMessage) ProtoReflect() protoreflect.Message {
	mi := &file_api_ima_gateway_ima_gateway_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BroadcastMessage.ProtoReflect.Descriptor instead.
func (*BroadcastMessage) Descriptor() ([]byte, []int) {
	return file_api_ima_gateway_ima_gateway_proto_rawDescGZIP(), []int{2}
}

func (x *BroadcastMessage) GetMessage() *common.ServerMessage {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *BroadcastMessage) GetTargetUsers() []string {
	if x != nil {
		return x.TargetUsers
	}
	return nil
}

// 连接状态
type ConnectionStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DeviceId      string                 `protobuf:"bytes,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	ImaInstance   string                 `protobuf:"bytes,3,opt,name=ima_instance,json=imaInstance,proto3" json:"ima_instance,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"` // online, offline, away, busy
	Timestamp     int64                  `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	DeviceInfo    *common.DeviceInfo     `protobuf:"bytes,6,opt,name=device_info,json=deviceInfo,proto3" json:"device_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectionStatus) Reset() {
	*x = ConnectionStatus{}
	mi := &file_api_ima_gateway_ima_gateway_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectionStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectionStatus) ProtoMessage() {}

func (x *ConnectionStatus) ProtoReflect() protoreflect.Message {
	mi := &file_api_ima_gateway_ima_gateway_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectionStatus.ProtoReflect.Descriptor instead.
func (*ConnectionStatus) Descriptor() ([]byte, []int) {
	return file_api_ima_gateway_ima_gateway_proto_rawDescGZIP(), []int{3}
}

func (x *ConnectionStatus) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ConnectionStatus) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *ConnectionStatus) GetImaInstance() string {
	if x != nil {
		return x.ImaInstance
	}
	return ""
}

func (x *ConnectionStatus) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ConnectionStatus) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *ConnectionStatus) GetDeviceInfo() *common.DeviceInfo {
	if x != nil {
		return x.DeviceInfo
	}
	return nil
}

// 踢用户下线请求
type KickUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DeviceId      string                 `protobuf:"bytes,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"` // multi_login, admin_kick, system_maintenance
	Operator      string                 `protobuf:"bytes,4,opt,name=operator,proto3" json:"operator,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KickUserRequest) Reset() {
	*x = KickUserRequest{}
	mi := &file_api_ima_gateway_ima_gateway_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KickUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KickUserRequest) ProtoMessage() {}

func (x *KickUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_ima_gateway_ima_gateway_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KickUserRequest.ProtoReflect.Descriptor instead.
func (*KickUserRequest) Descriptor() ([]byte, []int) {
	return file_api_ima_gateway_ima_gateway_proto_rawDescGZIP(), []int{4}
}

func (x *KickUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *KickUserRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *KickUserRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *KickUserRequest) GetOperator() string {
	if x != nil {
		return x.Operator
	}
	return ""
}

// 获取在线用户请求
type GetOnlineUsersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserIds       []string               `protobuf:"bytes,1,rep,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"`
	ImaInstance   string                 `protobuf:"bytes,2,opt,name=ima_instance,json=imaInstance,proto3" json:"ima_instance,omitempty"` // 为空表示所有实例
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOnlineUsersRequest) Reset() {
	*x = GetOnlineUsersRequest{}
	mi := &file_api_ima_gateway_ima_gateway_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOnlineUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOnlineUsersRequest) ProtoMessage() {}

func (x *GetOnlineUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_ima_gateway_ima_gateway_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOnlineUsersRequest.ProtoReflect.Descriptor instead.
func (*GetOnlineUsersRequest) Descriptor() ([]byte, []int) {
	return file_api_ima_gateway_ima_gateway_proto_rawDescGZIP(), []int{5}
}

func (x *GetOnlineUsersRequest) GetUserIds() []string {
	if x != nil {
		return x.UserIds
	}
	return nil
}

func (x *GetOnlineUsersRequest) GetImaInstance() string {
	if x != nil {
		return x.ImaInstance
	}
	return ""
}

// 获取在线用户响应
type GetOnlineUsersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *common.BaseResponse   `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	OnlineUsers   []*ConnectionStatus    `protobuf:"bytes,2,rep,name=online_users,json=onlineUsers,proto3" json:"online_users,omitempty"`
	TotalCount    int32                  `protobuf:"varint,3,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOnlineUsersResponse) Reset() {
	*x = GetOnlineUsersResponse{}
	mi := &file_api_ima_gateway_ima_gateway_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOnlineUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOnlineUsersResponse) ProtoMessage() {}

func (x *GetOnlineUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_ima_gateway_ima_gateway_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOnlineUsersResponse.ProtoReflect.Descriptor instead.
func (*GetOnlineUsersResponse) Descriptor() ([]byte, []int) {
	return file_api_ima_gateway_ima_gateway_proto_rawDescGZIP(), []int{6}
}

func (x *GetOnlineUsersResponse) GetBase() *common.BaseResponse {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *GetOnlineUsersResponse) GetOnlineUsers() []*ConnectionStatus {
	if x != nil {
		return x.OnlineUsers
	}
	return nil
}

func (x *GetOnlineUsersResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

// 检查用户在线状态请求
type CheckUserOnlineRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DeviceId      string                 `protobuf:"bytes,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"` // 为空表示任意设备
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckUserOnlineRequest) Reset() {
	*x = CheckUserOnlineRequest{}
	mi := &file_api_ima_gateway_ima_gateway_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckUserOnlineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckUserOnlineRequest) ProtoMessage() {}

func (x *CheckUserOnlineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_ima_gateway_ima_gateway_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckUserOnlineRequest.ProtoReflect.Descriptor instead.
func (*CheckUserOnlineRequest) Descriptor() ([]byte, []int) {
	return file_api_ima_gateway_ima_gateway_proto_rawDescGZIP(), []int{7}
}

func (x *CheckUserOnlineRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CheckUserOnlineRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

// 检查用户在线状态响应
type CheckUserOnlineResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Base           *common.BaseResponse   `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Online         bool                   `protobuf:"varint,2,opt,name=online,proto3" json:"online,omitempty"`
	OnlineDevices  []string               `protobuf:"bytes,3,rep,name=online_devices,json=onlineDevices,proto3" json:"online_devices,omitempty"`
	ImaInstance    string                 `protobuf:"bytes,4,opt,name=ima_instance,json=imaInstance,proto3" json:"ima_instance,omitempty"`
	LastActiveTime int64                  `protobuf:"varint,5,opt,name=last_active_time,json=lastActiveTime,proto3" json:"last_active_time,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CheckUserOnlineResponse) Reset() {
	*x = CheckUserOnlineResponse{}
	mi := &file_api_ima_gateway_ima_gateway_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckUserOnlineResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckUserOnlineResponse) ProtoMessage() {}

func (x *CheckUserOnlineResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_ima_gateway_ima_gateway_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckUserOnlineResponse.ProtoReflect.Descriptor instead.
func (*CheckUserOnlineResponse) Descriptor() ([]byte, []int) {
	return file_api_ima_gateway_ima_gateway_proto_rawDescGZIP(), []int{8}
}

func (x *CheckUserOnlineResponse) GetBase() *common.BaseResponse {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *CheckUserOnlineResponse) GetOnline() bool {
	if x != nil {
		return x.Online
	}
	return false
}

func (x *CheckUserOnlineResponse) GetOnlineDevices() []string {
	if x != nil {
		return x.OnlineDevices
	}
	return nil
}

func (x *CheckUserOnlineResponse) GetImaInstance() string {
	if x != nil {
		return x.ImaInstance
	}
	return ""
}

func (x *CheckUserOnlineResponse) GetLastActiveTime() int64 {
	if x != nil {
		return x.LastActiveTime
	}
	return 0
}

var File_api_ima_gateway_ima_gateway_proto protoreflect.FileDescriptor

const file_api_ima_gateway_ima_gateway_proto_rawDesc = "" +
	"\n" +
	"!api/ima_gateway/ima_gateway.proto\x12\vima_gateway\x1a\x17api/common/common.proto\"t\n" +
	"\vPushRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tdevice_id\x18\x02 \x01(\tR\bdeviceId\x12/\n" +
	"\amessage\x18\x03 \x01(\v2\x15.common.ServerMessageR\amessage\"D\n" +
	"\x10BatchPushRequest\x120\n" +
	"\x06pushes\x18\x01 \x03(\v2\x18.ima_gateway.PushRequestR\x06pushes\"f\n" +
	"\x10BroadcastMessage\x12/\n" +
	"\amessage\x18\x01 \x01(\v2\x15.common.ServerMessageR\amessage\x12!\n" +
	"\ftarget_users\x18\x02 \x03(\tR\vtargetUsers\"\xd6\x01\n" +
	"\x10ConnectionStatus\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tdevice_id\x18\x02 \x01(\tR\bdeviceId\x12!\n" +
	"\fima_instance\x18\x03 \x01(\tR\vimaInstance\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x03R\ttimestamp\x123\n" +
	"\vdevice_info\x18\x06 \x01(\v2\x12.common.DeviceInfoR\n" +
	"deviceInfo\"{\n" +
	"\x0fKickUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tdevice_id\x18\x02 \x01(\tR\bdeviceId\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\x12\x1a\n" +
	"\boperator\x18\x04 \x01(\tR\boperator\"U\n" +
	"\x15GetOnlineUsersRequest\x12\x19\n" +
	"\buser_ids\x18\x01 \x03(\tR\auserIds\x12!\n" +
	"\fima_instance\x18\x02 \x01(\tR\vimaInstance\"\xa5\x01\n" +
	"\x16GetOnlineUsersResponse\x12(\n" +
	"\x04base\x18\x01 \x01(\v2\x14.common.BaseResponseR\x04base\x12@\n" +
	"\fonline_users\x18\x02 \x03(\v2\x1d.ima_gateway.ConnectionStatusR\vonlineUsers\x12\x1f\n" +
	"\vtotal_count\x18\x03 \x01(\x05R\n" +
	"totalCount\"N\n" +
	"\x16CheckUserOnlineRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tdevice_id\x18\x02 \x01(\tR\bdeviceId\"\xcf\x01\n" +
	"\x17CheckUserOnlineResponse\x12(\n" +
	"\x04base\x18\x01 \x01(\v2\x14.common.BaseResponseR\x04base\x12\x16\n" +
	"\x06online\x18\x02 \x01(\bR\x06online\x12%\n" +
	"\x0eonline_devices\x18\x03 \x03(\tR\ronlineDevices\x12!\n" +
	"\fima_instance\x18\x04 \x01(\tR\vimaInstance\x12(\n" +
	"\x10last_active_time\x18\x05 \x01(\x03R\x0elastActiveTimeB\x1cZ\x1abdsw-im-ws/api/ima_gatewayb\x06proto3"

var (
	file_api_ima_gateway_ima_gateway_proto_rawDescOnce sync.Once
	file_api_ima_gateway_ima_gateway_proto_rawDescData []byte
)

func file_api_ima_gateway_ima_gateway_proto_rawDescGZIP() []byte {
	file_api_ima_gateway_ima_gateway_proto_rawDescOnce.Do(func() {
		file_api_ima_gateway_ima_gateway_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_ima_gateway_ima_gateway_proto_rawDesc), len(file_api_ima_gateway_ima_gateway_proto_rawDesc)))
	})
	return file_api_ima_gateway_ima_gateway_proto_rawDescData
}

var file_api_ima_gateway_ima_gateway_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_api_ima_gateway_ima_gateway_proto_goTypes = []any{
	(*PushRequest)(nil),             // 0: ima_gateway.PushRequest
	(*BatchPushRequest)(nil),        // 1: ima_gateway.BatchPushRequest
	(*BroadcastMessage)(nil),        // 2: ima_gateway.BroadcastMessage
	(*ConnectionStatus)(nil),        // 3: ima_gateway.ConnectionStatus
	(*KickUserRequest)(nil),         // 4: ima_gateway.KickUserRequest
	(*GetOnlineUsersRequest)(nil),   // 5: ima_gateway.GetOnlineUsersRequest
	(*GetOnlineUsersResponse)(nil),  // 6: ima_gateway.GetOnlineUsersResponse
	(*CheckUserOnlineRequest)(nil),  // 7: ima_gateway.CheckUserOnlineRequest
	(*CheckUserOnlineResponse)(nil), // 8: ima_gateway.CheckUserOnlineResponse
	(*common.ServerMessage)(nil),    // 9: common.ServerMessage
	(*common.DeviceInfo)(nil),       // 10: common.DeviceInfo
	(*common.BaseResponse)(nil),     // 11: common.BaseResponse
}
var file_api_ima_gateway_ima_gateway_proto_depIdxs = []int32{
	9,  // 0: ima_gateway.PushRequest.message:type_name -> common.ServerMessage
	0,  // 1: ima_gateway.BatchPushRequest.pushes:type_name -> ima_gateway.PushRequest
	9,  // 2: ima_gateway.BroadcastMessage.message:type_name -> common.ServerMessage
	10, // 3: ima_gateway.ConnectionStatus.device_info:type_name -> common.DeviceInfo
	11, // 4: ima_gateway.GetOnlineUsersResponse.base:type_name -> common.BaseResponse
	3,  // 5: ima_gateway.GetOnlineUsersResponse.online_users:type_name -> ima_gateway.ConnectionStatus
	11, // 6: ima_gateway.CheckUserOnlineResponse.base:type_name -> common.BaseResponse
	7,  // [7:7] is the sub-list for method output_type
	7,  // [7:7] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_api_ima_gateway_ima_gateway_proto_init() }
func file_api_ima_gateway_ima_gateway_proto_init() {
	if File_api_ima_gateway_ima_gateway_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_ima_gateway_ima_gateway_proto_rawDesc), len(file_api_ima_gateway_ima_gateway_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_ima_gateway_ima_gateway_proto_goTypes,
		DependencyIndexes: file_api_ima_gateway_ima_gateway_proto_depIdxs,
		MessageInfos:      file_api_ima_gateway_ima_gateway_proto_msgTypes,
	}.Build()
	File_api_ima_gateway_ima_gateway_proto = out.File
	file_api_ima_gateway_ima_gateway_proto_goTypes = nil
	file_api_ima_gateway_ima_gateway_proto_depIdxs = nil
}
