// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: proto/common/push.proto

// Java 包的命名空间

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 原始推送类型（用于日志和统计）
type PushRequest_PushType int32

const (
	PushRequest_SINGLE_USER   PushRequest_PushType = 0 // 单用户推送
	PushRequest_MULTI_USER    PushRequest_PushType = 1 // 多用户推送
	PushRequest_SINGLE_DEVICE PushRequest_PushType = 2 // 单设备推送
	PushRequest_MULTI_DEVICE  PushRequest_PushType = 3 // 多设备推送
	PushRequest_GROUP         PushRequest_PushType = 4 // 群组推送
	PushRequest_CONVERSATION  PushRequest_PushType = 5 // 会话推送
	PushRequest_BROADCAST     PushRequest_PushType = 6 // 广播推送
)

// Enum value maps for PushRequest_PushType.
var (
	PushRequest_PushType_name = map[int32]string{
		0: "SINGLE_USER",
		1: "MULTI_USER",
		2: "SINGLE_DEVICE",
		3: "MULTI_DEVICE",
		4: "GROUP",
		5: "CONVERSATION",
		6: "BROADCAST",
	}
	PushRequest_PushType_value = map[string]int32{
		"SINGLE_USER":   0,
		"MULTI_USER":    1,
		"SINGLE_DEVICE": 2,
		"MULTI_DEVICE":  3,
		"GROUP":         4,
		"CONVERSATION":  5,
		"BROADCAST":     6,
	}
)

func (x PushRequest_PushType) Enum() *PushRequest_PushType {
	p := new(PushRequest_PushType)
	*p = x
	return p
}

func (x PushRequest_PushType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PushRequest_PushType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_common_push_proto_enumTypes[0].Descriptor()
}

func (PushRequest_PushType) Type() protoreflect.EnumType {
	return &file_proto_common_push_proto_enumTypes[0]
}

func (x PushRequest_PushType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PushRequest_PushType.Descriptor instead.
func (PushRequest_PushType) EnumDescriptor() ([]byte, []int) {
	return file_proto_common_push_proto_rawDescGZIP(), []int{2, 0}
}

// 推送优先级
type PushOptions_Priority int32

const (
	PushOptions_LOW      PushOptions_Priority = 0 // 低优先级（可延迟）
	PushOptions_NORMAL   PushOptions_Priority = 1 // 普通优先级
	PushOptions_HIGH     PushOptions_Priority = 2 // 高优先级（立即发送）
	PushOptions_CRITICAL PushOptions_Priority = 3 // 关键优先级（必达）
)

// Enum value maps for PushOptions_Priority.
var (
	PushOptions_Priority_name = map[int32]string{
		0: "LOW",
		1: "NORMAL",
		2: "HIGH",
		3: "CRITICAL",
	}
	PushOptions_Priority_value = map[string]int32{
		"LOW":      0,
		"NORMAL":   1,
		"HIGH":     2,
		"CRITICAL": 3,
	}
)

func (x PushOptions_Priority) Enum() *PushOptions_Priority {
	p := new(PushOptions_Priority)
	*p = x
	return p
}

func (x PushOptions_Priority) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PushOptions_Priority) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_common_push_proto_enumTypes[1].Descriptor()
}

func (PushOptions_Priority) Type() protoreflect.EnumType {
	return &file_proto_common_push_proto_enumTypes[1]
}

func (x PushOptions_Priority) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PushOptions_Priority.Descriptor instead.
func (PushOptions_Priority) EnumDescriptor() ([]byte, []int) {
	return file_proto_common_push_proto_rawDescGZIP(), []int{3, 0}
}

// 设备同步策略
type PushOptions_SyncStrategy int32

const (
	PushOptions_SYNC_ALL           PushOptions_SyncStrategy = 0 // 同步到所有目标设备
	PushOptions_SYNC_EXCEPT_SOURCE PushOptions_SyncStrategy = 1 // 同步到除来源外的设备
	PushOptions_SYNC_NONE          PushOptions_SyncStrategy = 2 // 不进行设备间同步
)

// Enum value maps for PushOptions_SyncStrategy.
var (
	PushOptions_SyncStrategy_name = map[int32]string{
		0: "SYNC_ALL",
		1: "SYNC_EXCEPT_SOURCE",
		2: "SYNC_NONE",
	}
	PushOptions_SyncStrategy_value = map[string]int32{
		"SYNC_ALL":           0,
		"SYNC_EXCEPT_SOURCE": 1,
		"SYNC_NONE":          2,
	}
)

func (x PushOptions_SyncStrategy) Enum() *PushOptions_SyncStrategy {
	p := new(PushOptions_SyncStrategy)
	*p = x
	return p
}

func (x PushOptions_SyncStrategy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PushOptions_SyncStrategy) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_common_push_proto_enumTypes[2].Descriptor()
}

func (PushOptions_SyncStrategy) Type() protoreflect.EnumType {
	return &file_proto_common_push_proto_enumTypes[2]
}

func (x PushOptions_SyncStrategy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PushOptions_SyncStrategy.Descriptor instead.
func (PushOptions_SyncStrategy) EnumDescriptor() ([]byte, []int) {
	return file_proto_common_push_proto_rawDescGZIP(), []int{3, 1}
}

// 推送状态
type PushResult_ResultStatus int32

const (
	PushResult_PENDING  PushResult_ResultStatus = 0 // 等待中
	PushResult_SUCCESS  PushResult_ResultStatus = 1 // 成功
	PushResult_FAILED   PushResult_ResultStatus = 2 // 失败
	PushResult_SKIPPED  PushResult_ResultStatus = 3 // 跳过（如设备离线且skip_if_offline=true）
	PushResult_RETRYING PushResult_ResultStatus = 4 // 重试中
)

// Enum value maps for PushResult_ResultStatus.
var (
	PushResult_ResultStatus_name = map[int32]string{
		0: "PENDING",
		1: "SUCCESS",
		2: "FAILED",
		3: "SKIPPED",
		4: "RETRYING",
	}
	PushResult_ResultStatus_value = map[string]int32{
		"PENDING":  0,
		"SUCCESS":  1,
		"FAILED":   2,
		"SKIPPED":  3,
		"RETRYING": 4,
	}
)

func (x PushResult_ResultStatus) Enum() *PushResult_ResultStatus {
	p := new(PushResult_ResultStatus)
	*p = x
	return p
}

func (x PushResult_ResultStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PushResult_ResultStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_common_push_proto_enumTypes[3].Descriptor()
}

func (PushResult_ResultStatus) Type() protoreflect.EnumType {
	return &file_proto_common_push_proto_enumTypes[3]
}

func (x PushResult_ResultStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PushResult_ResultStatus.Descriptor instead.
func (PushResult_ResultStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_common_push_proto_rawDescGZIP(), []int{4, 0}
}

// ==================== 推送设备目标 ====================
// 最基本的推送目标：一个设备
type DeviceTarget struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DeviceId      string                 `protobuf:"bytes,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceTarget) Reset() {
	*x = DeviceTarget{}
	mi := &file_proto_common_push_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceTarget) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceTarget) ProtoMessage() {}

func (x *DeviceTarget) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_push_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceTarget.ProtoReflect.Descriptor instead.
func (*DeviceTarget) Descriptor() ([]byte, []int) {
	return file_proto_common_push_proto_rawDescGZIP(), []int{0}
}

func (x *DeviceTarget) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *DeviceTarget) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

// 设备目标列表
type DeviceTargetList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Devices       []*DeviceTarget        `protobuf:"bytes,1,rep,name=devices,proto3" json:"devices,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceTargetList) Reset() {
	*x = DeviceTargetList{}
	mi := &file_proto_common_push_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceTargetList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceTargetList) ProtoMessage() {}

func (x *DeviceTargetList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_push_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceTargetList.ProtoReflect.Descriptor instead.
func (*DeviceTargetList) Descriptor() ([]byte, []int) {
	return file_proto_common_push_proto_rawDescGZIP(), []int{1}
}

func (x *DeviceTargetList) GetDevices() []*DeviceTarget {
	if x != nil {
		return x.Devices
	}
	return nil
}

// ==================== 推送请求 ====================
// 通用推送请求
type PushRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 推送ID（唯一标识）
	PushId string `protobuf:"bytes,1,opt,name=push_id,json=pushId,proto3" json:"push_id,omitempty"`
	// 推送设备目标列表（必填）
	// 所有推送最终都归结为设备列表
	TargetDevices *DeviceTargetList `protobuf:"bytes,2,opt,name=target_devices,json=targetDevices,proto3" json:"target_devices,omitempty"`
	// 消息内容（必填）
	Message *Message `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	// 推送选项
	Options  *PushOptions         `protobuf:"bytes,4,opt,name=options,proto3" json:"options,omitempty"`
	PushType PushRequest_PushType `protobuf:"varint,5,opt,name=push_type,json=pushType,proto3,enum=com.bdsw.proto.common.PushRequest_PushType" json:"push_type,omitempty"`
	// 来源信息（原始请求者）
	SourceUserId   string `protobuf:"bytes,6,opt,name=source_user_id,json=sourceUserId,proto3" json:"source_user_id,omitempty"`       // 来源用户ID（可选）
	SourceDeviceId string `protobuf:"bytes,7,opt,name=source_device_id,json=sourceDeviceId,proto3" json:"source_device_id,omitempty"` // 来源设备ID（可选）
	// 请求信息
	RequestId     string `protobuf:"bytes,8,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`             // 请求ID
	SourceService string `protobuf:"bytes,9,opt,name=source_service,json=sourceService,proto3" json:"source_service,omitempty"` // 来源服务
	// 上下文信息（原始目标，用于重试等场景）
	//
	// Types that are valid to be assigned to OriginalTarget:
	//
	//	*PushRequest_OriginalUserId
	//	*PushRequest_OriginalGroupId
	//	*PushRequest_OriginalConversationId
	OriginalTarget isPushRequest_OriginalTarget `protobuf_oneof:"original_target"`
	// 时间信息
	CreateTime   int64 `protobuf:"varint,13,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	ScheduleTime int64 `protobuf:"varint,14,opt,name=schedule_time,json=scheduleTime,proto3" json:"schedule_time,omitempty"` // 计划推送时间
	// 扩展字段
	Extras        map[string]string `protobuf:"bytes,15,rep,name=extras,proto3" json:"extras,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushRequest) Reset() {
	*x = PushRequest{}
	mi := &file_proto_common_push_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushRequest) ProtoMessage() {}

func (x *PushRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_push_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushRequest.ProtoReflect.Descriptor instead.
func (*PushRequest) Descriptor() ([]byte, []int) {
	return file_proto_common_push_proto_rawDescGZIP(), []int{2}
}

func (x *PushRequest) GetPushId() string {
	if x != nil {
		return x.PushId
	}
	return ""
}

func (x *PushRequest) GetTargetDevices() *DeviceTargetList {
	if x != nil {
		return x.TargetDevices
	}
	return nil
}

func (x *PushRequest) GetMessage() *Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *PushRequest) GetOptions() *PushOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *PushRequest) GetPushType() PushRequest_PushType {
	if x != nil {
		return x.PushType
	}
	return PushRequest_SINGLE_USER
}

func (x *PushRequest) GetSourceUserId() string {
	if x != nil {
		return x.SourceUserId
	}
	return ""
}

func (x *PushRequest) GetSourceDeviceId() string {
	if x != nil {
		return x.SourceDeviceId
	}
	return ""
}

func (x *PushRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *PushRequest) GetSourceService() string {
	if x != nil {
		return x.SourceService
	}
	return ""
}

func (x *PushRequest) GetOriginalTarget() isPushRequest_OriginalTarget {
	if x != nil {
		return x.OriginalTarget
	}
	return nil
}

func (x *PushRequest) GetOriginalUserId() string {
	if x != nil {
		if x, ok := x.OriginalTarget.(*PushRequest_OriginalUserId); ok {
			return x.OriginalUserId
		}
	}
	return ""
}

func (x *PushRequest) GetOriginalGroupId() string {
	if x != nil {
		if x, ok := x.OriginalTarget.(*PushRequest_OriginalGroupId); ok {
			return x.OriginalGroupId
		}
	}
	return ""
}

func (x *PushRequest) GetOriginalConversationId() string {
	if x != nil {
		if x, ok := x.OriginalTarget.(*PushRequest_OriginalConversationId); ok {
			return x.OriginalConversationId
		}
	}
	return ""
}

func (x *PushRequest) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (x *PushRequest) GetScheduleTime() int64 {
	if x != nil {
		return x.ScheduleTime
	}
	return 0
}

func (x *PushRequest) GetExtras() map[string]string {
	if x != nil {
		return x.Extras
	}
	return nil
}

type isPushRequest_OriginalTarget interface {
	isPushRequest_OriginalTarget()
}

type PushRequest_OriginalUserId struct {
	OriginalUserId string `protobuf:"bytes,10,opt,name=original_user_id,json=originalUserId,proto3,oneof"` // 原始用户ID
}

type PushRequest_OriginalGroupId struct {
	OriginalGroupId string `protobuf:"bytes,11,opt,name=original_group_id,json=originalGroupId,proto3,oneof"` // 原始群组ID
}

type PushRequest_OriginalConversationId struct {
	OriginalConversationId string `protobuf:"bytes,12,opt,name=original_conversation_id,json=originalConversationId,proto3,oneof"` // 原始会话ID
}

func (*PushRequest_OriginalUserId) isPushRequest_OriginalTarget() {}

func (*PushRequest_OriginalGroupId) isPushRequest_OriginalTarget() {}

func (*PushRequest_OriginalConversationId) isPushRequest_OriginalTarget() {}

// ==================== 推送选项 ====================
type PushOptions struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Priority PushOptions_Priority   `protobuf:"varint,1,opt,name=priority,proto3,enum=com.bdsw.proto.common.PushOptions_Priority" json:"priority,omitempty"`
	// 消息持久化选项
	NeedPersist     bool `protobuf:"varint,2,opt,name=need_persist,json=needPersist,proto3" json:"need_persist,omitempty"`               // 是否需要持久化到DB
	NeedStore       bool `protobuf:"varint,3,opt,name=need_store,json=needStore,proto3" json:"need_store,omitempty"`                     // 是否需要存储到消息历史
	NeedReceipt     bool `protobuf:"varint,4,opt,name=need_receipt,json=needReceipt,proto3" json:"need_receipt,omitempty"`               // 是否需要送达回执
	NeedReadReceipt bool `protobuf:"varint,5,opt,name=need_read_receipt,json=needReadReceipt,proto3" json:"need_read_receipt,omitempty"` // 是否需要已读回执
	// 推送控制
	SkipIfOffline bool  `protobuf:"varint,6,opt,name=skip_if_offline,json=skipIfOffline,proto3" json:"skip_if_offline,omitempty"` // 如果设备离线是否跳过（仅对离线推送有效）
	ExpireTime    int64 `protobuf:"varint,7,opt,name=expire_time,json=expireTime,proto3" json:"expire_time,omitempty"`            // 过期时间戳（秒）
	// 重试策略
	MaxRetry      int32 `protobuf:"varint,8,opt,name=max_retry,json=maxRetry,proto3" json:"max_retry,omitempty"`                // 最大重试次数
	RetryInterval int64 `protobuf:"varint,9,opt,name=retry_interval,json=retryInterval,proto3" json:"retry_interval,omitempty"` // 重试间隔（秒）
	// 推送展示
	ShowNotification  bool                     `protobuf:"varint,10,opt,name=show_notification,json=showNotification,proto3" json:"show_notification,omitempty"`   // 是否显示通知
	NotificationTitle string                   `protobuf:"bytes,11,opt,name=notification_title,json=notificationTitle,proto3" json:"notification_title,omitempty"` // 通知标题
	NotificationBody  string                   `protobuf:"bytes,12,opt,name=notification_body,json=notificationBody,proto3" json:"notification_body,omitempty"`    // 通知内容
	NotificationSound string                   `protobuf:"bytes,13,opt,name=notification_sound,json=notificationSound,proto3" json:"notification_sound,omitempty"` // 通知声音
	SyncStrategy      PushOptions_SyncStrategy `protobuf:"varint,14,opt,name=sync_strategy,json=syncStrategy,proto3,enum=com.bdsw.proto.common.PushOptions_SyncStrategy" json:"sync_strategy,omitempty"`
	// 多端消息去重
	DedupKey    string `protobuf:"bytes,15,opt,name=dedup_key,json=dedupKey,proto3" json:"dedup_key,omitempty"`           // 去重键
	DedupWindow int32  `protobuf:"varint,16,opt,name=dedup_window,json=dedupWindow,proto3" json:"dedup_window,omitempty"` // 去重窗口（秒）
	// 扩展选项
	Extras        map[string]string `protobuf:"bytes,17,rep,name=extras,proto3" json:"extras,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushOptions) Reset() {
	*x = PushOptions{}
	mi := &file_proto_common_push_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushOptions) ProtoMessage() {}

func (x *PushOptions) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_push_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushOptions.ProtoReflect.Descriptor instead.
func (*PushOptions) Descriptor() ([]byte, []int) {
	return file_proto_common_push_proto_rawDescGZIP(), []int{3}
}

func (x *PushOptions) GetPriority() PushOptions_Priority {
	if x != nil {
		return x.Priority
	}
	return PushOptions_LOW
}

func (x *PushOptions) GetNeedPersist() bool {
	if x != nil {
		return x.NeedPersist
	}
	return false
}

func (x *PushOptions) GetNeedStore() bool {
	if x != nil {
		return x.NeedStore
	}
	return false
}

func (x *PushOptions) GetNeedReceipt() bool {
	if x != nil {
		return x.NeedReceipt
	}
	return false
}

func (x *PushOptions) GetNeedReadReceipt() bool {
	if x != nil {
		return x.NeedReadReceipt
	}
	return false
}

func (x *PushOptions) GetSkipIfOffline() bool {
	if x != nil {
		return x.SkipIfOffline
	}
	return false
}

func (x *PushOptions) GetExpireTime() int64 {
	if x != nil {
		return x.ExpireTime
	}
	return 0
}

func (x *PushOptions) GetMaxRetry() int32 {
	if x != nil {
		return x.MaxRetry
	}
	return 0
}

func (x *PushOptions) GetRetryInterval() int64 {
	if x != nil {
		return x.RetryInterval
	}
	return 0
}

func (x *PushOptions) GetShowNotification() bool {
	if x != nil {
		return x.ShowNotification
	}
	return false
}

func (x *PushOptions) GetNotificationTitle() string {
	if x != nil {
		return x.NotificationTitle
	}
	return ""
}

func (x *PushOptions) GetNotificationBody() string {
	if x != nil {
		return x.NotificationBody
	}
	return ""
}

func (x *PushOptions) GetNotificationSound() string {
	if x != nil {
		return x.NotificationSound
	}
	return ""
}

func (x *PushOptions) GetSyncStrategy() PushOptions_SyncStrategy {
	if x != nil {
		return x.SyncStrategy
	}
	return PushOptions_SYNC_ALL
}

func (x *PushOptions) GetDedupKey() string {
	if x != nil {
		return x.DedupKey
	}
	return ""
}

func (x *PushOptions) GetDedupWindow() int32 {
	if x != nil {
		return x.DedupWindow
	}
	return 0
}

func (x *PushOptions) GetExtras() map[string]string {
	if x != nil {
		return x.Extras
	}
	return nil
}

// ==================== 推送结果 ====================
type PushResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 设备目标
	UserId   string                  `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DeviceId string                  `protobuf:"bytes,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Status   PushResult_ResultStatus `protobuf:"varint,3,opt,name=status,proto3,enum=com.bdsw.proto.common.PushResult_ResultStatus" json:"status,omitempty"`
	// 详细信息
	ErrorMessage      string `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`                  // 错误信息
	PlatformMessageId string `protobuf:"bytes,5,opt,name=platform_message_id,json=platformMessageId,proto3" json:"platform_message_id,omitempty"` // 平台消息ID（APNS/FCM等）
	PushTime          int64  `protobuf:"varint,6,opt,name=push_time,json=pushTime,proto3" json:"push_time,omitempty"`                             // 推送时间
	DeliveryTime      int64  `protobuf:"varint,7,opt,name=delivery_time,json=deliveryTime,proto3" json:"delivery_time,omitempty"`                 // 送达时间
	ConnectionId      string `protobuf:"bytes,8,opt,name=connection_id,json=connectionId,proto3" json:"connection_id,omitempty"`                  // 连接ID（WebSocket推送）
	// 扩展信息
	Details       map[string]string `protobuf:"bytes,9,rep,name=details,proto3" json:"details,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushResult) Reset() {
	*x = PushResult{}
	mi := &file_proto_common_push_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushResult) ProtoMessage() {}

func (x *PushResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_push_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushResult.ProtoReflect.Descriptor instead.
func (*PushResult) Descriptor() ([]byte, []int) {
	return file_proto_common_push_proto_rawDescGZIP(), []int{4}
}

func (x *PushResult) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *PushResult) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *PushResult) GetStatus() PushResult_ResultStatus {
	if x != nil {
		return x.Status
	}
	return PushResult_PENDING
}

func (x *PushResult) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *PushResult) GetPlatformMessageId() string {
	if x != nil {
		return x.PlatformMessageId
	}
	return ""
}

func (x *PushResult) GetPushTime() int64 {
	if x != nil {
		return x.PushTime
	}
	return 0
}

func (x *PushResult) GetDeliveryTime() int64 {
	if x != nil {
		return x.DeliveryTime
	}
	return 0
}

func (x *PushResult) GetConnectionId() string {
	if x != nil {
		return x.ConnectionId
	}
	return ""
}

func (x *PushResult) GetDetails() map[string]string {
	if x != nil {
		return x.Details
	}
	return nil
}

// ==================== 推送响应 ====================
type PushResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 推送ID
	PushId string `protobuf:"bytes,1,opt,name=push_id,json=pushId,proto3" json:"push_id,omitempty"`
	// 总体状态
	Accepted bool   `protobuf:"varint,2,opt,name=accepted,proto3" json:"accepted,omitempty"` // 是否已接受
	Success  bool   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`   // 总体是否成功
	Message  string `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`    // 响应消息
	// 统计信息
	TotalTargets int32 `protobuf:"varint,5,opt,name=total_targets,json=totalTargets,proto3" json:"total_targets,omitempty"` // 总设备目标数
	SuccessCount int32 `protobuf:"varint,6,opt,name=success_count,json=successCount,proto3" json:"success_count,omitempty"` // 成功数
	FailedCount  int32 `protobuf:"varint,7,opt,name=failed_count,json=failedCount,proto3" json:"failed_count,omitempty"`    // 失败数
	SkippedCount int32 `protobuf:"varint,8,opt,name=skipped_count,json=skippedCount,proto3" json:"skipped_count,omitempty"` // 跳过数
	// 详细结果
	Results []*PushResult `protobuf:"bytes,9,rep,name=results,proto3" json:"results,omitempty"`
	// 时间信息
	StartTime int64 `protobuf:"varint,10,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"` // 开始时间
	EndTime   int64 `protobuf:"varint,11,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`       // 结束时间
	// 扩展信息
	Stats         map[string]string `protobuf:"bytes,12,rep,name=stats,proto3" json:"stats,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushResponse) Reset() {
	*x = PushResponse{}
	mi := &file_proto_common_push_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushResponse) ProtoMessage() {}

func (x *PushResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_push_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushResponse.ProtoReflect.Descriptor instead.
func (*PushResponse) Descriptor() ([]byte, []int) {
	return file_proto_common_push_proto_rawDescGZIP(), []int{5}
}

func (x *PushResponse) GetPushId() string {
	if x != nil {
		return x.PushId
	}
	return ""
}

func (x *PushResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *PushResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PushResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *PushResponse) GetTotalTargets() int32 {
	if x != nil {
		return x.TotalTargets
	}
	return 0
}

func (x *PushResponse) GetSuccessCount() int32 {
	if x != nil {
		return x.SuccessCount
	}
	return 0
}

func (x *PushResponse) GetFailedCount() int32 {
	if x != nil {
		return x.FailedCount
	}
	return 0
}

func (x *PushResponse) GetSkippedCount() int32 {
	if x != nil {
		return x.SkippedCount
	}
	return 0
}

func (x *PushResponse) GetResults() []*PushResult {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *PushResponse) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *PushResponse) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *PushResponse) GetStats() map[string]string {
	if x != nil {
		return x.Stats
	}
	return nil
}

// 广播请求
type PushBroadcastRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Message        *Message               `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Options        *PushOptions           `protobuf:"bytes,2,opt,name=options,proto3" json:"options,omitempty"`
	RequestId      string                 `protobuf:"bytes,3,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	SourceService  string                 `protobuf:"bytes,4,opt,name=source_service,json=sourceService,proto3" json:"source_service,omitempty"`
	ExcludeUserIds []string               `protobuf:"bytes,5,rep,name=exclude_user_ids,json=excludeUserIds,proto3" json:"exclude_user_ids,omitempty"` // 排除的用户ID
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PushBroadcastRequest) Reset() {
	*x = PushBroadcastRequest{}
	mi := &file_proto_common_push_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushBroadcastRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushBroadcastRequest) ProtoMessage() {}

func (x *PushBroadcastRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_push_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushBroadcastRequest.ProtoReflect.Descriptor instead.
func (*PushBroadcastRequest) Descriptor() ([]byte, []int) {
	return file_proto_common_push_proto_rawDescGZIP(), []int{6}
}

func (x *PushBroadcastRequest) GetMessage() *Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *PushBroadcastRequest) GetOptions() *PushOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *PushBroadcastRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *PushBroadcastRequest) GetSourceService() string {
	if x != nil {
		return x.SourceService
	}
	return ""
}

func (x *PushBroadcastRequest) GetExcludeUserIds() []string {
	if x != nil {
		return x.ExcludeUserIds
	}
	return nil
}

var File_proto_common_push_proto protoreflect.FileDescriptor

const file_proto_common_push_proto_rawDesc = "" +
	"\n" +
	"\x17proto/common/push.proto\x12\x15com.bdsw.proto.common\x1a\x1aproto/common/message.proto\"D\n" +
	"\fDeviceTarget\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tdevice_id\x18\x02 \x01(\tR\bdeviceId\"Q\n" +
	"\x10DeviceTargetList\x12=\n" +
	"\adevices\x18\x01 \x03(\v2#.com.bdsw.proto.common.DeviceTargetR\adevices\"\xbe\a\n" +
	"\vPushRequest\x12\x17\n" +
	"\apush_id\x18\x01 \x01(\tR\x06pushId\x12N\n" +
	"\x0etarget_devices\x18\x02 \x01(\v2'.com.bdsw.proto.common.DeviceTargetListR\rtargetDevices\x128\n" +
	"\amessage\x18\x03 \x01(\v2\x1e.com.bdsw.proto.common.MessageR\amessage\x12<\n" +
	"\aoptions\x18\x04 \x01(\v2\".com.bdsw.proto.common.PushOptionsR\aoptions\x12H\n" +
	"\tpush_type\x18\x05 \x01(\x0e2+.com.bdsw.proto.common.PushRequest.PushTypeR\bpushType\x12$\n" +
	"\x0esource_user_id\x18\x06 \x01(\tR\fsourceUserId\x12(\n" +
	"\x10source_device_id\x18\a \x01(\tR\x0esourceDeviceId\x12\x1d\n" +
	"\n" +
	"request_id\x18\b \x01(\tR\trequestId\x12%\n" +
	"\x0esource_service\x18\t \x01(\tR\rsourceService\x12*\n" +
	"\x10original_user_id\x18\n" +
	" \x01(\tH\x00R\x0eoriginalUserId\x12,\n" +
	"\x11original_group_id\x18\v \x01(\tH\x00R\x0foriginalGroupId\x12:\n" +
	"\x18original_conversation_id\x18\f \x01(\tH\x00R\x16originalConversationId\x12\x1f\n" +
	"\vcreate_time\x18\r \x01(\x03R\n" +
	"createTime\x12#\n" +
	"\rschedule_time\x18\x0e \x01(\x03R\fscheduleTime\x12F\n" +
	"\x06extras\x18\x0f \x03(\v2..com.bdsw.proto.common.PushRequest.ExtrasEntryR\x06extras\x1a9\n" +
	"\vExtrasEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"|\n" +
	"\bPushType\x12\x0f\n" +
	"\vSINGLE_USER\x10\x00\x12\x0e\n" +
	"\n" +
	"MULTI_USER\x10\x01\x12\x11\n" +
	"\rSINGLE_DEVICE\x10\x02\x12\x10\n" +
	"\fMULTI_DEVICE\x10\x03\x12\t\n" +
	"\x05GROUP\x10\x04\x12\x10\n" +
	"\fCONVERSATION\x10\x05\x12\r\n" +
	"\tBROADCAST\x10\x06B\x11\n" +
	"\x0foriginal_target\"\xc3\a\n" +
	"\vPushOptions\x12G\n" +
	"\bpriority\x18\x01 \x01(\x0e2+.com.bdsw.proto.common.PushOptions.PriorityR\bpriority\x12!\n" +
	"\fneed_persist\x18\x02 \x01(\bR\vneedPersist\x12\x1d\n" +
	"\n" +
	"need_store\x18\x03 \x01(\bR\tneedStore\x12!\n" +
	"\fneed_receipt\x18\x04 \x01(\bR\vneedReceipt\x12*\n" +
	"\x11need_read_receipt\x18\x05 \x01(\bR\x0fneedReadReceipt\x12&\n" +
	"\x0fskip_if_offline\x18\x06 \x01(\bR\rskipIfOffline\x12\x1f\n" +
	"\vexpire_time\x18\a \x01(\x03R\n" +
	"expireTime\x12\x1b\n" +
	"\tmax_retry\x18\b \x01(\x05R\bmaxRetry\x12%\n" +
	"\x0eretry_interval\x18\t \x01(\x03R\rretryInterval\x12+\n" +
	"\x11show_notification\x18\n" +
	" \x01(\bR\x10showNotification\x12-\n" +
	"\x12notification_title\x18\v \x01(\tR\x11notificationTitle\x12+\n" +
	"\x11notification_body\x18\f \x01(\tR\x10notificationBody\x12-\n" +
	"\x12notification_sound\x18\r \x01(\tR\x11notificationSound\x12T\n" +
	"\rsync_strategy\x18\x0e \x01(\x0e2/.com.bdsw.proto.common.PushOptions.SyncStrategyR\fsyncStrategy\x12\x1b\n" +
	"\tdedup_key\x18\x0f \x01(\tR\bdedupKey\x12!\n" +
	"\fdedup_window\x18\x10 \x01(\x05R\vdedupWindow\x12F\n" +
	"\x06extras\x18\x11 \x03(\v2..com.bdsw.proto.common.PushOptions.ExtrasEntryR\x06extras\x1a9\n" +
	"\vExtrasEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"7\n" +
	"\bPriority\x12\a\n" +
	"\x03LOW\x10\x00\x12\n" +
	"\n" +
	"\x06NORMAL\x10\x01\x12\b\n" +
	"\x04HIGH\x10\x02\x12\f\n" +
	"\bCRITICAL\x10\x03\"C\n" +
	"\fSyncStrategy\x12\f\n" +
	"\bSYNC_ALL\x10\x00\x12\x16\n" +
	"\x12SYNC_EXCEPT_SOURCE\x10\x01\x12\r\n" +
	"\tSYNC_NONE\x10\x02\"\x9d\x04\n" +
	"\n" +
	"PushResult\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tdevice_id\x18\x02 \x01(\tR\bdeviceId\x12F\n" +
	"\x06status\x18\x03 \x01(\x0e2..com.bdsw.proto.common.PushResult.ResultStatusR\x06status\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage\x12.\n" +
	"\x13platform_message_id\x18\x05 \x01(\tR\x11platformMessageId\x12\x1b\n" +
	"\tpush_time\x18\x06 \x01(\x03R\bpushTime\x12#\n" +
	"\rdelivery_time\x18\a \x01(\x03R\fdeliveryTime\x12#\n" +
	"\rconnection_id\x18\b \x01(\tR\fconnectionId\x12H\n" +
	"\adetails\x18\t \x03(\v2..com.bdsw.proto.common.PushResult.DetailsEntryR\adetails\x1a:\n" +
	"\fDetailsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"O\n" +
	"\fResultStatus\x12\v\n" +
	"\aPENDING\x10\x00\x12\v\n" +
	"\aSUCCESS\x10\x01\x12\n" +
	"\n" +
	"\x06FAILED\x10\x02\x12\v\n" +
	"\aSKIPPED\x10\x03\x12\f\n" +
	"\bRETRYING\x10\x04\"\x80\x04\n" +
	"\fPushResponse\x12\x17\n" +
	"\apush_id\x18\x01 \x01(\tR\x06pushId\x12\x1a\n" +
	"\baccepted\x18\x02 \x01(\bR\baccepted\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12#\n" +
	"\rtotal_targets\x18\x05 \x01(\x05R\ftotalTargets\x12#\n" +
	"\rsuccess_count\x18\x06 \x01(\x05R\fsuccessCount\x12!\n" +
	"\ffailed_count\x18\a \x01(\x05R\vfailedCount\x12#\n" +
	"\rskipped_count\x18\b \x01(\x05R\fskippedCount\x12;\n" +
	"\aresults\x18\t \x03(\v2!.com.bdsw.proto.common.PushResultR\aresults\x12\x1d\n" +
	"\n" +
	"start_time\x18\n" +
	" \x01(\x03R\tstartTime\x12\x19\n" +
	"\bend_time\x18\v \x01(\x03R\aendTime\x12D\n" +
	"\x05stats\x18\f \x03(\v2..com.bdsw.proto.common.PushResponse.StatsEntryR\x05stats\x1a8\n" +
	"\n" +
	"StatsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xfe\x01\n" +
	"\x14PushBroadcastRequest\x128\n" +
	"\amessage\x18\x01 \x01(\v2\x1e.com.bdsw.proto.common.MessageR\amessage\x12<\n" +
	"\aoptions\x18\x02 \x01(\v2\".com.bdsw.proto.common.PushOptionsR\aoptions\x12\x1d\n" +
	"\n" +
	"request_id\x18\x03 \x01(\tR\trequestId\x12%\n" +
	"\x0esource_service\x18\x04 \x01(\tR\rsourceService\x12(\n" +
	"\x10exclude_user_ids\x18\x05 \x03(\tR\x0eexcludeUserIdsBT\n" +
	"\x15com.bdsw.proto.commonB\tPushProtoP\x01Z.github.com/bdsw/bdsw-im-ws/proto/common;commonb\x06proto3"

var (
	file_proto_common_push_proto_rawDescOnce sync.Once
	file_proto_common_push_proto_rawDescData []byte
)

func file_proto_common_push_proto_rawDescGZIP() []byte {
	file_proto_common_push_proto_rawDescOnce.Do(func() {
		file_proto_common_push_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_common_push_proto_rawDesc), len(file_proto_common_push_proto_rawDesc)))
	})
	return file_proto_common_push_proto_rawDescData
}

var file_proto_common_push_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_proto_common_push_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_proto_common_push_proto_goTypes = []any{
	(PushRequest_PushType)(0),     // 0: com.bdsw.proto.common.PushRequest.PushType
	(PushOptions_Priority)(0),     // 1: com.bdsw.proto.common.PushOptions.Priority
	(PushOptions_SyncStrategy)(0), // 2: com.bdsw.proto.common.PushOptions.SyncStrategy
	(PushResult_ResultStatus)(0),  // 3: com.bdsw.proto.common.PushResult.ResultStatus
	(*DeviceTarget)(nil),          // 4: com.bdsw.proto.common.DeviceTarget
	(*DeviceTargetList)(nil),      // 5: com.bdsw.proto.common.DeviceTargetList
	(*PushRequest)(nil),           // 6: com.bdsw.proto.common.PushRequest
	(*PushOptions)(nil),           // 7: com.bdsw.proto.common.PushOptions
	(*PushResult)(nil),            // 8: com.bdsw.proto.common.PushResult
	(*PushResponse)(nil),          // 9: com.bdsw.proto.common.PushResponse
	(*PushBroadcastRequest)(nil),  // 10: com.bdsw.proto.common.PushBroadcastRequest
	nil,                           // 11: com.bdsw.proto.common.PushRequest.ExtrasEntry
	nil,                           // 12: com.bdsw.proto.common.PushOptions.ExtrasEntry
	nil,                           // 13: com.bdsw.proto.common.PushResult.DetailsEntry
	nil,                           // 14: com.bdsw.proto.common.PushResponse.StatsEntry
	(*Message)(nil),               // 15: com.bdsw.proto.common.Message
}
var file_proto_common_push_proto_depIdxs = []int32{
	4,  // 0: com.bdsw.proto.common.DeviceTargetList.devices:type_name -> com.bdsw.proto.common.DeviceTarget
	5,  // 1: com.bdsw.proto.common.PushRequest.target_devices:type_name -> com.bdsw.proto.common.DeviceTargetList
	15, // 2: com.bdsw.proto.common.PushRequest.message:type_name -> com.bdsw.proto.common.Message
	7,  // 3: com.bdsw.proto.common.PushRequest.options:type_name -> com.bdsw.proto.common.PushOptions
	0,  // 4: com.bdsw.proto.common.PushRequest.push_type:type_name -> com.bdsw.proto.common.PushRequest.PushType
	11, // 5: com.bdsw.proto.common.PushRequest.extras:type_name -> com.bdsw.proto.common.PushRequest.ExtrasEntry
	1,  // 6: com.bdsw.proto.common.PushOptions.priority:type_name -> com.bdsw.proto.common.PushOptions.Priority
	2,  // 7: com.bdsw.proto.common.PushOptions.sync_strategy:type_name -> com.bdsw.proto.common.PushOptions.SyncStrategy
	12, // 8: com.bdsw.proto.common.PushOptions.extras:type_name -> com.bdsw.proto.common.PushOptions.ExtrasEntry
	3,  // 9: com.bdsw.proto.common.PushResult.status:type_name -> com.bdsw.proto.common.PushResult.ResultStatus
	13, // 10: com.bdsw.proto.common.PushResult.details:type_name -> com.bdsw.proto.common.PushResult.DetailsEntry
	8,  // 11: com.bdsw.proto.common.PushResponse.results:type_name -> com.bdsw.proto.common.PushResult
	14, // 12: com.bdsw.proto.common.PushResponse.stats:type_name -> com.bdsw.proto.common.PushResponse.StatsEntry
	15, // 13: com.bdsw.proto.common.PushBroadcastRequest.message:type_name -> com.bdsw.proto.common.Message
	7,  // 14: com.bdsw.proto.common.PushBroadcastRequest.options:type_name -> com.bdsw.proto.common.PushOptions
	15, // [15:15] is the sub-list for method output_type
	15, // [15:15] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_proto_common_push_proto_init() }
func file_proto_common_push_proto_init() {
	if File_proto_common_push_proto != nil {
		return
	}
	file_proto_common_message_proto_init()
	file_proto_common_push_proto_msgTypes[2].OneofWrappers = []any{
		(*PushRequest_OriginalUserId)(nil),
		(*PushRequest_OriginalGroupId)(nil),
		(*PushRequest_OriginalConversationId)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_common_push_proto_rawDesc), len(file_proto_common_push_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_common_push_proto_goTypes,
		DependencyIndexes: file_proto_common_push_proto_depIdxs,
		EnumInfos:         file_proto_common_push_proto_enumTypes,
		MessageInfos:      file_proto_common_push_proto_msgTypes,
	}.Build()
	File_proto_common_push_proto = out.File
	file_proto_common_push_proto_goTypes = nil
	file_proto_common_push_proto_depIdxs = nil
}
