// Code generated by protoc-gen-go-triple. DO NOT EDIT.
// versions:
// - protoc-gen-go-triple v1.0.8
// - protoc             v6.32.1
// source: api/muc/muc.proto

package muc

import (
	context "context"
	protocol "dubbo.apache.org/dubbo-go/v3/protocol"
	dubbo3 "dubbo.apache.org/dubbo-go/v3/protocol/dubbo3"
	invocation "dubbo.apache.org/dubbo-go/v3/protocol/invocation"
	common1 "github.com/bdsw/bdsw-im-ws/api/common"
	grpc_go "github.com/dubbogo/grpc-go"
	codes "github.com/dubbogo/grpc-go/codes"
	metadata "github.com/dubbogo/grpc-go/metadata"
	status "github.com/dubbogo/grpc-go/status"
	common "github.com/dubbogo/triple/pkg/common"
	constant "github.com/dubbogo/triple/pkg/common/constant"
	triple "github.com/dubbogo/triple/pkg/triple"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc_go.SupportPackageIsVersion7

// MUCServiceClient is the client API for MUCService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MUCServiceClient interface {
	// Token 验证
	ValidateToken(ctx context.Context, in *TokenValidateRequest, opts ...grpc_go.CallOption) (*TokenValidateResponse, common.ErrorWithAttachment)
	// 刷新 Token
	RefreshToken(ctx context.Context, in *RefreshTokenRequest, opts ...grpc_go.CallOption) (*RefreshTokenResponse, common.ErrorWithAttachment)
	// 获取用户权限
	GetUserPermissions(ctx context.Context, in *GetUserPermissionsRequest, opts ...grpc_go.CallOption) (*GetUserPermissionsResponse, common.ErrorWithAttachment)
	// 用户登录
	Login(ctx context.Context, in *LoginRequest, opts ...grpc_go.CallOption) (*LoginResponse, common.ErrorWithAttachment)
	// 用户登出
	Logout(ctx context.Context, in *LogoutRequest, opts ...grpc_go.CallOption) (*common1.BaseResponse, common.ErrorWithAttachment)
}

type mUCServiceClient struct {
	cc *triple.TripleConn
}

type MUCServiceClientImpl struct {
	ValidateToken      func(ctx context.Context, in *TokenValidateRequest) (*TokenValidateResponse, error)
	RefreshToken       func(ctx context.Context, in *RefreshTokenRequest) (*RefreshTokenResponse, error)
	GetUserPermissions func(ctx context.Context, in *GetUserPermissionsRequest) (*GetUserPermissionsResponse, error)
	Login              func(ctx context.Context, in *LoginRequest) (*LoginResponse, error)
	Logout             func(ctx context.Context, in *LogoutRequest) (*common1.BaseResponse, error)
}

func (c *MUCServiceClientImpl) GetDubboStub(cc *triple.TripleConn) MUCServiceClient {
	return NewMUCServiceClient(cc)
}

func (c *MUCServiceClientImpl) XXX_InterfaceName() string {
	return "com.bdsw.muc.MUCService"
}

func NewMUCServiceClient(cc *triple.TripleConn) MUCServiceClient {
	return &mUCServiceClient{cc}
}

func (c *mUCServiceClient) ValidateToken(ctx context.Context, in *TokenValidateRequest, opts ...grpc_go.CallOption) (*TokenValidateResponse, common.ErrorWithAttachment) {
	out := new(TokenValidateResponse)
	interfaceKey := ctx.Value(constant.InterfaceKey).(string)
	return out, c.cc.Invoke(ctx, "/"+interfaceKey+"/ValidateToken", in, out)
}

func (c *mUCServiceClient) RefreshToken(ctx context.Context, in *RefreshTokenRequest, opts ...grpc_go.CallOption) (*RefreshTokenResponse, common.ErrorWithAttachment) {
	out := new(RefreshTokenResponse)
	interfaceKey := ctx.Value(constant.InterfaceKey).(string)
	return out, c.cc.Invoke(ctx, "/"+interfaceKey+"/RefreshToken", in, out)
}

func (c *mUCServiceClient) GetUserPermissions(ctx context.Context, in *GetUserPermissionsRequest, opts ...grpc_go.CallOption) (*GetUserPermissionsResponse, common.ErrorWithAttachment) {
	out := new(GetUserPermissionsResponse)
	interfaceKey := ctx.Value(constant.InterfaceKey).(string)
	return out, c.cc.Invoke(ctx, "/"+interfaceKey+"/GetUserPermissions", in, out)
}

func (c *mUCServiceClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc_go.CallOption) (*LoginResponse, common.ErrorWithAttachment) {
	out := new(LoginResponse)
	interfaceKey := ctx.Value(constant.InterfaceKey).(string)
	return out, c.cc.Invoke(ctx, "/"+interfaceKey+"/Login", in, out)
}

func (c *mUCServiceClient) Logout(ctx context.Context, in *LogoutRequest, opts ...grpc_go.CallOption) (*common1.BaseResponse, common.ErrorWithAttachment) {
	out := new(common1.BaseResponse)
	interfaceKey := ctx.Value(constant.InterfaceKey).(string)
	return out, c.cc.Invoke(ctx, "/"+interfaceKey+"/Logout", in, out)
}

// MUCServiceServer is the server API for MUCService service.
// All implementations must embed UnimplementedMUCServiceServer
// for forward compatibility
type MUCServiceServer interface {
	// Token 验证
	ValidateToken(context.Context, *TokenValidateRequest) (*TokenValidateResponse, error)
	// 刷新 Token
	RefreshToken(context.Context, *RefreshTokenRequest) (*RefreshTokenResponse, error)
	// 获取用户权限
	GetUserPermissions(context.Context, *GetUserPermissionsRequest) (*GetUserPermissionsResponse, error)
	// 用户登录
	Login(context.Context, *LoginRequest) (*LoginResponse, error)
	// 用户登出
	Logout(context.Context, *LogoutRequest) (*common1.BaseResponse, error)
	mustEmbedUnimplementedMUCServiceServer()
}

// UnimplementedMUCServiceServer must be embedded to have forward compatible implementations.
type UnimplementedMUCServiceServer struct {
	proxyImpl protocol.Invoker
}

func (UnimplementedMUCServiceServer) ValidateToken(context.Context, *TokenValidateRequest) (*TokenValidateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ValidateToken not implemented")
}
func (UnimplementedMUCServiceServer) RefreshToken(context.Context, *RefreshTokenRequest) (*RefreshTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RefreshToken not implemented")
}
func (UnimplementedMUCServiceServer) GetUserPermissions(context.Context, *GetUserPermissionsRequest) (*GetUserPermissionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserPermissions not implemented")
}
func (UnimplementedMUCServiceServer) Login(context.Context, *LoginRequest) (*LoginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedMUCServiceServer) Logout(context.Context, *LogoutRequest) (*common1.BaseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Logout not implemented")
}
func (s *UnimplementedMUCServiceServer) XXX_SetProxyImpl(impl protocol.Invoker) {
	s.proxyImpl = impl
}

func (s *UnimplementedMUCServiceServer) XXX_GetProxyImpl() protocol.Invoker {
	return s.proxyImpl
}

func (s *UnimplementedMUCServiceServer) XXX_ServiceDesc() *grpc_go.ServiceDesc {
	return &MUCService_ServiceDesc
}
func (s *UnimplementedMUCServiceServer) XXX_InterfaceName() string {
	return "com.bdsw.muc.MUCService"
}

func (UnimplementedMUCServiceServer) mustEmbedUnimplementedMUCServiceServer() {}

// UnsafeMUCServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MUCServiceServer will
// result in compilation errors.
type UnsafeMUCServiceServer interface {
	mustEmbedUnimplementedMUCServiceServer()
}

func RegisterMUCServiceServer(s grpc_go.ServiceRegistrar, srv MUCServiceServer) {
	s.RegisterService(&MUCService_ServiceDesc, srv)
}

func _MUCService_ValidateToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc_go.UnaryServerInterceptor) (interface{}, error) {
	in := new(TokenValidateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	base := srv.(dubbo3.Dubbo3GrpcService)
	args := []interface{}{}
	args = append(args, in)
	md, _ := metadata.FromIncomingContext(ctx)
	invAttachment := make(map[string]interface{}, len(md))
	for k, v := range md {
		invAttachment[k] = v
	}
	invo := invocation.NewRPCInvocation("ValidateToken", args, invAttachment)
	if interceptor == nil {
		result := base.XXX_GetProxyImpl().Invoke(ctx, invo)
		return result, result.Error()
	}
	info := &grpc_go.UnaryServerInfo{
		Server:     srv,
		FullMethod: ctx.Value("XXX_TRIPLE_GO_INTERFACE_NAME").(string),
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		result := base.XXX_GetProxyImpl().Invoke(ctx, invo)
		return result, result.Error()
	}
	return interceptor(ctx, in, info, handler)
}

func _MUCService_RefreshToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc_go.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefreshTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	base := srv.(dubbo3.Dubbo3GrpcService)
	args := []interface{}{}
	args = append(args, in)
	md, _ := metadata.FromIncomingContext(ctx)
	invAttachment := make(map[string]interface{}, len(md))
	for k, v := range md {
		invAttachment[k] = v
	}
	invo := invocation.NewRPCInvocation("RefreshToken", args, invAttachment)
	if interceptor == nil {
		result := base.XXX_GetProxyImpl().Invoke(ctx, invo)
		return result, result.Error()
	}
	info := &grpc_go.UnaryServerInfo{
		Server:     srv,
		FullMethod: ctx.Value("XXX_TRIPLE_GO_INTERFACE_NAME").(string),
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		result := base.XXX_GetProxyImpl().Invoke(ctx, invo)
		return result, result.Error()
	}
	return interceptor(ctx, in, info, handler)
}

func _MUCService_GetUserPermissions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc_go.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserPermissionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	base := srv.(dubbo3.Dubbo3GrpcService)
	args := []interface{}{}
	args = append(args, in)
	md, _ := metadata.FromIncomingContext(ctx)
	invAttachment := make(map[string]interface{}, len(md))
	for k, v := range md {
		invAttachment[k] = v
	}
	invo := invocation.NewRPCInvocation("GetUserPermissions", args, invAttachment)
	if interceptor == nil {
		result := base.XXX_GetProxyImpl().Invoke(ctx, invo)
		return result, result.Error()
	}
	info := &grpc_go.UnaryServerInfo{
		Server:     srv,
		FullMethod: ctx.Value("XXX_TRIPLE_GO_INTERFACE_NAME").(string),
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		result := base.XXX_GetProxyImpl().Invoke(ctx, invo)
		return result, result.Error()
	}
	return interceptor(ctx, in, info, handler)
}

func _MUCService_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc_go.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	base := srv.(dubbo3.Dubbo3GrpcService)
	args := []interface{}{}
	args = append(args, in)
	md, _ := metadata.FromIncomingContext(ctx)
	invAttachment := make(map[string]interface{}, len(md))
	for k, v := range md {
		invAttachment[k] = v
	}
	invo := invocation.NewRPCInvocation("Login", args, invAttachment)
	if interceptor == nil {
		result := base.XXX_GetProxyImpl().Invoke(ctx, invo)
		return result, result.Error()
	}
	info := &grpc_go.UnaryServerInfo{
		Server:     srv,
		FullMethod: ctx.Value("XXX_TRIPLE_GO_INTERFACE_NAME").(string),
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		result := base.XXX_GetProxyImpl().Invoke(ctx, invo)
		return result, result.Error()
	}
	return interceptor(ctx, in, info, handler)
}

func _MUCService_Logout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc_go.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogoutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	base := srv.(dubbo3.Dubbo3GrpcService)
	args := []interface{}{}
	args = append(args, in)
	md, _ := metadata.FromIncomingContext(ctx)
	invAttachment := make(map[string]interface{}, len(md))
	for k, v := range md {
		invAttachment[k] = v
	}
	invo := invocation.NewRPCInvocation("Logout", args, invAttachment)
	if interceptor == nil {
		result := base.XXX_GetProxyImpl().Invoke(ctx, invo)
		return result, result.Error()
	}
	info := &grpc_go.UnaryServerInfo{
		Server:     srv,
		FullMethod: ctx.Value("XXX_TRIPLE_GO_INTERFACE_NAME").(string),
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		result := base.XXX_GetProxyImpl().Invoke(ctx, invo)
		return result, result.Error()
	}
	return interceptor(ctx, in, info, handler)
}

// MUCService_ServiceDesc is the grpc_go.ServiceDesc for MUCService service.
// It's only intended for direct use with grpc_go.RegisterService,
// and not to be introspected or modified (even as a copy)
var MUCService_ServiceDesc = grpc_go.ServiceDesc{
	ServiceName: "com.bdsw.muc.MUCService",
	HandlerType: (*MUCServiceServer)(nil),
	Methods: []grpc_go.MethodDesc{
		{
			MethodName: "ValidateToken",
			Handler:    _MUCService_ValidateToken_Handler,
		},
		{
			MethodName: "RefreshToken",
			Handler:    _MUCService_RefreshToken_Handler,
		},
		{
			MethodName: "GetUserPermissions",
			Handler:    _MUCService_GetUserPermissions_Handler,
		},
		{
			MethodName: "Login",
			Handler:    _MUCService_Login_Handler,
		},
		{
			MethodName: "Logout",
			Handler:    _MUCService_Logout_Handler,
		},
	},
	Streams:  []grpc_go.StreamDesc{},
	Metadata: "api/muc/muc.proto",
}
